[config]
default_to_workspace = false
skip_core_tasks = true

[tasks.build]
script = '''
#!@duckscript

exec cargo build --target wasm32-wasi --release --package tairitsu-proto
exec cargo build --package tairitsu-vm
'''
