// @ts-nocheck
// Auto-generated by build_npm_glue_packages.py

// === resizeObserver ===
export const resizeObserver_exports = {
  observe(self, target, options) {
    const observer = globalThis.__lookupElement(self);
    const el = globalThis.__lookupElement(target);
    if (observer && el) {
      observer.observe(el, options);
    }
  },
  unobserve(self, target) {
    const observer = globalThis.__lookupElement(self);
    const el = globalThis.__lookupElement(target);
    if (observer && el) {
      observer.unobserve(el);
    }
  },
  disconnect(self) {
    const observer = globalThis.__lookupElement(self);
    if (observer) {
      observer.disconnect();
    }
  },
};

// === resizeObserverEntry ===
export const resizeObserverEntry_exports = {
  getTarget(self) {
    if (!globalThis.__resizeObserverEntryHandles) return 0n;
    const entry = globalThis.__resizeObserverEntryHandles.get(self);
    if (!entry) return 0n;
    return globalThis.__storeElement(entry.target);
  },
  getContentRect(self) {
    if (!globalThis.__resizeObserverEntryHandles) return 0n;
    const entry = globalThis.__resizeObserverEntryHandles.get(self);
    if (!entry) return 0n;
    if (!globalThis.__domRectHandles) { globalThis.__domRectHandles = new Map(); globalThis.__nextDomRectHandle = 1n; }
    const handle = globalThis.__nextDomRectHandle++;
    globalThis.__domRectHandles.set(handle, entry.contentRect);
    return handle;
  },
  getBorderBoxSize(self) {
    if (!globalThis.__resizeObserverEntryHandles) return [];
    const entry = globalThis.__resizeObserverEntryHandles.get(self);
    if (!entry) return [];
    if (!globalThis.__resizeObserverSizeHandles) { globalThis.__resizeObserverSizeHandles = new Map(); globalThis.__nextResizeObserverSizeHandle = 1n; }
    return [...entry.borderBoxSize].map(function (size) {
      const handle = globalThis.__nextResizeObserverSizeHandle++;
      globalThis.__resizeObserverSizeHandles.set(handle, size);
      return handle;
    });
  },
  getContentBoxSize(self) {
    if (!globalThis.__resizeObserverEntryHandles) return [];
    const entry = globalThis.__resizeObserverEntryHandles.get(self);
    if (!entry) return [];
    if (!globalThis.__resizeObserverSizeHandles) { globalThis.__resizeObserverSizeHandles = new Map(); globalThis.__nextResizeObserverSizeHandle = 1n; }
    return [...entry.contentBoxSize].map(function (size) {
      const handle = globalThis.__nextResizeObserverSizeHandle++;
      globalThis.__resizeObserverSizeHandles.set(handle, size);
      return handle;
    });
  },
};

// === resizeObserverSize ===
export const resizeObserverSize_exports = {
  getInlineSize(self) {
    if (!globalThis.__resizeObserverSizeHandles) return 0;
    const size = globalThis.__resizeObserverSizeHandles.get(self);
    return size ? size.inlineSize : 0;
  },
  getBlockSize(self) {
    if (!globalThis.__resizeObserverSizeHandles) return 0;
    const size = globalThis.__resizeObserverSizeHandles.get(self);
    return size ? size.blockSize : 0;
  },
};

// === Registry ===
export const INTERFACES = {
  "@tairitsu-glue/resize-observer": resizeObserver_exports,
  "@tairitsu-glue/resize-observer-entry": resizeObserverEntry_exports,
  "@tairitsu-glue/resize-observer-size": resizeObserverSize_exports,
};
