[package]
authors = ["langyo <langyo.china@gmail.com>"]
name = "tairitsu-router"

version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
tairitsu-database = { path = "../database" }
tairitsu-utils = { path = "../utils" }

anyhow = "^1"
async-std = { version = "^1", features = ["attributes", "tokio1"] }
base64 = "^0.22"
chrono = { version = "^0.4", features = ["serde", "unstable-locales"] }
env_logger = "^0.11"
lazy_static = "*"
log = "^0.4"
serde = { version = "^1", features = ["derive"] }
serde_json = "^1"
url = "^2"
tokio = { version = "^1", features = ["full"] }
uuid = { version = "^1", features = [
  'v4',
  'fast-rng',
  'macro-diagnostics',
  'serde',
] }

axum = { version = "^0.7", features = ["query"] }
clap = { version = "^4", features = ["derive"] }
futures = { version = "^0.3", features = ["std"], default-features = false }
hyper = { version = "^1", features = ["full"] }
http-body-util = "0.1"
hyper-util = { version = "0.1", features = ["full"] }
tower = { version = "^0.4", features = ["make"] }
tracing = "^0.1"
tracing-subscriber = "^0.3"
stylist = { version = "^0.13", features = ["yew_integration", "ssr"] }
yew = { version = "^0.21", features = ["ssr", "hydration"] }

[dev-dependencies.web-sys]
features = [
  "Window",
  "Document",
  "Element",
  "HtmlElement",
  "HtmlHeadElement",
  "HtmlStyleElement",
  "CssStyleDeclaration",
]
version = "0.3"

[dependencies.tower-http]
features = ["fs", "trace", "compression-gzip"]
version = "^0.5"
