[package]
authors = ["langyo <langyo.china@gmail.com>"]
name = "tairitsu-database-driver-cloudflare"

version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
tairitsu-database-types = { path = "../database_types" }

anyhow = "^1"
chrono = { version = "^0.4", features = [
    "serde",
    "wasmbind",
    "unstable-locales",
] }
log = "^0.4"
serde = { version = "^1", features = ["derive"] }
serde_json = { version = "^1" }
strum = { version = "^0.26", features = ["derive"] }
uuid = { version = "^1", features = [
    'v4',
    'fast-rng',
    'macro-diagnostics',
    'serde',
] }
bytes = "^1"

async-trait = "^0.1"
oneshot = "^0.1"

sea-orm = { version = "1.1.0-rc.1", features = ["proxy"] }
sqlparser = { version = "^0.48", optional = true }

wasm-bindgen = { version = "0.2.87" }
wasm-bindgen-futures = { version = "^0.4" }
worker = { version = "^0.3", features = ["d1"] }
