[package]
authors = ["langyo <langyo.china@gmail.com>"]
name = "tairitsu-proto"

version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
tairitsu-utils = { path = "../utils", version = "*" }

serde = { version = "^1", features = ["derive"] }
serde_json = "^1"
anyhow = "^1"
tokio_wasi = { version = "^1", features = ["full"] }

sea-orm = { git = "https://github.com/langyo/sea-orm", branch = "proxy-conn", features = [
  "proxy",
] }
