[package]
authors = ["langyo <langyo.china@gmail.com>"]
name = "tairitsu-proto"

version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
tairitsu-utils = { path = "../utils", version = "*" }

ron = "^0.8"
serde = { version = "^1", features = ["derive"] }
anyhow = "^1"
tokio_wasi = { version = "^1", features = ["full"] }
