[package]
authors = ["langyo <langyo.china@gmail.com>"]
name = "tairitsu-database"

version = "0.1.0"
edition = "2021"
publish = false
resolver = "2"

[dependencies]
tairitsu-database-types = { path = "../database_types" }

anyhow = "^1"
chrono = { version = "^0.4", features = [
    "serde",
    "wasmbind",
    "unstable-locales",
] }
log = "^0.4"
serde = { version = "^1", features = ["derive"] }
serde_json = { version = "^1" }
strum = { version = "^0.26", features = ["derive"] }
uuid = { version = "^1", features = [
    'v4',
    'fast-rng',
    'macro-diagnostics',
    'serde',
] }
bytes = "^1"

async-trait = "^0.1"
cfg-if = "^1"
sea-orm = "1.1.0-rc.1"
worker = "^0.3"

# [target.'cfg(all(any(target_arch = "wasm32", target_arch = "wasm64"), not(target_os = "wasi")))'.dependencies]
tairitsu-database-driver-cloudflare = { path = "../database_driver_cloudflare" }

[target.'cfg(not(any(target_arch = "wasm32", target_arch = "wasm64")))'.dependencies]
tairitsu-database-driver-native = { path = "../database_driver_native" }

# [target.'cfg(all(any(target_arch = "wasm32", target_arch = "wasm64"), target_os = "wasi"))'.dependencies]
tairitsu-database-driver-wasi = { path = "../database_driver_wasi" }

[features]
default = []
cloudflare = []
native = []
wasi = []
