[package]
authors = ["langyo <langyo.china@gmail.com>"]
name = "tairitsu-database"

version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
tairitsu-utils = { path = "../utils" }

anyhow = "^1"
chrono = { version = "^0.4", features = ["serde", "unstable-locales"] }
env_logger = "^0.10"
lazy_static = "*"
log = "^0.4"
strum = "^0.25"
strum_macros = "^0.25"
uuid = { version = "^1", features = [
  'v4',
  'fast-rng',
  'macro-diagnostics',
  'serde',
] }

sea-orm-migration = "^0.12"
serde = { version = "^1", features = ["derive"] }
serde_json = "^1"
async-std = { version = "^1", features = ["attributes", "tokio1"] }

[dependencies.sea-orm]
features = [
  "sqlx-mysql",
  "runtime-async-std-rustls",
  "with-uuid",
  "with-chrono",
  "with-json",
]
version = "^0.12"
