[package]
authors = ["langyo <langyo.china@gmail.com>"]
name = "tairitsu-database"

version = "0.1.0"
edition = "2021"
publish = false
resolver = "2"

[dependencies]
tairitsu-database-types = { path = "../database_types" }

# [target.'cfg(all(any(target_arch = "wasm32", target_arch = "wasm64"), not(target_os = "wasi")))'.dependencies]
tairitsu-database-driver-cloudflare = { path = "../database_driver_cloudflare" }

[target.'cfg(not(any(target_arch = "wasm32", target_arch = "wasm64")))'.dependencies]
tairitsu-database-driver-native = { path = "../database_driver_native" }

# [target.'cfg(all(any(target_arch = "wasm32", target_arch = "wasm64"), target_os = "wasi"))'.dependencies]
tairitsu-database-driver-wasi = { path = "../database_driver_wasi" }

[features]
default = []
cloudflare = []
native = []
wasi = []
