[package]
authors = ["langyo <langyo.china@gmail.com>"]
name = "tairitsu-macro-types"

version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
anyhow = "^1"
async-trait = "^0.1"
base64 = "^0.21"
derive_more = "^0.99"
serde = { version = "^1", features = ["derive"] }
serde_json = "^1"
strum = "^0.25"
strum_macros = "^0.25"
