// @ts-nocheck
// Auto-generated by build_npm_glue_packages.py

// === window ===
export const window_exports = {
  getInnerWidth() {
    return window.innerWidth;
  },
  getInnerHeight() {
    return window.innerHeight;
  },
  getComputedStyle(elt: number, pseudoElt?: string): number {
    const el = globalThis.__lookupElement(elt);
    const result = window.getComputedStyle(el, pseudoElt);
    const handle = globalThis.__nextCssStyleDeclarationHandle++;
    globalThis.__cssStyleDeclarationHandles.set(handle, result);
    return handle;
  },
};

// === location ===
// Location interface - provides hash and viewport info for WIT browser world

export const location_exports = {
  getHash() {
    return window.location.hash || '';
  },
  getInnerWidth() {
    return window.innerWidth;
  },
  getPathname() {
    return window.location.pathname || '/';
  },
};

// === history ===
// History interface - provides browser history API for WIT browser world

export const history_exports = {
  getLength() {
    return window.history.length;
  },
  getScrollRestoration() {
    const value = window.history.scrollRestoration;
    switch (value) {
      case 'auto': return 0n;
      case 'manual': return 1n;
      default: return 0n;
    }
  },
  setScrollRestoration(value) {
    let enumValue;
    if (value === 0n) { enumValue = 'auto'; }
    else if (value === 1n) { enumValue = 'manual'; }
    else { enumValue = 'auto'; }
    window.history.scrollRestoration = enumValue;
  },
  getState() {
    return window.history.state || null;
  },
  go(delta) {
    window.history.go(delta);
  },
  back() {
    window.history.back();
  },
  forward() {
    window.history.forward();
  },
  pushState(data, unused, url) {
    window.history.pushState(data, unused, url);
  },
  replaceState(data, unused, url) {
    window.history.replaceState(data, unused, url);
  },
};

// === Registry ===
export const INTERFACES = {
  "@tairitsu-glue/window": window_exports,
  "@tairitsu-glue/location": location_exports,
  "@tairitsu-glue/history": history_exports,
};
