package tairitsu:plugin-example;

world plugin {
    export greet: func(name: string) -> string;
    export add: func(a: s32, b: s32) -> s32;
    export echo-list: func(items: list<string>) -> list<string>;
}
