/**
 * url glue — implements the `tairitsu-browser:url` WIT import interfaces.
 *
 * Auto-generated from: /mnt/sdb1/tairitsu/packages/browser-glue/../../packages/browser-worlds/wit/generated/url.wit
 * Generated by: scripts/generate_browser_glue.py
 *
 * DO NOT EDIT MANUALLY - regenerate with: just glue-gen
 *
 * All browser objects are represented as opaque bigint handles.
 */

// ---------------------------------------------------------------------------
// Custom type definitions
// ---------------------------------------------------------------------------

/** Type definition for DOMTokenListValue */
export type DOMTokenListValue = string;

/** Type definition for EventHandlerRecord */
export type EventHandlerRecord = any;

/** Type definition for WebGLObject */
export type WebGLObject = any;

/** Type definition for u64 */
export type u64 = bigint;

/** Type definition for RTCDataChannelBinaryType */
export type RTCDataChannelBinaryType = "blob" | "arraybuffer";

/** Type definition for CSSFontFaceDescriptors */
export type CSSFontFaceDescriptors = any;

/** Type definition for CSSFontFeatureValuesMap */
export type CSSFontFeatureValuesMap = any;

/** Type definition for OnBeforeUnloadEventHandlerRecord */
export type OnBeforeUnloadEventHandlerRecord = OnBeforeUnloadEventHandlerNonNull | null;

/** Type definition for OnErrorEventHandlerRecord */
export type OnErrorEventHandlerRecord = OnErrorEventHandlerNonNull | null;

/** Type definition for VoidFunctionRecord */
export type VoidFunctionRecord = VoidFunction;

/** Type definition for EventHandler */
export type EventHandler = (this: any, ev: any) => any;

/** Type definition for GeometryUtils */
export type GeometryUtils = any;

/** Type definition for HyperlinkElementUtils */
export type HyperlinkElementUtils = any;

/** Type definition for PopoverTargetAttributes */
export type PopoverTargetAttributes = any;

/** Type definition for CSSPageDescriptors */
export type CSSPageDescriptors = any;

/** Type definition for CSSMarginRule */
export type CSSMarginRule = CSSRule;

/** Type definition for CSSStyleProperties */
export type CSSStyleProperties = Record<string, string>;

/** Type definition for Origin */
export type Origin = string;

/** Type definition for FetchLaterResult */
export type FetchLaterResult = any;

/** Type definition for NotRestoredReasonDetails */
export type NotRestoredReasonDetails = any;

/** Type definition for NotRestoredReasons */
export type NotRestoredReasons = any;

/** Type definition for DeviceChangeEvent */
export type DeviceChangeEvent = Event;

/** Type definition for ChapterInformation */
export type ChapterInformation = any;

/** Type definition for PerformanceTimingConfidence */
export type PerformanceTimingConfidence = any;

/** Type definition for NotificationEvent */
export type NotificationEvent = Event;

/** Type definition for VisibilityStateEntry */
export type VisibilityStateEntry = PerformanceEntry;

/** Type definition for CommandEvent */
export type CommandEvent = Event;

/** Type definition for CloseWatcher */
export type CloseWatcher = EventTarget;

/** Type definition for CaptureController */
export type CaptureController = any;

/** Type definition for Navigation */
export type Navigation = any;

/** Type definition for NavigationTransition */
export type NavigationTransition = any;

/** Type definition for NavigateEvent */
export type NavigateEvent = Event;

/** Type definition for NavigationPrecommitController */
export type NavigationPrecommitController = any;

/** Type definition for NavigationDestination */
export type NavigationDestination = any;

/** Type definition for NavigationCurrentEntryChangeEvent */
export type NavigationCurrentEntryChangeEvent = Event;

/** Type definition for BatteryManager */
export type BatteryManager = any;

/** Type definition for AudioTrackList */
export type AudioTrackList = any;

/** Type definition for AudioTrack */
export type AudioTrack = any;

/** Type definition for VideoTrackList */
export type VideoTrackList = any;

/** Type definition for VideoTrack */
export type VideoTrack = any;

/** Type definition for WorkerGlobalScope */
export type WorkerGlobalScope = any;

/** Type definition for DedicatedWorkerGlobalScope */
export type DedicatedWorkerGlobalScope = any;

/** Type definition for SharedWorkerGlobalScope */
export type SharedWorkerGlobalScope = any;

/** Type definition for WorkerNavigator */
export type WorkerNavigator = any;

/** Type definition for WorkerLocation */
export type WorkerLocation = any;

/** Type definition for ServiceWorkerGlobalScope */
export type ServiceWorkerGlobalScope = any;

/** Type definition for Client */
export type Client = any;

/** Type definition for WindowClient */
export type WindowClient = any;

/** Type definition for Clients */
export type Clients = any;

/** Type definition for ExtendableEvent */
export type ExtendableEvent = Event;

/** Type definition for InstallEvent */
export type InstallEvent = Event;

/** Type definition for FetchEvent */
export type FetchEvent = Event;

/** Type definition for ExtendableMessageEvent */
export type ExtendableMessageEvent = MessageEvent;

/** Type definition for SpeechRecognition */
export type SpeechRecognition = any;

/** Type definition for SpeechRecognitionErrorEvent */
export type SpeechRecognitionErrorEvent = Event;

/** Type definition for SpeechRecognitionEvent */
export type SpeechRecognitionEvent = Event;

/** Type definition for SpeechGrammar */
export type SpeechGrammar = any;

/** Type definition for SpeechGrammarList */
export type SpeechGrammarList = any;

/** Type definition for SpeechRecognitionPhrase */
export type SpeechRecognitionPhrase = any;

/** Type definition for Module */
export type Module = typeof WebAssembly.Module;

/** Type definition for Instance */
export type Instance = typeof WebAssembly.Instance;

/** Type definition for Memory */
export type Memory = typeof WebAssembly.Memory;

/** Type definition for Table */
export type Table = typeof WebAssembly.Table;

/** Type definition for Global */
export type Global = typeof WebAssembly.Global;

/** Type definition for Exception */
export type Exception = any;

/** Type definition for HTMLString */
export type HTMLString = string;

/** Type definition for MediaText */
export type MediaText = string;

/** Type definition for HTMLHyperlinkHref */
export type HTMLHyperlinkHref = string;

/** Type definition for LocationHref */
export type LocationHref = string;

/** Type definition for URLHref */
export type URLHref = string;


// ---------------------------------------------------------------------------
// WIT interface: url-search-params
// ---------------------------------------------------------------------------

/** Type alias */
export type UrlSearchParamsHandle = bigint;

/** Handle table for URLSearchParams instances */
const _urlSearchParamshandles = new Map<bigint, URLSearchParams>();
let _nextURLSearchParams = 1n;

/** Lookup a URLSearchParams by handle, throwing if not found. */
function lookupURLSearchParams(handle: bigint): URLSearchParams {
  const obj = _urlSearchParamshandles.get(handle);
  if (!obj) {
    throw new Error(`URLSearchParams handle ${handle} not found`);
  }
  return obj!;
}

/** Lookup an optional URLSearchParams by handle. */
function lookupOptionURLSearchParams(handle: bigint | undefined): URLSearchParams | null {
  if (handle === undefined || handle === 0n) {
    return null;
  }
  return _urlSearchParamshandles.get(handle) ?? null;
}
/**
 * `get-size()` operation.
 */
export function getSize(self: bigint): number {
  const obj = lookupURLSearchParams(self);
  return obj.size;
}

/**
 * `append()` operation.
 */
export function append(self: bigint, name: string, value: string): void {
  const obj = lookupURLSearchParams(self);
  obj.append(name as any, value);
}

/**
 * `delete()` operation.
 */
export function _delete(self: bigint, name: string, value: string | undefined): void {
  const obj = lookupURLSearchParams(self);
  obj.delete(name as any, value as any);
}

/**
 * `get()` operation.
 */
export function _get(self: bigint, name: string): string | undefined {
  const obj = lookupURLSearchParams(self);
  return obj.get(name) ?? undefined;
}

/**
 * `get-all()` operation.
 */
export function getAll(self: bigint, name: string): (string)[] {
  const obj = lookupURLSearchParams(self);
  return (obj as any).all;
}

/**
 * `has()` operation.
 */
export function has(self: bigint, name: string, value: string | undefined): boolean {
  const obj = lookupURLSearchParams(self);
  return obj.has(name, value as any);
}

/**
 * `set()` operation.
 */
export function _set(self: bigint, name: string, value: string): void {
  const obj = lookupURLSearchParams(self);
  obj.set(name as any, value as any);
}

/**
 * `sort()` operation.
 */
export function sort(self: bigint): void {
  const obj = lookupURLSearchParams(self);
  obj.sort();
}

// ---------------------------------------------------------------------------
// Exports
// ---------------------------------------------------------------------------

export default {
  getSize,
  append,
  _delete,
  _get,
  getAll,
  has,
  _set,
  sort
};
