use std::time::{Duration, Instant};

use indicatif::{MultiProgress, ProgressBar, ProgressStyle};

use crate::{config::Config, daemon};

fn locale() -> &'static crate::i18n::Translations {
    crate::i18n::translations()
}

fn find_workspace_root(manifest_dir: &std::path::Path) -> crate::Result<std::path::PathBuf> {
    let output = std::process::Command::new("cargo")
        .args([
            "metadata",
            "--no-deps",
            "--locked",
            "--format-version",
            "1",
            "--manifest-path",
            manifest_dir.join("Cargo.toml").to_str().unwrap(),
        ])
        .output()?;

    let metadata: serde_json::Value = serde_json::from_slice(&output.stdout)?;
    let workspace_root = metadata
        .get("workspace_root")
        .and_then(|v| v.as_str())
        .map(std::path::PathBuf::from)
        .ok_or_else(|| {
            crate::TairitsuPackagerError::BuildError("Failed to find workspace root".to_string())
        })?;

    Ok(workspace_root)
}

pub fn resolve_hikari_icons(
    manifest_dir: &std::path::Path,
    offline: bool,
    _verbose: bool,
) -> crate::Result<std::path::PathBuf> {
    let meta = crate::icons::read_consumer_metadata(manifest_dir)?;

    if meta.sets.is_empty() {
        let target_dir = manifest_dir.join("target");
        return crate::icons::hikari_resolver::resolve_stub(&target_dir);
    }

    let cache_root = crate::icons::resolve_cache_root(Some(manifest_dir));

    let cache = crate::icons::IconCache::new(cache_root, offline);
    let result = crate::icons::resolve(&meta, &cache)?;

    if result.sets.is_empty() {
        let target_dir = manifest_dir.join("target");
        return crate::icons::hikari_resolver::resolve_stub(&target_dir);
    }

    let output = manifest_dir
        .join("target")
        .join("tairitsu")
        .join("generated")
        .join("hikari_icons.rs");
    if let Some(parent) = output.parent() {
        std::fs::create_dir_all(parent)?;
    }

    let mut f = std::fs::File::create(&output)?;
    use std::io::Write as _;
    writeln!(f, "// @generated by tairitsu-packager — DO NOT EDIT")?;
    writeln!(f)?;
    writeln!(f, "crate::impl_icons! {{")?;
    for resolved in &result.sets {
        let view_box = resolved.source.view_box;
        let set_ident = resolved.source.name.replace('-', "_").to_uppercase();
        let mut icons: Vec<_> = resolved.icons.iter().collect();
        icons.sort_by(|a, b| a.0.cmp(b.0));
        for (name, data) in &icons {
            let safe = name.replace('-', "_").to_uppercase();
            let safe = if safe
                .as_bytes()
                .first()
                .map(|b| b.is_ascii_digit())
                .unwrap_or(false)
            {
                format!("_{}", safe)
            } else {
                safe
            };
            let const_name = format!("{}_{}", set_ident, safe);
            writeln!(
                f,
                "    {:?} => {{ ident: {}, path: {:?}, view_box: {:?} }},",
                name, const_name, data.path_d, view_box
            )?;
        }
    }
    writeln!(f, "}}")?;

    crate::log_info!(
        "Generated {} → {} icon sets",
        output.display(),
        result.sets.len()
    );
    Ok(output)
}

/// 构建 wasm32-wasip2 格式的 WASM Component，
/// 但使用 WIT Component Model 及 tairitsu browser-glue 实现浏览器互操作。
///
/// 构建步骤：
/// 1. 检查 wasm32-wasip2 toolchain 已安装
/// 2. `cargo build --target wasm32-wasip2 --lib`
/// 3. 将 .wasm 组件拷贝到输出目录
/// 4. 将 browser-glue/dist/ 拷贝到输出目录
/// 5. 生成宿主 HTML（通过 browser-glue 加载组件）
pub fn build_component(
    config: &Config,
    release: bool,
    multi: Option<std::sync::Arc<MultiProgress>>,
    verbose: bool,
) -> crate::Result<()> {
    let build_start = Instant::now();
    let pb_raw = ProgressBar::new(5);
    pb_raw.set_style(
        ProgressStyle::with_template("  {spinner:.bold.cyan}  {prefix:.bold.dim}  {wide_msg}")
            .unwrap()
            .tick_strings(&["⠋", "⠙", "⠹", "⠸", "⠼", "⠴", "⠦", "⠧", "⠇", "⠏"]),
    );
    pb_raw.enable_steady_tick(Duration::from_millis(80));
    // Attach to MultiProgress when in watch mode so pb.println() lines
    // scroll above the persistent status bars instead of below them.
    let pb = match &multi {
        Some(m) => m.add(pb_raw),
        None => pb_raw,
    };

    crate::logfmt::set_active_pb(&pb);

    let build_result: crate::Result<()> = (|| {
        let b = &locale().build;
        // -- 1/5  check target -----------------------------------------------------
        pb.set_prefix("[1/5]");
        pb.set_message(&b.step_check_target);
        let t = Instant::now();
        check_wasip2_target()?;
        crate::log_ok!("{:<20} {:.1?}", b.step_check_target, t.elapsed());
        pb.inc(1);

        // -- 2/5  compile ----------------------------------------------------------
        pb.set_prefix("[2/5]");
        pb.set_message(&b.step_compile);
        let t = Instant::now();

        // Resolve hikari-icons before compiling
        let icons_rs = resolve_hikari_icons(&config.manifest_dir, false, verbose).ok();

        let wasm_path =
            build_wasm_component(config, release, pb.clone(), verbose, icons_rs.as_deref())?;
        crate::log_ok!("{:<20} {:.1?}", b.step_compile, t.elapsed());
        pb.inc(1);

        // -- 3/5  bundle assets ----------------------------------------------------
        pb.set_prefix("[3/5]");
        pb.set_message(&b.step_bundle);
        let t = Instant::now();

        // Resolve output_dir relative to manifest_dir
        let output_dir = if config.build.output_dir.is_relative() {
            config.manifest_dir.join(&config.build.output_dir)
        } else {
            config.build.output_dir.clone()
        };

        let dest_wasm = output_dir.join(format!("{}.wasm", config.package.name.replace('-', "_")));

        crate::log_info!("{}", b.creating_output_dir);
        std::fs::create_dir_all(&output_dir)?;

        crate::log_info!("{}", b.copying_wasm);
        std::fs::copy(&wasm_path, &dest_wasm)?;

        crate::log_info!("{}", b.copying_glue);
        copy_browser_glue_with_output_dir(config, &output_dir, &pb)?;

        crate::log_info!("{}", b.copying_public);
        copy_static_public_assets_with_output_dir(config, &output_dir)?;

        write_browser_glue_bundle(config, &output_dir)?;

        crate::log_info!("{}", b.compiling_scss);
        compile_project_scss_with_output_dir(config, &output_dir)?;
        crate::log_ok!("{:<20} {:.1?}", b.step_bundle, t.elapsed());
        pb.inc(1);

        // -- 4/5  component wrapper ------------------------------------------------
        pb.set_prefix("[4/5]");
        pb.set_message(&b.step_wrapper);
        let t = Instant::now();
        prepare_component_wrapper_fallback(config, &dest_wasm, &output_dir, &pb)?;
        crate::log_ok!("{:<20} {:.1?}", b.step_wrapper, t.elapsed());
        pb.inc(1);

        // -- 5/5  HTML -------------------------------------------------------------
        pb.set_prefix("[5/5]");
        pb.set_message(&b.step_generate_html);
        let t = Instant::now();
        generate_component_html_with_output_dir(config, &output_dir)?;
        crate::log_ok!("{:<20} {:.1?}", b.step_generate_html, t.elapsed());
        pb.inc(1);

        Ok(())
    })();

    pb.finish_and_clear();
    crate::logfmt::clear_active_pb();

    build_result?;

    let elapsed = build_start.elapsed();
    crate::log_ok!(
        "{}",
        crate::fmt_tmpl!(locale().build.build_complete, elapsed => format!("{:.1?}", elapsed))
    );

    let output_dir = if config.build.output_dir.is_relative() {
        config.manifest_dir.join(&config.build.output_dir)
    } else {
        config.build.output_dir.clone()
    };
    let wasm_file = output_dir.join(format!("{}.wasm", config.package.name.replace('-', "_")));
    if let Ok(meta) = std::fs::metadata(&wasm_file) {
        let size_bytes = meta.len();
        let size_str = if size_bytes >= 1_048_576 {
            format!("{:.1} MB", size_bytes as f64 / 1_048_576.0)
        } else {
            format!("{:.1} KB", size_bytes as f64 / 1024.0)
        };
        crate::log_info!(
            "{}",
            crate::fmt_tmpl!(locale().build.package_info,
                name => wasm_file.file_name().unwrap_or_default().to_string_lossy(),
                size => size_str
            )
        );
    }

    // Log successful build if in daemon mode
    if daemon::is_daemon() {
        let _ = daemon::append_build_log("component", true, None);
    }

    Ok(())
}

fn check_wasip2_target() -> crate::Result<()> {
    let output = std::process::Command::new("rustup")
        .args(["target", "list", "--installed"])
        .output()?;

    let targets = String::from_utf8_lossy(&output.stdout);
    if !targets.contains("wasm32-wasip2") {
        return Err(crate::TairitsuPackagerError::BuildError(
            locale().build.target_not_installed.to_string(),
        ));
    }

    Ok(())
}

fn build_wasm_component(
    config: &Config,
    release: bool,
    pb: ProgressBar,
    verbose: bool,
    icons_rs: Option<&std::path::Path>,
) -> crate::Result<std::path::PathBuf> {
    use std::io::BufRead;
    use std::process::Stdio;

    let pkg_name = &config.package.name;

    let mut cmd = std::process::Command::new("cargo");
    cmd.args([
        "build",
        "--locked",
        "--target",
        "wasm32-wasip2",
        "--lib",
        "--package",
        pkg_name,
        "--manifest-path",
        config.manifest_dir.join("Cargo.toml").to_str().unwrap(),
        "--message-format=json-diagnostic-rendered-ansi",
    ]);
    if release {
        cmd.arg("--release");
    } else {
        cmd.args(["--profile", "dev-wasm"]);
    }

    if let Some(path) = icons_rs {
        cmd.env("TAIRITSU_ICONS_RS", path);
    }

    cmd.stdout(Stdio::piped());
    cmd.stderr(Stdio::piped());

    let mut child = cmd.spawn()?;

    let stdout = child.stdout.take().expect("stdout should be piped");
    let stderr = child.stderr.take().expect("stderr should be piped");

    let pb_clone = pb.clone();

    fn extract_crate_name(package_id: &str) -> &str {
        if let Some(after_hash) = package_id.split('#').nth(1) {
            if let Some(name) = after_hash.split('@').next() {
                return name;
            }
        }
        package_id
    }

    let diagnostics = std::sync::Arc::new(std::sync::Mutex::new(String::new()));
    let diag_clone = diagnostics.clone();

    #[derive(Clone)]
    struct DiagEntry {
        level: String,
        message: String,
        location: Option<String>,
    }
    let diag_entries: std::sync::Arc<std::sync::Mutex<Vec<DiagEntry>>> =
        std::sync::Arc::new(std::sync::Mutex::new(Vec::new()));
    let entries_clone = diag_entries.clone();

    let stderr_capture = std::sync::Arc::new(std::sync::Mutex::new(String::new()));
    let stderr_clone = stderr_capture.clone();
    let stderr_handle = std::thread::spawn(move || {
        use std::io::BufRead;
        let mut buf = String::new();
        for line in std::io::BufReader::new(stderr)
            .lines()
            .map_while(Result::ok)
        {
            buf.push_str(&line);
            buf.push('\n');
        }
        if let Ok(mut s) = stderr_clone.lock() {
            *s = buf;
        }
    });

    let handle = std::thread::spawn(move || {
        for line in std::io::BufReader::new(stdout).lines() {
            let Ok(line) = line else { continue };
            if let Ok(msg) = serde_json::from_str::<serde_json::Value>(&line) {
                if let Some(reason) = msg.get("reason").and_then(|r| r.as_str()) {
                    match reason {
                        "compiler-artifact" => {
                            if let Some(package_id) = msg.get("package_id").and_then(|p| p.as_str())
                            {
                                let crate_name = extract_crate_name(package_id);
                                if let Some(target) = msg.get("target") {
                                    if target.get("kind").and_then(|k| k.as_array()).is_some_and(
                                        |k| k.iter().any(|kind| kind.as_str() == Some("lib")),
                                    ) {
                                        pb_clone.set_message(format!("compile {}", crate_name));
                                    }
                                }
                            }
                        }
                        "compiler-message" => {
                            if let Some(rendered) = msg
                                .get("message")
                                .and_then(|m| m.get("rendered"))
                                .and_then(|r| r.as_str())
                            {
                                if verbose {
                                    pb_clone.println(rendered);
                                }
                                if let Ok(mut d) = diag_clone.lock() {
                                    d.push_str(rendered);
                                    d.push('\n');
                                }
                                if !verbose {
                                    let level = msg
                                        .get("message")
                                        .and_then(|m| m.get("level"))
                                        .and_then(|l| l.as_str())
                                        .unwrap_or("")
                                        .to_string();
                                    let diag_msg = msg
                                        .get("message")
                                        .and_then(|m| m.get("message"))
                                        .and_then(|m| m.as_str())
                                        .unwrap_or("")
                                        .to_string();
                                    let location = msg.get("message").and_then(|m| {
                                        m.get("spans")
                                            .and_then(|s| s.as_array())
                                            .and_then(|a| a.first())
                                            .and_then(|span| {
                                                let file = span
                                                    .get("file_name")
                                                    .and_then(|f| f.as_str())
                                                    .unwrap_or("");
                                                let line = span
                                                    .get("line_start")
                                                    .and_then(|l| l.as_u64())
                                                    .unwrap_or(0);
                                                if file.is_empty() {
                                                    return None;
                                                }
                                                let name = std::path::Path::new(file)
                                                    .file_name()
                                                    .and_then(|n| n.to_str())
                                                    .unwrap_or(file);
                                                Some(if line > 0 {
                                                    format!("{}:{}", name, line)
                                                } else {
                                                    name.to_string()
                                                })
                                            })
                                    });
                                    if matches!(level.as_str(), "warning" | "error") {
                                        if let Ok(mut entries) = entries_clone.lock() {
                                            entries.push(DiagEntry {
                                                level,
                                                message: diag_msg,
                                                location,
                                            });
                                        }
                                    }
                                }
                            }
                        }
                        "build-script-executed" => {
                            if let Some(package_id) = msg.get("package_id").and_then(|p| p.as_str())
                            {
                                let crate_name = extract_crate_name(package_id);
                                pb_clone.set_message(format!("build script {}", crate_name));
                            }
                        }
                        "build-finished" => {}
                        _ => {}
                    }
                }
            }
        }
    });

    let status = child.wait()?;
    handle.join().ok();
    stderr_handle.join().ok();

    if !status.success() {
        if !verbose {
            let entries = diag_entries.lock().map(|e| e.clone()).unwrap_or_default();
            let n_err = entries.iter().filter(|e| e.level == "error").count();
            let n_warn = entries.iter().filter(|e| e.level == "warning").count();
            for entry in &entries {
                match &entry.location {
                    Some(loc) => {
                        crate::log_progress!("{}: {} — {}", entry.level, entry.message, loc)
                    }
                    None => crate::log_progress!("{}: {}", entry.level, entry.message),
                }
            }
            let mut parts = Vec::new();
            if n_err > 0 {
                parts.push(
                    crate::fmt_tmpl!(locale().build.diagnostic_count, n => n_err.to_string()),
                );
            }
            if n_warn > 0 {
                parts.push(crate::fmt_tmpl!(locale().build.warning_count, n => n_warn.to_string()));
            }
            if !parts.is_empty() {
                crate::log_progress!(
                    "{}",
                    crate::fmt_tmpl!(locale().build.compilation_failed, details => parts.join(", "))
                );
            }
        }
        let diag_text = diagnostics
            .lock()
            .map(|d| d.trim().to_string())
            .unwrap_or_default();
        let stderr_text = stderr_capture
            .lock()
            .map(|s| s.trim().to_string())
            .unwrap_or_default();
        let error_detail = if !diag_text.is_empty() {
            diag_text
        } else if !stderr_text.is_empty() {
            stderr_text
        } else {
            "cargo build --target wasm32-wasip2 failed".to_string()
        };
        if daemon::is_daemon() {
            let _ = daemon::append_build_log("component", false, Some(&error_detail));
        }
        return Err(crate::TairitsuPackagerError::BuildError(error_detail));
    }

    if !verbose {
        let entries = diag_entries.lock().map(|e| e.clone()).unwrap_or_default();
        let n_warn = entries.iter().filter(|e| e.level == "warning").count();
        let n_err = entries.iter().filter(|e| e.level == "error").count();
        if n_warn > 0 || n_err > 0 {
            for entry in &entries {
                match &entry.location {
                    Some(loc) => {
                        crate::log_progress!("{}: {} — {}", entry.level, entry.message, loc)
                    }
                    None => crate::log_progress!("{}: {}", entry.level, entry.message),
                }
            }
            let mut parts = Vec::new();
            if n_err > 0 {
                parts.push(
                    crate::fmt_tmpl!(locale().build.diagnostic_count, n => n_err.to_string()),
                );
            }
            if n_warn > 0 {
                parts.push(crate::fmt_tmpl!(locale().build.warning_count, n => n_warn.to_string()));
            }
            crate::log_progress!(
                "{}",
                crate::fmt_tmpl!(locale().build.compiled_with, details => parts.join(", "))
            );
        }
    }

    let workspace_root = find_workspace_root(&config.manifest_dir)?;
    let profile = if release { "release" } else { "dev-wasm" };
    let wasm_path = workspace_root
        .join("target")
        .join("wasm32-wasip2")
        .join(profile)
        .join(format!("{}.wasm", pkg_name.replace('-', "_")));

    if !wasm_path.exists() {
        return Err(crate::TairitsuPackagerError::BuildError(
            crate::fmt_tmpl!(locale().build.component_not_found, path => wasm_path.display().to_string()),
        ));
    }

    Ok(wasm_path)
}

/// Resolve the browser-glue runtime bundle (`dist/runtime.js`).
///
/// Search order:
/// 1. `TAIRITSU_RUNTIME_BUNDLE` environment variable (absolute or relative path)
/// 2. Monorepo-relative paths (for in-tree development)
/// 3. [`DEP_TAIRITSU_BROWSER_WORLDS_WIT_DIR`] auto-discovery (for crates.io users)
/// 4. `node_modules/` paths (for npm-installed `tairitsu-browser-glue`)
fn resolve_glue_runtime_bundle(manifest_dir: &std::path::Path) -> crate::Result<String> {
    if let Ok(env_path) = std::env::var("TAIRITSU_RUNTIME_BUNDLE") {
        let path = std::path::Path::new(&env_path);
        if path.exists() {
            return std::fs::read_to_string(path).map_err(|e| {
                crate::TairitsuPackagerError::BuildError(format!(
                    "Failed to read browser-glue runtime bundle from env override {}: {}",
                    path.display(),
                    e
                ))
            });
        }
        eprintln!(
            "[tairitsu] Warning: TAIRITSU_RUNTIME_BUNDLE={} does not exist, falling back to default search",
            path.display()
        );
    }

    let candidates: &[&str] = &[
        "../../../tairitsu/packages/browser-glue/dist/runtime.js",
        "../../packages/browser-glue/dist/runtime.js",
        "../packages/browser-glue/dist/runtime.js",
        "packages/browser-glue/dist/runtime.js",
        "../browser-glue/dist/runtime.js",
    ];
    for candidate in candidates {
        let path = manifest_dir.join(candidate);
        if path.exists() {
            return std::fs::read_to_string(&path).map_err(|e| {
                crate::TairitsuPackagerError::BuildError(format!(
                    "Failed to read browser-glue runtime bundle {}: {}",
                    path.display(),
                    e
                ))
            });
        }
    }

    if let Ok(bw_dir) = std::env::var("DEP_TAIRITSU_BROWSER_WORLDS_WIT_DIR") {
        let glue_path = std::path::Path::new(&bw_dir)
            .parent()
            .and_then(|p| p.parent())
            .map(|p| p.join("browser-glue/dist/runtime.js"));
        if let Some(glue_path) = glue_path {
            if glue_path.exists() {
                return std::fs::read_to_string(&glue_path).map_err(|e| {
                    crate::TairitsuPackagerError::BuildError(format!(
                        "Failed to read browser-glue runtime bundle {}: {}",
                        glue_path.display(),
                        e
                    ))
                });
            }
        }
    }

    let node_modules_candidates: &[&str] = &[
        "node_modules/tairitsu-browser-glue/dist/runtime.js",
        "node_modules/@tairitsu/browser-glue/dist/runtime.js",
        "../node_modules/tairitsu-browser-glue/dist/runtime.js",
    ];
    for candidate in node_modules_candidates {
        let path = manifest_dir.join(candidate);
        if path.exists() {
            return std::fs::read_to_string(&path).map_err(|e| {
                crate::TairitsuPackagerError::BuildError(format!(
                    "Failed to read browser-glue runtime bundle {}: {}",
                    path.display(),
                    e
                ))
            });
        }
    }

    Err(crate::TairitsuPackagerError::BuildError(
        "browser-glue runtime bundle (dist/runtime.js) not found. \
         Set TAIRITSU_RUNTIME_BUNDLE env var to the path of runtime.js, \
         or ensure browser-glue is built (run `npm run build` in packages/browser-glue)."
            .to_string(),
    ))
}

fn write_browser_glue_bundle(config: &Config, output_dir: &std::path::Path) -> crate::Result<()> {
    let glue_path = config.build.browser_glue_path.trim_start_matches('/');
    let bundle_dest = output_dir.join(glue_path);

    if let Some(parent) = bundle_dest.parent() {
        std::fs::create_dir_all(parent)?;
    }

    let bundle = resolve_glue_runtime_bundle(&config.manifest_dir)?;
    std::fs::write(&bundle_dest, &bundle)?;

    Ok(())
}

fn flatten_barrel_exports(barrel_path: &std::path::Path) -> crate::Result<()> {
    let content = std::fs::read_to_string(barrel_path).map_err(|e| {
        crate::TairitsuPackagerError::BuildError(format!(
            "Failed to read barrel {}: {}",
            barrel_path.display(),
            e
        ))
    })?;

    let mut needs_flatten = false;
    for line in content.lines() {
        let trimmed = line.trim();
        if trimmed.starts_with("export * as ")
            || (trimmed.contains("export * from") && trimmed.contains("glue/index"))
        {
            needs_flatten = true;
            break;
        }
    }

    if !needs_flatten {
        return Ok(());
    }

    let glue_dir = barrel_path.parent().map(|p| p.join("glue"));
    let Some(glue_dir) = glue_dir else {
        return Ok(());
    };

    let sym_map = build_symbol_module_map(&glue_dir);

    let mut module_syms: std::collections::BTreeMap<String, Vec<String>> =
        std::collections::BTreeMap::new();
    for (sym, mod_name) in &sym_map {
        module_syms
            .entry(mod_name.clone())
            .or_default()
            .push(sym.clone());
    }

    let mut lines = vec![
        "/**".to_string(),
        " * @tairitsu/browser-glue — flattened barrel (auto-generated)".to_string(),
        " * Combines exports from all glue submodules into named re-exports.".to_string(),
        " */".to_string(),
    ];
    for (mod_name, syms) in &module_syms {
        if syms.is_empty() {
            continue;
        }
        lines.push(format!(
            "export {{ {} }} from \"./glue/{}.js\";",
            syms.join(", "),
            mod_name
        ));
    }

    std::fs::write(barrel_path, lines.join("\n")).map_err(|e| {
        crate::TairitsuPackagerError::BuildError(format!(
            "Failed to write flattened barrel {}: {}",
            barrel_path.display(),
            e
        ))
    })?;

    crate::log_info!(
        "{}",
        crate::fmt_tmpl!(
            locale().build.flattened_barrel,
            path => barrel_path.display().to_string(),
            modules => module_syms.len().to_string(),
            symbols => sym_map.len().to_string()
        )
    );
    Ok(())
}

fn build_symbol_module_map(
    glue_dir: &std::path::Path,
) -> std::collections::HashMap<String, String> {
    let mut map: std::collections::HashMap<String, (String, bool)> =
        std::collections::HashMap::new();
    let Ok(entries) = std::fs::read_dir(glue_dir) else {
        return std::collections::HashMap::new();
    };
    for entry in entries.flatten() {
        let path = entry.path();
        if path.extension().is_none_or(|e| e != "js") {
            continue;
        }
        let Some(module_name) = path.file_stem().and_then(|s| s.to_str()) else {
            continue;
        };
        let Ok(content) = std::fs::read_to_string(&path) else {
            continue;
        };
        for line in content.lines() {
            let trimmed = line.trim();
            let export_start = trimmed
                .find("export ")
                .or_else(|| trimmed.find("export\t"))
                .unwrap_or(usize::MAX);
            if export_start == usize::MAX {
                continue;
            }
            let after_export = &trimmed[export_start + 7..];
            let prefix = if after_export.starts_with("function ") {
                "function "
            } else if after_export.starts_with("const ") {
                "const "
            } else if after_export.starts_with("let ") {
                "let "
            } else if after_export.starts_with("var ") {
                "var "
            } else if after_export.starts_with("async function ") {
                "async function "
            } else {
                continue;
            };
            if let Some(rest) = after_export.strip_prefix(prefix) {
                if let Some(sym_full) = rest.split_whitespace().next() {
                    let sym_name = sym_full
                        .split('(')
                        .next()
                        .unwrap_or(sym_full)
                        .trim()
                        .to_string();
                    if !sym_name.is_empty() {
                        let has_self = rest.contains("(self)") || rest.contains("(self,");
                        match map.get(&sym_name) {
                            Some((_other_mod, other_has_self)) => {
                                if *other_has_self && !has_self {
                                    map.insert(sym_name, (module_name.to_string(), has_self));
                                }
                            }
                            None => {
                                map.insert(sym_name, (module_name.to_string(), has_self));
                            }
                        }
                    }
                }
            }
        }
    }
    map.into_iter().map(|(k, (v, _))| (k, v)).collect()
}

fn copy_browser_glue_with_output_dir(
    config: &Config,
    output_dir: &std::path::Path,
    _pb: &ProgressBar,
) -> crate::Result<()> {
    // Also copy the full browser-glue dist so that jco-generated wrapper
    // ES module imports (e.g. `import { setProperty } from '@tairitsu/browser-glue'`)
    // can resolve. The dist contains index.js (main barrel) + glue/*.js submodules.
    // Try tairitsu workspace first (where browser-glue is built), then local.
    let glue_dist_candidates: &[&str] = &[
        "../../../tairitsu/packages/browser-glue/dist", // hikari/examples/website → tairitsu
        "../../packages/browser-glue/dist",             // tairitsu/examples/website → tairitsu
        "../packages/browser-glue/dist",                // any project examples/* → workspace root
        "packages/browser-glue/dist",                   // workspace root itself
    ];
    let mut copied = false;
    for candidate in glue_dist_candidates {
        let glue_dist = config.manifest_dir.join(candidate);
        if glue_dist.exists() {
            let dest_glue = output_dir.join("browser-glue");
            std::fs::create_dir_all(&dest_glue)?;
            for entry in walkdir::WalkDir::new(&glue_dist) {
                let entry = entry.map_err(|e| {
                    crate::TairitsuPackagerError::BuildError(format!(
                        "Failed to walk browser-glue dist: {}",
                        e
                    ))
                })?;
                let path = entry.path();
                let rel = path.strip_prefix(&glue_dist).map_err(|_| {
                    crate::TairitsuPackagerError::BuildError(
                        "Failed to compute relative path".to_string(),
                    )
                })?;
                let dest = dest_glue.join(rel);
                if path.is_dir() {
                    std::fs::create_dir_all(&dest)?;
                } else {
                    std::fs::copy(path, &dest)?;
                }
            }
            copied = true;

            let top_barrel = dest_glue.join("index.js");
            if top_barrel.exists() {
                if let Err(e) = flatten_barrel_exports(&top_barrel) {
                    crate::log_warn!("Failed to flatten top-level barrel: {}", e);
                }
            }
            break;
        }
    }
    if !copied {
        crate::log_warn!("browser-glue dist not found — jco wrapper imports may fail at runtime");
    }

    Ok(())
}

fn copy_static_public_assets_with_output_dir(
    config: &Config,
    output_dir: &std::path::Path,
) -> crate::Result<()> {
    let public_dir = config.manifest_dir.join("public");

    if public_dir.exists() {
        copy_dir_contents(&public_dir, output_dir)?;
    }

    for extra in &config.assets.extra_public_dirs {
        let extra_path = config.manifest_dir.join(extra);
        if extra_path.exists() {
            crate::log_info!(
                "{}",
                crate::fmt_tmpl!(locale().build.copying_extra_public, path => extra_path.display().to_string())
            );
            copy_dir_contents(&extra_path, output_dir)?;
        } else {
            crate::log_warn!(
                "{}",
                crate::fmt_tmpl!(locale().build.extra_public_not_found, path => extra_path.display().to_string())
            );
        }
    }

    Ok(())
}

fn copy_dir_contents(src_dir: &std::path::Path, output_dir: &std::path::Path) -> crate::Result<()> {
    for entry in walkdir::WalkDir::new(src_dir) {
        let entry = entry.map_err(|e| {
            crate::TairitsuPackagerError::BuildError(format!("Failed to walk directory: {}", e))
        })?;
        let path = entry.path();
        if path.is_dir() {
            continue;
        }
        let relative = path.strip_prefix(src_dir).map_err(|e| {
            crate::TairitsuPackagerError::BuildError(format!(
                "Failed to compute relative path: {}",
                e
            ))
        })?;
        let dest = output_dir.join(relative);
        if let Some(parent) = dest.parent() {
            std::fs::create_dir_all(parent)?;
        }
        std::fs::copy(path, dest)?;
    }
    Ok(())
}

fn compile_project_scss_with_output_dir(
    config: &Config,
    output_dir: &std::path::Path,
) -> crate::Result<()> {
    let project_root = &config.manifest_dir;

    crate::log_info!(
        "{}",
        crate::fmt_tmpl!(locale().build.scss_project_root, path => project_root.display().to_string())
    );

    // Use new SCSS configuration system
    let results = crate::styles::compile_scss_with_config(&config.scss, project_root, output_dir)
        .map_err(|e| {
        crate::TairitsuPackagerError::BuildError(format!("Failed to compile SCSS: {}", e))
    })?;

    // Log compiled files
    for result in results {
        crate::log_info!(
            "{}",
            crate::fmt_tmpl!(locale().build.compiled_scss, path => result.output_path.display().to_string())
        );
    }

    Ok(())
}

fn prepare_component_wrapper_fallback(
    config: &Config,
    component_wasm_path: &std::path::Path,
    output_dir: &std::path::Path,
    pb: &ProgressBar,
) -> crate::Result<()> {
    write_component_wrapper_loader(config, component_wasm_path, output_dir)?;

    if !try_generate_component_wrapper(config, component_wasm_path, output_dir, pb)? {
        return Err(crate::TairitsuPackagerError::BuildError(
            "Component wrapper transpile failed. \
             Install jco: npm install -g @bytecodealliance/jco\n\
             The dev server requires the jco-transpiled wrapper to serve WASM components."
                .to_string(),
        ));
    }

    let local_shim_available = bundle_local_wasi_shim(output_dir, pb)?;
    rewrite_wrapper_imports(output_dir, local_shim_available)?;

    Ok(())
}

const WASI_SHIM_MODULES: &[&str] = &["io", "cli", "random", "clocks", "filesystem", "sockets"];

fn bundle_local_wasi_shim(output_dir: &std::path::Path, pb: &ProgressBar) -> crate::Result<bool> {
    let shim_dir = output_dir.join("wasi-shim");
    if shim_dir.exists() {
        let marker = shim_dir.join(".tairitsu-bundled");
        if marker.exists() {
            return Ok(true);
        }
    }

    let node = if cfg!(windows) { "node.exe" } else { "node" };
    let script = include_str!("bundle-wasi-shim.js");

    let temp_script = output_dir.join("_wasi_shim_bundle.js");
    std::fs::write(&temp_script, script)?;

    let result = std::process::Command::new(node)
        .arg(&temp_script)
        .arg(shim_dir.to_str().unwrap_or("."))
        .output();

    let _ = std::fs::remove_file(&temp_script);

    match result {
        Ok(output) if output.status.success() => {
            let count = WASI_SHIM_MODULES.len();
            pb.println(format!(
                "✓  Bundled {} WASI preview2-shim modules locally",
                count
            ));
            Ok(true)
        }
        Ok(_) => {
            pb.println(
                "⚠  Could not bundle WASI shim locally (npm unavailable?). Falling back to CDN.",
            );
            Ok(false)
        }
        Err(_) => {
            pb.println(
                "⚠  Could not bundle WASI shim locally (node not found?). Falling back to CDN.",
            );
            Ok(false)
        }
    }
}

fn rewrite_wrapper_imports(
    output_dir: &std::path::Path,
    local_shim_available: bool,
) -> crate::Result<()> {
    let wrapper_dir = output_dir.join("component-wrapper");
    if !wrapper_dir.exists() {
        return Ok(());
    }

    let local_prefix = if local_shim_available {
        "'/wasi-shim/"
    } else {
        "'https://esm.sh/@bytecodealliance/preview2-shim/"
    };
    let local_prefix_dq = if local_shim_available {
        "\"/wasi-shim/"
    } else {
        "\"https://esm.sh/@bytecodealliance/preview2-shim/"
    };

    for entry in std::fs::read_dir(&wrapper_dir)? {
        let entry = entry?;
        let path = entry.path();
        if !path.is_file() {
            continue;
        }
        if path.extension().and_then(|s| s.to_str()) != Some("js") {
            continue;
        }

        let content = std::fs::read_to_string(&path)?;
        let mut patched = content
            .replace("'@bytecodealliance/preview2-shim/", local_prefix)
            .replace("\"@bytecodealliance/preview2-shim/", local_prefix_dq);

        if local_shim_available {
            patched = patched
                .replace("'/wasi-shim/io'", "'/wasi-shim/io.js'")
                .replace("'/wasi-shim/cli'", "'/wasi-shim/cli.js'")
                .replace("'/wasi-shim/random'", "'/wasi-shim/random.js'")
                .replace("'/wasi-shim/clocks'", "'/wasi-shim/clocks.js'")
                .replace("'/wasi-shim/filesystem'", "'/wasi-shim/filesystem.js'")
                .replace("'/wasi-shim/sockets'", "'/wasi-shim/sockets.js'")
                .replace("\"/wasi-shim/io\"", "\"/wasi-shim/io.js\"")
                .replace("\"/wasi-shim/cli\"", "\"/wasi-shim/cli.js\"")
                .replace("\"/wasi-shim/random\"", "\"/wasi-shim/random.js\"")
                .replace("\"/wasi-shim/clocks\"", "\"/wasi-shim/clocks.js\"")
                .replace("\"/wasi-shim/filesystem\"", "\"/wasi-shim/filesystem.js\"")
                .replace("\"/wasi-shim/sockets\"", "\"/wasi-shim/sockets.js\"");
        }

        if patched != content {
            std::fs::write(&path, patched)?;
        }
    }

    Ok(())
}

fn write_component_wrapper_loader(
    _config: &Config,
    component_wasm_path: &std::path::Path,
    output_dir: &std::path::Path,
) -> crate::Result<()> {
    let wasm_stem = component_wasm_path
        .file_stem()
        .and_then(|s| s.to_str())
        .ok_or_else(|| {
            crate::TairitsuPackagerError::BuildError(
                "Failed to derive wasm file stem for wrapper loader".to_string(),
            )
        })?;

    let loader = include_str!(concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/src/wasm/component-wrapper-loader.template.js"
    ))
    .replace("__WASM_STEM__", wasm_stem);

    let loader_path = output_dir.join("component-wrapper-loader.js");
    std::fs::write(loader_path, loader)?;
    Ok(())
}

fn try_generate_component_wrapper(
    _config: &Config,
    component_wasm_path: &std::path::Path,
    output_dir: &std::path::Path,
    pb: &ProgressBar,
) -> crate::Result<bool> {
    let wrapper_dir = output_dir.join("component-wrapper");
    std::fs::create_dir_all(&wrapper_dir)?;

    let wasm_path_for_cmd = std::fs::canonicalize(component_wasm_path)
        .unwrap_or_else(|_| component_wasm_path.to_path_buf());
    let wrapper_dir_for_cmd = std::fs::canonicalize(&wrapper_dir).unwrap_or(wrapper_dir.clone());
    let wasm_path_hint = wasm_path_for_cmd
        .display()
        .to_string()
        .trim_start_matches(r"\\?\")
        .to_string();
    let wrapper_dir_hint = wrapper_dir_for_cmd
        .display()
        .to_string()
        .trim_start_matches(r"\\?\")
        .to_string();

    let wasm_stem = component_wasm_path
        .file_stem()
        .and_then(|s| s.to_str())
        .ok_or_else(|| {
            crate::TairitsuPackagerError::BuildError(
                "Failed to derive wasm file stem for wrapper detection".to_string(),
            )
        })?;

    let wrapper_main = if wrapper_dir.join("index.js").exists() {
        Some(wrapper_dir.join("index.js"))
    } else {
        let named = wrapper_dir.join(format!("{}.js", wasm_stem));
        if named.exists() {
            Some(named)
        } else {
            None
        }
    };

    if let Some(main) = wrapper_main {
        let wrapper_mtime = std::fs::metadata(&main)?.modified().ok();
        let wasm_mtime = std::fs::metadata(component_wasm_path)?.modified().ok();
        if let (Some(w), Some(c)) = (wrapper_mtime, wasm_mtime) {
            if w >= c {
                return Ok(true);
            }
        }
    }

    #[allow(unused_mut)]
    let mut attempts: Vec<(&str, Vec<String>)> = vec![
        (
            "jco",
            vec![
                "transpile".to_string(),
                wasm_path_for_cmd.display().to_string(),
                "-o".to_string(),
                wrapper_dir_for_cmd.display().to_string(),
            ],
        ),
        (
            "npx",
            vec![
                "--yes".to_string(),
                "@bytecodealliance/jco".to_string(),
                "transpile".to_string(),
                wasm_path_for_cmd.display().to_string(),
                "-o".to_string(),
                wrapper_dir_for_cmd.display().to_string(),
            ],
        ),
    ];

    #[cfg(windows)]
    {
        attempts.push((
            "npx.cmd",
            vec![
                "--yes".to_string(),
                "@bytecodealliance/jco".to_string(),
                "transpile".to_string(),
                wasm_path_for_cmd.display().to_string(),
                "-o".to_string(),
                wrapper_dir_for_cmd.display().to_string(),
            ],
        ));
    }

    let mut missing_commands = Vec::new();

    let re_import =
        regex::Regex::new(r"(?:import\s*\{([^}]+)\}\s*from\s*'@tairitsu-glue/([^']*)'\s*;?)")
            .unwrap();
    let re_import_d =
        regex::Regex::new(r#"(?:import\s*\{([^}]+)\}\s*from\s*"@tairitsu-glue/([^"]*)"\s*;?)"#)
            .unwrap();

    for (bin, args) in attempts {
        let command_preview = format!("{} {}", bin, args.join(" "));
        match std::process::Command::new(bin).args(&args).output() {
            Ok(output) if output.status.success() => {
                let has_index = wrapper_dir.join("index.js").exists();
                let has_named = wrapper_dir.join(format!("{}.js", wasm_stem)).exists();
                if has_index || has_named {
                    // Post-process the generated JS to replace tairitsu-browser:full/ imports
                    // with @tairitsu-glue/ imports which are valid bare module specifiers
                    let js_files = vec![
                        wrapper_dir.join("index.js"),
                        wrapper_dir.join(format!("{}.js", wasm_stem)),
                    ];
                    for js_file in js_files {
                        if js_file.exists() {
                            if let Ok(mut content) = std::fs::read_to_string(&js_file) {
                                let original = content.clone();
                                content = content.replace(
                                    "from 'tairitsu-browser:full/",
                                    "from '@tairitsu-glue/",
                                );
                                content = content.replace(
                                    "from \"tairitsu-browser:full/",
                                    "from \"@tairitsu-glue/",
                                );

                                let _import_map_interfaces: std::collections::HashSet<&str> =
                                    [].into_iter().collect();

                                content = re_import
                                    .replace_all(&content, |caps: &regex::Captures| {
                                        let _m0 = caps.get(0).map(|m| m.as_str()).unwrap_or("");
                                        let m1 = caps.get(1).map(|m| m.as_str()).unwrap_or("");
                                        let m2 = caps.get(2).map(|m| m.as_str()).unwrap_or("");
                                        if m1.is_empty() {
                                            return String::new();
                                        }
                                        let _iface_name = m2.split('/').next().unwrap_or("");

                                        // Split symbols: import-map-available vs needs-glue-fallback
                                        let mut map_syms = Vec::new();
                                        for sym in m1.trim().split(',') {
                                            let s = sym.trim();
                                            if s.is_empty() {
                                                continue;
                                            }
                                            // All interfaces now provided by __tairitsu_glue__.js import map
                                            map_syms.push(s.to_string());
                                        }

                                        let mut parts = Vec::new();
                                        if !map_syms.is_empty() {
                                            parts.push(format!(
                                                "import {{ {} }} from '@tairitsu-glue/{}';",
                                                map_syms.join(", "),
                                                m2
                                            ));
                                        }
                                        // Resolve each symbol to its own module
                                        parts.join("\n  ")
                                    })
                                    .to_string();
                                content = re_import_d
                                    .replace_all(&content, |caps: &regex::Captures| {
                                        let _m0 = caps.get(0).map(|m| m.as_str()).unwrap_or("");
                                        let m1 = caps.get(1).map(|m| m.as_str()).unwrap_or("");
                                        let m2 = caps.get(2).map(|m| m.as_str()).unwrap_or("");
                                        if m1.is_empty() {
                                            return String::new();
                                        }
                                        let _iface_name = m2.split('/').next().unwrap_or("");

                                        let mut map_syms = Vec::new();
                                        for sym in m1.trim().split(',') {
                                            let s = sym.trim();
                                            if s.is_empty() {
                                                continue;
                                            }
                                            map_syms.push(s.to_string());
                                        }

                                        let mut parts = Vec::new();
                                        if !map_syms.is_empty() {
                                            parts.push(format!(
                                                "import {{ {} }} from \"@tairitsu-glue/{}\";",
                                                map_syms.join(", "),
                                                m2
                                            ));
                                        }
                                        parts.join("\n  ")
                                    })
                                    .to_string();

                                if content != original {
                                    std::fs::write(&js_file, content)?;
                                }
                            }
                        }

                        // Patch preview2-shim resource instanceof checks that fail
                        // due to cross-module class identity issues (jco + preview2-shim).
                        // The getStdout/getStderr/subscribe calls return valid objects but
                        // from a different module instance than the expected class.
                        if let Ok(mut content) = std::fs::read_to_string(&js_file) {
                            let original = content.clone();
                            let patterns = [
                                ("OutputStream", "\"OutputStream\""),
                                ("InputStream", "\"InputStream\""),
                                ("Pollable", "\"Pollable\""),
                                ("TerminalOutput", "\"TerminalOutput\""),
                                ("TerminalInput", "\"TerminalInput\""),
                            ];
                            for (class_name, label) in patterns {
                                let check = format!(
                                    "if (!(ret instanceof {})) {{\n      throw new TypeError('Resource error: Not a valid {} resource.');\n    }}",
                                    class_name, label
                                );
                                let catch_check = format!(
                                    "if (!(e instanceof {})) {{\n      throw new TypeError('Resource error: Not a valid {} resource.');\n    }}",
                                    class_name, label
                                );
                                let comment = format!(
                                    "/* {} instanceof check patched for browser compat */",
                                    class_name
                                );
                                content = content.replace(&check, &comment);
                                content = content.replace(&catch_check, &comment);
                            }
                            if content != original {
                                std::fs::write(&js_file, content)?;
                            }
                        }
                    }
                    return Ok(true);
                }
                pb.println(format!(
                    "⚠  Wrapper transpile command succeeded but no JS wrapper entry was found.\n   Command: {}",
                    command_preview
                ));
                continue;
            }
            Ok(output) => {
                let stderr = String::from_utf8_lossy(&output.stderr).trim().to_string();
                let stdout = String::from_utf8_lossy(&output.stdout).trim().to_string();
                let detail = if !stderr.is_empty() {
                    stderr
                } else if !stdout.is_empty() {
                    stdout
                } else {
                    "(no output)".to_string()
                };
                let detail_preview: String = detail.chars().take(400).collect();

                pb.println(format!(
                    "⚠  Wrapper transpile command failed.\n   Command: {}\n   Exit: {}\n   Detail: {}",
                    command_preview,
                    output.status,
                    detail_preview
                ));
                continue;
            }
            Err(err) if err.kind() == std::io::ErrorKind::NotFound => {
                missing_commands.push(bin.to_string());
                // Don't print per-command not found - we'll summarize at the end
                continue;
            }
            Err(err) => {
                pb.println(format!(
                    "⚠  Failed to execute wrapper transpile command.\n   Command: {}\n   Error: {}",
                    command_preview, err
                ));
                continue;
            }
        }
    }

    // Only print one summary message for missing commands
    if !missing_commands.is_empty() {
        missing_commands.sort();
        missing_commands.dedup();
        pb.println(format!(
            "⚠  Wrapper transpile command not found: '{}'.\n   \
             Attempted: jco transpile {} -o {}",
            missing_commands.join(", "),
            wasm_path_hint,
            wrapper_dir_hint
        ));
    }

    Ok(false)
}

fn collect_css_output_paths(scss_config: &crate::config::ScssConfig) -> Vec<String> {
    let mut paths = Vec::new();

    if !scss_config.entries.is_empty() {
        for entry in &scss_config.entries {
            paths.push(entry.output.clone());
        }
    } else if scss_config.entry.is_some() {
        paths.push(scss_config.output.clone());
    } else {
        paths.push("styles.css".to_string());
    }

    paths
}

fn generate_component_html_with_output_dir(
    config: &Config,
    output_dir: &std::path::Path,
) -> crate::Result<()> {
    let pkg_name = &config.package.name;
    let wasm_file = format!("{}.wasm", pkg_name.replace('-', "_"));
    // Build-time version stamp so browsers never serve stale cached JS/WASM
    // modules even if `Cache-Control: no-store` is bypassed by a caching proxy.
    let v = std::time::SystemTime::now()
        .duration_since(std::time::UNIX_EPOCH)
        .map(|d| d.as_secs())
        .unwrap_or(0);

    let title = config.html.title.as_deref().unwrap_or(pkg_name.as_str());
    let favicon = config
        .html
        .favicon
        .as_deref()
        .map(|f| f.strip_prefix("public/").unwrap_or(f).replace('\\', "/"));
    let favicon_link = favicon
        .as_deref()
        .map(|href| format!("<link rel=\"icon\" href=\"./{}\">", href))
        .unwrap_or_default();

    let glue_bundle_path = &config.build.browser_glue_path;

    let mut ctx = tera::Context::new();
    ctx.insert("lang", &config.html.lang);
    ctx.insert("charset", &config.html.charset);
    ctx.insert("viewport", &config.html.viewport);
    ctx.insert("title", &title);
    ctx.insert("favicon", &favicon_link);
    ctx.insert("head", &config.html.head);
    ctx.insert("body_class", &config.html.body_class);
    ctx.insert("wasm_file", &wasm_file);
    ctx.insert("glue_bundle", glue_bundle_path);
    ctx.insert("v", &v.to_string());

    let mut tera = tera::Tera::default();
    tera.add_raw_template("index.html", include_str!("index.html.template"))
        .map_err(|e| {
            crate::TairitsuPackagerError::BuildError(format!("Template parse error: {e}"))
        })?;
    let html = tera.render("index.html", &ctx).map_err(|e| {
        crate::TairitsuPackagerError::BuildError(format!("Template render error: {e}"))
    })?;

    let mut html = html;

    if config.html.inline_css {
        let injector = crate::styles::StyleInjector::new();
        let css_paths = collect_css_output_paths(&config.scss);

        for css_path in &css_paths {
            let full_path = output_dir.join(css_path);
            match std::fs::read_to_string(&full_path) {
                Ok(css_content) => {
                    html = injector.inject_style_into_html(&html, &css_content)?;
                    crate::log_info!(
                        "{}",
                        crate::fmt_tmpl!(locale().build.inlined_css, path => css_path.to_string())
                    );
                }
                Err(e) => {
                    crate::log_warn!(
                        "CSS file not found for inline injection: {} ({})",
                        css_path,
                        e
                    );
                }
            }
        }
    }

    let html_path = output_dir.join("index.html");
    std::fs::write(&html_path, &html)?;

    generate_route_html_files(config, output_dir, &html)?;

    Ok(())
}

fn generate_route_html_files(
    config: &Config,
    output_dir: &std::path::Path,
    base_html: &str,
) -> crate::Result<()> {
    use crate::config::DiscoveredRoute;

    let routes = config.discovered_routes();
    if routes.is_empty() {
        return Ok(());
    }

    let non_root_routes: Vec<&DiscoveredRoute> = routes.iter().filter(|r| !r.is_root()).collect();

    if non_root_routes.is_empty() {
        return Ok(());
    }

    let route_preload_script = |route_path: &str| -> String {
        format!(
            "<script>if(history.replaceState){{history.replaceState(null,null,{path})}}</script>",
            path =
                serde_json::to_string(route_path).unwrap_or_else(|_| format!("'{}'", route_path))
        )
    };

    for route in &non_root_routes {
        let fs_route = route.fs_path();
        let route_dir = output_dir.join(fs_route);

        std::fs::create_dir_all(&route_dir).map_err(|e| {
            crate::TairitsuPackagerError::BuildError(format!(
                "Failed to create route directory {}: {}",
                route_dir.display(),
                e
            ))
        })?;

        let preload = route_preload_script(&route.path);
        let route_html = base_html.replace(
            "<div id=\"app\">Loading…</div>",
            &format!("<div id=\"app\" style=\"display:flex;align-items:center;justify-content:center;min-height:100vh;font-family:system-ui,sans-serif;color:rgba(255,255,255,.7)\"><div>Loading…</div></div>\n    {}", preload),
        );

        let route_file = route_dir.join("index.html");
        std::fs::write(&route_file, &route_html).map_err(|e| {
            crate::TairitsuPackagerError::BuildError(format!(
                "Failed to write route HTML {}: {}",
                route_file.display(),
                e
            ))
        })?;
    }

    crate::log_info!(
        "{}",
        crate::fmt_tmpl!(locale().build.generated_routes, n => non_root_routes.len().to_string())
    );

    Ok(())
}

/// Middleware that prevents browsers from caching JS/WASM/HTML assets in dev mode.
/// Without this, browsers serve stale cached modules even after a file changes.
#[cfg(feature = "dev-server")]
async fn no_cache_headers(
    request: axum::extract::Request,
    next: axum::middleware::Next,
) -> axum::response::Response {
    let path = request.uri().path().to_owned();
    let mut response = next.run(request).await;

    let should_bust = path == "/"
        || path.ends_with(".html")
        || path.ends_with(".js")
        || path.ends_with(".mjs")
        || path.ends_with(".wasm")
        || path.ends_with(".map");

    if should_bust {
        response.headers_mut().insert(
            axum::http::header::CACHE_CONTROL,
            axum::http::HeaderValue::from_static("no-store"),
        );
    }
    response
}

/// Returns true if the path requests a static asset (JS, WASM, CSS, etc.)
/// that should return 404 when missing, NOT the SPA fallback HTML.
#[cfg(feature = "dev-server")]
fn is_asset_request(path: &str) -> bool {
    const ASSET_EXTENSIONS: &[&str] = &[
        ".js", ".mjs", ".cjs", ".wasm", ".css", ".map", ".svg", ".png", ".jpg", ".jpeg", ".gif",
        ".ico", ".webp", ".woff", ".woff2", ".ttf", ".otf", ".eot",
    ];
    ASSET_EXTENSIONS.iter().any(|ext| path.ends_with(ext))
}

/// Middleware that returns a proper 404 for asset file requests (.js, .wasm, etc.)
/// when the file does not exist on disk.  Without this, the SPA fallback handler
/// would serve index.html (text/html) for missing JS files, causing:
///   "Failed to load module script: Expected a JavaScript module but got text/html"
#[cfg(feature = "dev-server")]
async fn reject_missing_assets(
    axum::extract::State(dist): axum::extract::State<std::sync::Arc<std::path::PathBuf>>,
    request: axum::extract::Request,
    next: axum::middleware::Next,
) -> axum::response::Response {
    use axum::response::IntoResponse;
    let path = request.uri().path();
    let is_get_or_head = *request.method() == axum::http::Method::GET
        || *request.method() == axum::http::Method::HEAD;
    if is_asset_request(path) && is_get_or_head {
        let clean = path.trim_start_matches('/');
        let file_path = dist.join(clean);
        if !file_path.exists() {
            return (
                axum::http::StatusCode::NOT_FOUND,
                format!("404 Not Found: {}", path),
            )
                .into_response();
        }
    }
    next.run(request).await
}

#[cfg(feature = "dev-server")]
#[allow(clippy::too_many_arguments)]
pub async fn dev_server(
    config: &Config,
    port: u16,
    open: bool,
    watch: bool,
    force: bool,
    verbose: bool,
    debug: bool,
    debug_port: Option<u16>,
    clean: bool,
) -> crate::Result<()> {
    use axum::response::Html;
    use axum::routing::get;
    use axum::{middleware, Router};
    use tower_http::services::ServeDir;

    if watch {
        crate::log_info!("{}", locale().build.dev_server_watch);
    } else {
        crate::log_info!("{}", locale().build.dev_server);
    }

    if !crate::daemon::is_daemon() && crate::daemon::is_daemon_running() {
        let pid = crate::daemon::read_pid().unwrap_or(0);
        crate::log_warn!(
            "{}",
            crate::fmt_tmpl!(locale().build.daemon_already_running, pid => pid.to_string())
        );
        crate::log_info!("{}", locale().build.daemon_attach_hint);
    }

    {
        let probe = std::net::TcpListener::bind(("127.0.0.1", port));
        if let Err(ref err) = probe {
            if err.kind() == std::io::ErrorKind::AddrInUse {
                let owner = crate::daemon::port_owner_info(port);
                let our_pid = crate::daemon::read_pid().unwrap_or(0);

                if let Some(ref info) = owner {
                    if info.pid == our_pid && !crate::daemon::is_daemon() {
                        return Err(crate::TairitsuPackagerError::BuildError(
                            crate::fmt_tmpl!(locale().dev.port_in_use_daemon, port => port.to_string(), pid => info.pid.to_string()),
                        ));
                    }

                    let is_tairitsu = info
                        .exe_path
                        .as_ref()
                        .map(|exe| {
                            let exe_str = exe.to_string_lossy().to_lowercase();
                            exe_str.contains("tairitsu")
                        })
                        .unwrap_or(false);

                    if is_tairitsu {
                        if !force {
                            let mut msg = crate::fmt_tmpl!(locale().dev.port_in_use_other_daemon, port => port.to_string(), pid => info.pid.to_string());
                            if let Some(ref exe) = info.exe_path {
                                msg.push_str(&format!("\n  Executable: {}", exe.display()));
                            }
                            msg.push_str(&format!("\n  {}", locale().dev.port_use_force));
                            return Err(crate::TairitsuPackagerError::BuildError(msg));
                        }

                        crate::log_warn!(
                            "{}",
                            crate::fmt_tmpl!(
                                locale().build.force_killing_daemon,
                                pid => info.pid.to_string(),
                                port => port.to_string()
                            )
                        );
                        crate::daemon::kill_process_by_pid(info.pid);
                        std::thread::sleep(std::time::Duration::from_millis(500));
                    }
                }

                let probe2 = std::net::TcpListener::bind(("127.0.0.1", port));
                if let Err(ref err2) = probe2 {
                    if err2.kind() == std::io::ErrorKind::AddrInUse {
                        let mut msg = crate::fmt_tmpl!(locale().dev.port_in_use_other, port => port.to_string());
                        if let Some(info) = owner {
                            msg.push_str(&format!(" (PID {})", info.pid));
                            if let Some(exe) = info.exe_path {
                                msg.push_str(&format!("\n  Executable: {}", exe.display()));
                            }
                        }
                        msg.push_str(&format!("\n  {}", locale().dev.port_change_hint));
                        return Err(crate::TairitsuPackagerError::BuildError(msg));
                    }
                }
                drop(probe2);
            }
        }
        drop(probe);
    }

    let (reload_tx, _) = tokio::sync::broadcast::channel::<()>(8);

    if clean {
        let dist_dir = if config.build.output_dir.is_relative() {
            config.manifest_dir.join(&config.build.output_dir)
        } else {
            config.build.output_dir.clone()
        };
        if dist_dir.exists() {
            crate::log_info!("Cleaning output directory: {}", dist_dir.display());
            let _ = std::fs::remove_dir_all(&dist_dir);
        }
    }

    let initial_started = Instant::now();
    crate::log_progress!(
        "{}",
        crate::fmt_tmpl!(locale().build.building_component, name => config.package.name.clone())
    );
    match config.build.target.as_str() {
        "component" => build_component(config, false, None, verbose).inspect_err(|e| {
            if crate::daemon::is_daemon() {
                let _ = crate::daemon::signal_failed(&e.to_string());
            }
        })?,
        other => {
            let err = crate::TairitsuPackagerError::BuildError(
                crate::fmt_tmpl!(locale().build.unknown_build_target, target => &other),
            );
            if crate::daemon::is_daemon() {
                let _ = crate::daemon::signal_failed(&err.to_string());
            }
            return Err(err);
        }
    }
    let initial_elapsed = initial_started.elapsed();

    let dist_dir = if config.build.output_dir.is_relative() {
        config.manifest_dir.join(&config.build.output_dir)
    } else {
        config.build.output_dir.clone()
    };

    let wasm_file = dist_dir.join(format!("{}.wasm", config.package.name.replace('-', "_")));
    let pkg_size_str = match std::fs::metadata(&wasm_file) {
        Ok(meta) => {
            let bytes = meta.len();
            if bytes >= 1_048_576 {
                format!("{:.1} MB", bytes as f64 / 1_048_576.0)
            } else {
                format!("{:.1} KB", bytes as f64 / 1024.0)
            }
        }
        Err(_) => String::from("unknown"),
    };

    crate::log_ok!(
        "{}",
        crate::fmt_tmpl!(locale().build.initial_build_ok, elapsed => format!("{:.1?}", initial_elapsed))
    );
    crate::log_info!(
        "{}",
        crate::fmt_tmpl!(locale().build.workspace_label, dir => config.manifest_dir.display().to_string())
    );
    crate::log_info!(
        "{}",
        crate::fmt_tmpl!(locale().build.package_label, name => config.package.name.clone(), version => config.package.version.clone())
    );
    crate::log_info!(
        "{}",
        crate::fmt_tmpl!(locale().build.output_label, dir => dist_dir.display().to_string(), size => pkg_size_str)
    );

    let dist_for_index = dist_dir.clone();
    let pkg_name = config.package.name.clone();
    let dist_for_spa = dist_for_index.clone();
    let spa_pkg_name = pkg_name.clone();

    let discovered = config.discovered_routes();
    let known_route_paths: Vec<String> = discovered
        .iter()
        .filter(|r| !r.is_root())
        .map(|r| r.path.clone())
        .collect();

    let spa_fallback = Router::new().fallback(get(move |req: axum::extract::Request| {
        let dist = dist_for_spa.clone();
        let pkg = spa_pkg_name.clone();
        let routes = known_route_paths.clone();
        async move {
            let path = req.uri().path().trim_end_matches('/');

            let route_file = if !path.is_empty()
                && routes
                    .iter()
                    .any(|r| r == path || format!("{}/", r) == *path)
            {
                let clean_path = path.strip_prefix('/').unwrap_or(path);
                Some(dist.join(clean_path).join("index.html"))
            } else {
                None
            };

            let content = match route_file {
                Some(ref fp) if fp.exists() => std::fs::read_to_string(fp),
                _ => Err(std::io::Error::new(
                    std::io::ErrorKind::NotFound,
                    "no route file",
                )),
            }
            .or_else(|_| std::fs::read_to_string(dist.join("index.html")))
            .unwrap_or_else(|_| {
                format!(
                    "<!DOCTYPE html><html><head><title>{}</title></head>\
                         <body><div id=\"app\">Loading…</div></body></html>",
                    pkg
                )
            });
            Html(content)
        }
    }));
    let reload_tx_for_route = reload_tx.clone();
    let dist_state = std::sync::Arc::new(dist_dir.clone());

    let app = Router::new()
        .route(
            "/__tairitsu_reload",
            get(move || {
                let tx = reload_tx_for_route.clone();
                async move {
                    use axum::response::sse::{Event, Sse};
                    use axum::response::IntoResponse;
                    use futures::stream::StreamExt;
                    let receiver = tx.subscribe();
                    let stream =
                        tokio_stream::wrappers::BroadcastStream::new(receiver).map(|result| {
                            match result {
                                Ok(()) => Ok::<_, std::io::Error>(Event::default().data("reload")),
                                Err(_) => Err(std::io::Error::other("lagged")),
                            }
                        });
                    Sse::new(stream)
                        .keep_alive(
                            axum::response::sse::KeepAlive::new()
                                .interval(Duration::from_secs(15))
                                .text("ping"),
                        )
                        .into_response()
                }
            }),
        )
        .route(
            "/",
            get(move || {
                let dist = dist_for_index.clone();
                let pkg = pkg_name.clone();
                async move {
                    let content =
                        std::fs::read_to_string(dist.join("index.html")).unwrap_or_else(|_| {
                            format!(
                                "<!DOCTYPE html><html><head><title>{}</title></head>\
                                 <body><div id=\"app\">Loading…</div></body></html>",
                                pkg
                            )
                        });
                    Html(content)
                }
            }),
        );

    let app = app
        .fallback_service(ServeDir::new(dist_dir).fallback(spa_fallback))
        .layer(middleware::from_fn_with_state(
            dist_state,
            reject_missing_assets,
        ))
        .layer(middleware::from_fn(no_cache_headers));

    let (listener, actual_port) = bind_listener_with_fallback(port).await?;

    let effective_debug_port = debug_port.unwrap_or(actual_port + 1);
    if debug {
        let cfg = config.clone();
        tokio::spawn(async move {
            if let Err(e) =
                crate::debug::start_debug_server(&cfg, actual_port, effective_debug_port).await
            {
                crate::log_warn!("Debug API server error: {}", e);
            }
        });
        crate::log_info!(
            "Debug API enabled → http://localhost:{}",
            effective_debug_port
        );
    }

    if crate::daemon::is_daemon() {
        #[cfg(feature = "debug-browser")]
        let dp = Some(effective_debug_port);
        #[cfg(not(feature = "debug-browser"))]
        let dp = None;
        let _ = crate::daemon::signal_ready(actual_port, dp);
        crate::daemon::register_cleanup_on_exit().await;
    }

    let mut last_build_line = format_last_build_line(true, initial_elapsed, None);

    let port_switched = if actual_port != port {
        Some(
            locale()
                .dev
                .port_switched
                .replace("{from}", &port.to_string())
                .replace("{to}", &actual_port.to_string()),
        )
    } else {
        None
    };

    print_status_panel(
        actual_port,
        &config.build.output_dir,
        Some(&last_build_line),
        port_switched.as_deref(),
    );

    if open || config.dev.open_browser {
        let url = format!("http://localhost:{}", actual_port);
        match webbrowser::open(&url) {
            Ok(_) => crate::log_ok!("{}", locale().dev.opening_browser),
            Err(e) => crate::log_warn!("{}: {}", locale().dev.open_browser_failed, e),
        }
    }

    if watch {
        // Run the HTTP server as a background task; this task runs the watch loop.
        tokio::spawn(async move {
            axum::serve(listener, app).await.ok();
        });
        run_watch_loop(
            config,
            actual_port,
            &config.build.output_dir,
            &mut last_build_line,
            reload_tx,
            verbose,
        )
        .await?;
    } else {
        crate::log_info!("{}", locale().dev.press_ctrl_c_to_stop);
        let shutdown = async {
            #[cfg(unix)]
            {
                use tokio::signal::unix::{signal, SignalKind};
                let mut sigterm = signal(SignalKind::terminate()).unwrap();
                tokio::select! {
                    _ = tokio::signal::ctrl_c() => {},
                    _ = sigterm.recv() => {},
                }
            }
            #[cfg(not(unix))]
            {
                tokio::signal::ctrl_c().await.ok();
            }
        };
        axum::serve(listener, app)
            .with_graceful_shutdown(shutdown)
            .await?;
    }

    Ok(())
}

#[cfg(feature = "dev-server")]
fn print_status_panel(
    port: u16,
    output_dir: &std::path::Path,
    last_build_line: Option<&str>,
    warning: Option<&str>,
) {
    crate::log_ok!("{}: http://localhost:{}", locale().dev.local, port);
    crate::log_info!("{}: {}", locale().dev.serving, output_dir.display());
    if let Some(line) = last_build_line {
        crate::log_info!("{}", line);
    }
    if let Some(w) = warning {
        crate::log_warn!("{}", w);
    }
}

#[cfg(feature = "dev-server")]
fn format_last_build_line(ok: bool, elapsed: Duration, error_hint: Option<&str>) -> String {
    let b = &locale().build;
    let status = if ok {
        b.status_ok.as_str()
    } else {
        b.status_fail.as_str()
    };
    let mut line = format!("{} | {:.1?}", status, elapsed);
    if let Some(hint) = error_hint {
        let display = if hint.len() > 50 { &hint[..50] } else { hint };
        line.push_str(&format!(" | {}", display));
    }
    line
}

#[cfg(feature = "dev-server")]
fn format_building_line() -> String {
    locale().dev.build_rebuilding.clone()
}
/// Try binding localhost starting from `preferred_port` and automatically
/// fallback to higher ports when the preferred one is already occupied.
#[cfg(feature = "dev-server")]
async fn bind_listener_with_fallback(
    preferred_port: u16,
) -> crate::Result<(tokio::net::TcpListener, u16)> {
    const MAX_CANDIDATES: u16 = 20;

    for offset in 0..MAX_CANDIDATES {
        let candidate = preferred_port.saturating_add(offset);
        let addr = std::net::SocketAddr::from(([127, 0, 0, 1], candidate));

        match tokio::net::TcpListener::bind(addr).await {
            Ok(listener) => return Ok((listener, candidate)),
            Err(err) if err.kind() == std::io::ErrorKind::AddrInUse => continue,
            Err(err) => {
                return Err(crate::TairitsuPackagerError::BuildError(format!(
                    "failed to bind dev server at {}: {}",
                    addr, err
                )));
            }
        }
    }

    let last = preferred_port.saturating_add(MAX_CANDIDATES - 1);

    let mut hint = String::new();
    if crate::daemon::is_daemon_running() {
        hint = format!(
            "\n\n  Hint: A tairitsu daemon is already running (PID {}). \
             To attach to it, use: tairitsu dev --daemon\n  \
             To stop it first, use: tairitsu dev --shutdown",
            crate::daemon::read_pid().unwrap_or(0)
        );
    } else if let Some(owner) = crate::daemon::port_owner_info(preferred_port) {
        hint = format!(
            "\n\n  Hint: Port {} is held by PID {}{}.",
            preferred_port,
            owner.pid,
            owner
                .exe_path
                .map(|p| format!(" ({})", p.display()))
                .unwrap_or_default()
        );
    }

    Err(crate::TairitsuPackagerError::BuildError(format!(
        "failed to bind dev server: no free port in range {}..={}{}",
        preferred_port, last, hint
    )))
}

#[cfg(feature = "dev-server")]
#[derive(Debug, Clone, Copy)]
enum DevCmd {
    Rebuild,
    OpenBrowser,
    Clear,
}

/// Watches `src/`, `Cargo.toml`, `Tairitsu.toml`, and `public/` for changes and
/// triggers incremental rebuilds using the same pipeline as the initial build.
///
/// Debounces rapid saves (200 ms window) so a single `cargo save` operation does
/// not trigger multiple concurrent builds.
#[cfg(feature = "dev-server")]
async fn run_watch_loop(
    config: &Config,
    port: u16,
    output_dir: &std::path::Path,
    last_build_line: &mut String,
    reload_tx: tokio::sync::broadcast::Sender<()>,
    verbose: bool,
) -> crate::Result<()> {
    use notify::{EventKind, RecursiveMode, Watcher};

    let project_root = std::env::current_dir()?;

    // Collect existing watch paths before moving them into the OS thread.
    let watch_paths: Vec<std::path::PathBuf> = [
        project_root.join("src"),
        project_root.join("Cargo.toml"),
        project_root.join("Tairitsu.toml"),
        project_root.join("public"),
    ]
    .into_iter()
    .filter(|p| p.exists())
    .collect();

    let (tx, mut rx) = tokio::sync::mpsc::channel::<notify::Result<notify::Event>>(64);

    // Spawn the watcher on a dedicated OS thread.  Some platform backends
    // (e.g. FSEvents on macOS) are not Send; isolating them here avoids that.
    std::thread::spawn(move || {
        let Ok(mut watcher) = notify::recommended_watcher(move |ev| {
            tx.blocking_send(ev).ok();
        }) else {
            crate::log_warn!("Failed to create file watcher");
            return;
        };

        for path in &watch_paths {
            let mode = if path.is_dir() {
                RecursiveMode::Recursive
            } else {
                RecursiveMode::NonRecursive
            };
            if let Err(e) = watcher.watch(path, mode) {
                crate::log_warn!("Cannot watch {}: {}", path.display(), e);
            }
        }

        crate::log_ok!("{}", locale().dev.watching_for_changes);

        // Keep the watcher alive until the process exits.
        loop {
            std::thread::sleep(Duration::from_secs(3600));
        }
    });

    // -- Keyboard command listener ---------------------------------------------
    // Runs on a dedicated blocking thread so the tokio runtime is never stalled
    // waiting for stdin.  The user types a letter + Enter to send a command.
    // Skipped in daemon mode where stdin is unavailable.
    let (cmd_tx, mut cmd_rx) = tokio::sync::mpsc::channel::<DevCmd>(8);
    if !crate::daemon::is_daemon() {
        tokio::task::spawn_blocking(move || {
            use std::io::BufRead;
            for line in std::io::stdin().lock().lines() {
                let line = match line {
                    Ok(l) => l,
                    Err(_) => continue,
                };
                let cmd = match line.trim() {
                    "r" | "R" => Some(DevCmd::Rebuild),
                    "o" | "O" => Some(DevCmd::OpenBrowser),
                    "c" | "C" => Some(DevCmd::Clear),
                    _ => None,
                };
                if let Some(c) = cmd {
                    if cmd_tx.blocking_send(c).is_err() {
                        break;
                    }
                }
            }
        });
    }

    let debounce = tokio::time::Duration::from_millis(200);

    'watch: loop {
        // Wait for a rebuild trigger — either a file-system event or a keyboard
        // command.  `changed` is populated only for file-driven triggers.
        let mut changed: Vec<std::path::PathBuf> = Vec::new();

        let should_rebuild = tokio::select! {
            ev = rx.recv() => {
                let ev = match ev {
                    None => break 'watch,
                    Some(Err(e)) => {
                        crate::log_warn!("{}: {}", locale().dev.watch_error, e);
                        continue;
                    }
                    Some(Ok(e)) => e,
                };
                if !matches!(
                    ev.kind,
                    EventKind::Create(_) | EventKind::Modify(_) | EventKind::Remove(_)
                ) {
                    continue;
                }

                // Collect paths for this event.
                changed = ev
                    .paths
                    .iter()
                    .filter_map(|p: &std::path::PathBuf| p.strip_prefix(&project_root).ok().map(|r: &std::path::Path| r.to_path_buf()))
                    .collect();

                // Debounce: drain further events within the 200 ms window.
                let deadline = tokio::time::Instant::now() + debounce;
                while let Ok(Some(Ok(ev))) = tokio::time::timeout_at(deadline, rx.recv()).await {
                    changed.extend(ev.paths.iter().filter_map(|p: &std::path::PathBuf| {
                        p.strip_prefix(&project_root).ok().map(|r: &std::path::Path| r.to_path_buf())
                    }));
                }
                changed.sort();
                changed.dedup();
                true
            }

            cmd = cmd_rx.recv() => {
                match cmd {
                    None => break 'watch,
                    Some(DevCmd::Rebuild) => {
                        crate::log_progress!("{}", locale().dev.manual_rebuild_triggered);
                        true
                    }
                    Some(DevCmd::OpenBrowser) => {
                        let url = format!("http://localhost:{}", port);
                        crate::log_info!("{} {}", locale().dev.opening_url, url);
                        webbrowser::open(&url).ok();
                        false
                    }
                    Some(DevCmd::Clear) => {
                        // ANSI: clear screen and move cursor to top-left.
                        // indicatif redraws its persistent bars on the next tick.
                        print!("\x1b[2J\x1b[1;1H");
                        use std::io::Write;
                        std::io::stdout().flush().ok();
                        false
                    }
                }
            }

            _ = async {
                #[cfg(unix)]
                {
                    use tokio::signal::unix::{SignalKind, signal};
                    let mut sigterm = signal(SignalKind::terminate()).unwrap();
                    tokio::select! {
                        _ = tokio::signal::ctrl_c() => {},
                        _ = sigterm.recv() => {},
                    }
                }
                #[cfg(not(unix))]
                {
                    tokio::signal::ctrl_c().await.ok();
                }
            } => {
                crate::log_ok!("{}", locale().dev.stopping);
                crate::logfmt::clear_active_pb();
                use std::io::Write;
                let _ = std::io::stdout().write_all(b"\x1b[?25h");
                let _ = std::io::stdout().flush();
                break 'watch;
            }
        };

        if !should_rebuild {
            continue;
        }

        if changed.is_empty() {
            crate::log_progress!("{}", locale().dev.source_changed);
        } else if changed.len() == 1 {
            crate::log_progress!("{}", changed[0].display());
        } else {
            crate::log_progress!("{} {}", changed.len(), locale().dev.files_changed);
        }

        *last_build_line = format_building_line();
        print_status_panel(port, output_dir, Some(last_build_line), None);

        // Run the rebuild on a blocking thread so the tokio runtime stays alive.
        // The progress bar is managed internally by build_component.
        let rebuild_started = Instant::now();
        let config_clone = config.clone();
        let target = config.build.target.clone();
        let target_for_build = target.clone();
        let result = tokio::task::spawn_blocking(move || match target_for_build.as_str() {
            "component" => build_component(&config_clone, false, None, verbose),
            other => Err(crate::TairitsuPackagerError::BuildError(format!(
                "Unknown build target '{}'. Only 'component' is supported.",
                other
            ))),
        })
        .await
        .map_err(|e| {
            crate::TairitsuPackagerError::BuildError(format!("rebuild task panicked: {}", e))
        })?;

        let elapsed = rebuild_started.elapsed();
        match result {
            Ok(()) => {
                *last_build_line = format_last_build_line(true, elapsed, None);
                print_status_panel(port, output_dir, Some(last_build_line), None);
                crate::log_ok!(
                    "{}  ->  http://localhost:{}  ({:.1?})",
                    locale().dev.rebuilt,
                    port,
                    elapsed
                );

                let _ = reload_tx.send(());

                if daemon::is_daemon() {
                    let _ = daemon::append_build_log("component", true, None);
                }
            }
            Err(e) => {
                let hint = extract_error_hint(e.to_string());
                *last_build_line = format_last_build_line(false, elapsed, Some(&hint));
                print_status_panel(port, output_dir, Some(last_build_line), None);
                crate::log_fail!("{}", e);

                if daemon::is_daemon() {
                    let _ = daemon::append_build_log("component", false, Some(&e.to_string()));
                }
            }
        }
    }

    Ok(())
}

/// Extract a concise one-line description from a build error for the TUI status bar.
#[cfg(feature = "dev-server")]
fn extract_error_hint(msg: String) -> String {
    // Prefer lines beginning with rustc-style "error[…]" or "error: …"
    for line in msg.lines() {
        let t = line.trim();
        if (t.starts_with("error[") || t.starts_with("error: "))
            && !t.contains("aborting due to")
            && t.len() > 6
        {
            return if t.len() > 55 {
                t[..55].to_string()
            } else {
                t.to_string()
            };
        }
    }
    // Fallback: first non-empty line, capped at 55 chars.
    let first = msg.lines().find(|l| !l.trim().is_empty()).unwrap_or(&msg);
    let first = first.trim();
    if first.len() > 55 {
        first[..55].to_string()
    } else {
        first.to_string()
    }
}
