//! Rust code generation for icons.
//!
//! Generates icon enum and data module with SVG paths.

use std::path::PathBuf;

use super::{IconEntry, IconStyle};

/// Result of icon building
#[derive(Debug, Clone)]
pub struct IconBuildResult {
    /// Number of icons generated
    pub icons_count: usize,

    /// Output file path
    pub output_path: PathBuf,

    /// Generated Rust code
    pub generated_code: String,
}

/// Generate icon module Rust code
pub fn generate_icon_module(icons: &[&IconEntry], styles: &[IconStyle]) -> crate::Result<String> {
    let mut code = String::new();

    // Header
    code.push_str("//! Auto-generated icon module\n");
    code.push_str("//! Generated by tairitsu-packager\n");
    code.push_str("//! DO NOT EDIT MANUALLY\n\n");
    code.push_str("#![allow(dead_code)]\n");
    code.push_str("#![allow(non_camel_case_types)]\n\n");

    // Icon enum
    code.push_str("/// Available icons\n");
    code.push_str("#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]\n");
    code.push_str("pub enum Icon {\n");

    for icon in icons {
        let ident = icon.to_rust_ident();
        code.push_str(&format!("    /// {}\n", icon.name));
        if let Some(ref author) = icon.author {
            code.push_str(&format!("    /// Author: {}\n", author));
        }
        for tag in &icon.tags {
            code.push_str(&format!("    /// Tag: {}\n", tag));
        }
        code.push_str(&format!("    {},\n", ident));
    }

    code.push_str("}\n\n");

    // Icon implementation
    code.push_str("impl Icon {\n");

    // name() method
    code.push_str("    /// Get the original icon name\n");
    code.push_str("    pub fn name(&self) -> &'static str {\n");
    code.push_str("        match self {\n");
    for icon in icons {
        let ident = icon.to_rust_ident();
        code.push_str(&format!("            Icon::{} => \"{}\",\n", ident, icon.name));
    }
    code.push_str("        }\n");
    code.push_str("    }\n\n");

    // svg_path() method for filled style (default)
    if styles.contains(&IconStyle::Filled) || styles.is_empty() {
        code.push_str("    /// Get the SVG path data (filled style)\n");
        code.push_str("    pub fn svg_path(&self) -> &'static str {\n");
        code.push_str("        match self {\n");
        for icon in icons {
            let ident = icon.to_rust_ident();
            let path = icon.svg_path.as_deref().unwrap_or("");
            code.push_str(&format!("            Icon::{} => \"{}\",\n", ident, path));
        }
        code.push_str("        }\n");
        code.push_str("    }\n\n");
    }

    // svg_path_outline() method for outline style
    if styles.contains(&IconStyle::Outline) {
        code.push_str("    /// Get the SVG path data (outline style)\n");
        code.push_str("    pub fn svg_path_outline(&self) -> &'static str {\n");
        code.push_str("        match self {\n");
        for icon in icons {
            let ident = icon.to_rust_ident();
            // Note: MDI outline paths would be different, for now use same as filled
            let path = icon.svg_path.as_deref().unwrap_or("");
            code.push_str(&format!("            Icon::{} => \"{}\",\n", ident, path));
        }
        code.push_str("        }\n");
        code.push_str("    }\n\n");
    }

    // tags() method
    code.push_str("    /// Get the icon tags\n");
    code.push_str("    pub fn tags(&self) -> &'static [&'static str] {\n");
    code.push_str("        match self {\n");
    for icon in icons {
        let ident = icon.to_rust_ident();
        let tags: Vec<&str> = icon.tags.iter().map(String::as_str).collect();
        code.push_str(&format!(
            "            Icon::{} => &[{}],\n",
            ident,
            tags.iter().map(|t| format!("\"{}\"", t)).collect::<Vec<_>>().join(", ")
        ));
    }
    code.push_str("        }\n");
    code.push_str("    }\n\n");

    // all() method
    code.push_str("    /// Get all icons\n");
    code.push_str("    pub fn all() -> &'static [Icon] {\n");
    code.push_str("        &[\n");
    for icon in icons {
        let ident = icon.to_rust_ident();
        code.push_str(&format!("            Icon::{},\n", ident));
    }
    code.push_str("        ]\n");
    code.push_str("    }\n");

    code.push_str("}\n\n");

    // ICON_COUNT constant
    code.push_str(&format!("/// Total number of icons\n"));
    code.push_str(&format!("pub const ICON_COUNT: usize = {};\n\n", icons.len()));

    // Icon names array for lookup
    code.push_str("/// All icon names\n");
    code.push_str("pub const ICON_NAMES: &[&str] = &[\n");
    for icon in icons {
        code.push_str(&format!("    \"{}\",\n", icon.name));
    }
    code.push_str("];\n");

    Ok(code)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_generate_icon_module() {
        let icons = vec![
            IconEntry {
                name: "account".to_string(),
                aliases: vec![],
                tags: vec!["Account".to_string()],
                author: Some("Google".to_string()),
                version: None,
                deprecated: false,
                svg_path: Some("M12 2C6.48 2 2 6.48 2 12s4.48 10 10 10 10-4.48 10-10S17.52 2 12 2z".to_string()),
            },
            IconEntry {
                name: "sun".to_string(),
                aliases: vec![],
                tags: vec!["Nature".to_string()],
                author: None,
                version: None,
                deprecated: false,
                svg_path: Some("M12 7c-2.76 0-5 2.24-5 5s2.24 5 5 5 5-2.24 5-5-2.24-5-5-5z".to_string()),
            },
        ];

        let icons_refs: Vec<&IconEntry> = icons.iter().collect();
        let code = generate_icon_module(&icons_refs, &[IconStyle::Filled]).unwrap();

        assert!(code.contains("pub enum Icon"));
        assert!(code.contains("account,"));
        assert!(code.contains("sun,"));
        assert!(code.contains("pub fn svg_path"));
        assert!(code.contains("ICON_COUNT: usize = 2"));
    }
}
