//! Hikari-icons integration: resolve icon data for hikari-icons at build time.
//!
//! This module downloads MDI SVGs from GitHub, extracts SVG path data, and
//! generates an `impl_icons!` macro invocation file that hikari-icons expects
//! via the `TAIRITSU_ICONS_RS` environment variable.

use std::io::Write as _;
use std::path::{Path, PathBuf};

/// MDI single-SVG download URL template
const MDI_SVG_URL_PREFIX: &str =
    "https://raw.githubusercontent.com/Templarian/MaterialDesign/master/svg/";

/// Resolve hikari-icons data.
///
/// Reads `icons.txt` (list of icon kebab names), downloads SVGs from GitHub,
/// caches them locally, extracts path data, and writes `impl_icons!` code.
pub fn resolve(icons_txt: &Path, target_dir: &Path, offline: bool) -> crate::Result<PathBuf> {
    let icon_names = read_icon_names(icons_txt)?;
    if icon_names.is_empty() {
        crate::log_warn!("No icon names in {}", icons_txt.display());
        return write_impl_icons(target_dir, &[]);
    }

    let cache_dir = target_dir.join("tairitsu/icons/hikari/svg");
    std::fs::create_dir_all(&cache_dir)?;

    let mut entries: Vec<IconEntry> = Vec::with_capacity(icon_names.len());

    for name in &icon_names {
        let svg_path = cache_dir.join(format!("{}.svg", name));

        if !svg_path.exists() {
            if offline {
                continue;
            }
            let url = format!("{}{}.svg", MDI_SVG_URL_PREFIX, name);
            if let Err(e) = download_to(&url, &svg_path) {
                crate::log_warn!("Skipping {}: {}", name, e);
                continue;
            }
        }

        if let Ok(svg) = std::fs::read_to_string(&svg_path) {
            if let Some(d) = extract_path_d(&svg) {
                let const_name = name.replace('-', "_").to_uppercase();
                entries.push(IconEntry {
                    kebab: name.clone(),
                    const_name,
                    path: d,
                });
            }
        }
    }

    if entries.is_empty() && !icon_names.is_empty() {
        return Err(crate::TairitsuPackagerError::IconFetchError(if offline {
            "No cached icons found. Run without --offline to download.".to_string()
        } else {
            "Failed to resolve any icons.".to_string()
        }));
    }

    crate::log_info!(
        "Resolved {}/{} hikari icons",
        entries.len(),
        icon_names.len()
    );
    write_impl_icons(target_dir, &entries)
}

struct IconEntry {
    kebab: String,
    const_name: String,
    path: String,
}

fn read_icon_names(path: &Path) -> crate::Result<Vec<String>> {
    let content = std::fs::read_to_string(path).map_err(|e| {
        crate::TairitsuPackagerError::IconFetchError(format!(
            "Failed to read {}: {}",
            path.display(),
            e
        ))
    })?;
    Ok(content
        .lines()
        .map(|s| s.trim().to_string())
        .filter(|s| !s.is_empty() && !s.starts_with('#'))
        .collect())
}

fn write_impl_icons(target_dir: &Path, entries: &[IconEntry]) -> crate::Result<PathBuf> {
    let gen_dir = target_dir.join("tairitsu/generated");
    std::fs::create_dir_all(&gen_dir)?;
    let output = gen_dir.join("hikari_icons.rs");

    let mut f = std::fs::File::create(&output)?;
    writeln!(f, "// @generated by tairitsu-packager — DO NOT EDIT")?;
    writeln!(f)?;
    writeln!(f, "crate::impl_icons! {{")?;
    for e in entries {
        writeln!(
            f,
            "    {:?} => {{ ident: {}, path: {:?}, view_box: \"0 0 24 24\" }},",
            e.kebab, e.const_name, e.path
        )?;
    }
    writeln!(f, "}}")?;

    crate::log_info!("Generated {}", output.display());
    Ok(output)
}

/// Extract the `d` attribute from an SVG `<path>` element.
fn extract_path_d(svg: &str) -> Option<String> {
    let start = svg.find("<path")?;
    let rest = &svg[start..];
    let d_start = rest.find("d=\"")? + 3;
    let d_end = rest[d_start..].find('\"')?;
    Some(rest[d_start..d_start + d_end].to_string())
}

/// Download a URL to a local file.
#[cfg(feature = "icon-fetch")]
fn download_to(url: &str, dest: &Path) -> Result<(), String> {
    let out = std::process::Command::new("curl")
        .args(["-fsSL", "-o", &dest.to_string_lossy(), url])
        .output()
        .map_err(|e| format!("spawn curl: {}", e))?;
    if !out.status.success() {
        let stderr = String::from_utf8_lossy(&out.stderr);
        return Err(format!("curl {} failed: {}", url, stderr.trim()));
    }
    Ok(())
}

#[cfg(not(feature = "icon-fetch"))]
fn download_to(_url: &str, _dest: &Path) -> Result<(), String> {
    Err("icon-fetch feature not enabled".to_string())
}
