//! Build script for generating CSS property enums from data.
//!
//! This script:
//! 1. Reads CSS property data from css_data/css_properties.json
//! 2. Generates Rust code for the CssProperty enum
//! 3. Writes the generated code to src/properties/generated.rs

use std::{collections::BTreeMap, env, fs, path::Path};

fn main() {
    println!("cargo:rerun-if-changed=css_data/css_properties.json");
    println!("cargo:rerun-if-changed=build.rs");

    let manifest_dir = env::var("CARGO_MANIFEST_DIR").unwrap();
    let data_path = Path::new(&manifest_dir).join("css_data/css_properties.json");
    let output_path = Path::new(&manifest_dir).join("src/properties/generated.rs");

    let data = fs::read_to_string(&data_path).unwrap_or_else(|e| {
        panic!(
            "Failed to read CSS properties data from {}: {}",
            data_path.display(),
            e
        )
    });

    let css_data: CssData = serde_json::from_str(&data)
        .unwrap_or_else(|e| panic!("Failed to parse CSS properties data: {}", e));

    let generated_code = generate_property_enum(&css_data);

    fs::write(&output_path, generated_code).unwrap_or_else(|e| {
        panic!(
            "Failed to write generated code to {}: {}",
            output_path.display(),
            e
        )
    });

    println!(
        "cargo:warning=Generated {} CSS properties",
        css_data.properties().len()
    );
}

#[derive(Debug, serde::Deserialize)]
struct CssData {
    #[serde(rename = "categories")]
    categories_map: BTreeMap<String, CategoryData>,
    #[serde(default)]
    version: String,
    #[serde(default)]
    source: String,
    #[serde(default)]
    last_updated: String,
}

impl CssData {
    /// Flatten the categories map into a sorted list of properties
    fn properties(&self) -> Vec<PropertyEntry> {
        let mut props = Vec::new();

        for (category_name, category_data) in &self.categories_map {
            for prop in &category_data.properties {
                props.push(PropertyEntry {
                    name: prop.name.clone(),
                    rust_name: prop
                        .rust_name
                        .clone()
                        .unwrap_or_else(|| to_rust_name(&prop.name)),
                    category: category_name.clone(),
                    status: prop.status.clone(),
                    shorthand: prop.shorthand,
                    mdn_url: prop.mdn_url.clone(),
                });
            }
        }

        props.sort_by(|a, b| match a.category.cmp(&b.category) {
            std::cmp::Ordering::Equal => a.name.cmp(&b.name),
            other => other,
        });

        props
    }
}

#[derive(Debug)]
struct PropertyEntry {
    name: String,
    rust_name: String,
    category: String,
    status: String,
    shorthand: bool,
    mdn_url: String,
}

#[derive(Debug, serde::Deserialize)]
struct CategoryData {
    #[allow(dead_code)]
    description: String,
    properties: Vec<PropertyData>,
}

#[derive(Debug, serde::Deserialize)]
struct PropertyData {
    name: String,
    #[serde(rename = "rust_name", default)]
    rust_name: Option<String>,
    status: String,
    shorthand: bool,
    #[serde(rename = "mdn_url")]
    mdn_url: String,
}

/// Convert CSS property name to Rust enum variant name
fn to_rust_name(css_name: &str) -> String {
    // Split by hyphens, capitalize each part, remove hyphens
    css_name
        .split('-')
        .enumerate()
        .map(|(i, part)| {
            if i == 0 {
                // First word: capitalize first letter
                let mut chars = part.chars();
                match chars.next() {
                    None => String::new(),
                    Some(first) => first.to_uppercase().collect::<String>() + chars.as_str(),
                }
            } else {
                // Subsequent words: capitalize first letter
                let mut chars = part.chars();
                match chars.next() {
                    None => String::new(),
                    Some(first) => first.to_uppercase().collect::<String>() + chars.as_str(),
                }
            }
        })
        .collect()
}

fn generate_property_enum(data: &CssData) -> String {
    let properties = data.properties();

    let mut code = String::new();

    // File header
    code.push_str("// Auto-generated by build.rs from css_data/css_properties.json\n");
    code.push_str("// DO NOT EDIT manually - your changes will be overwritten\n");
    code.push_str("//\n");
    code.push_str("// This file is generated during the build process.\n");
    code.push_str("// To add or modify CSS properties, edit css_data/css_properties.json\n");
    code.push_str("// and run `cargo build` to regenerate this file.\n");
    code.push_str("//\n");
    code.push_str(&format!(
        "// Generated from CSS properties data version: {}\n",
        data.version
    ));
    code.push_str(&format!("// Source: {}\n", data.source));
    code.push_str(&format!("// Last updated: {}\n", data.last_updated));
    code.push_str(&format!("// Total properties: {}\n", properties.len()));
    code.push('\n');

    // Imports
    code.push_str("use super::category::CssCategory;\n");
    code.push('\n');

    // Enum definition
    code.push_str("#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]\n");
    code.push_str("pub enum CssProperty {\n");

    // Group properties by category for better organization
    let mut last_category = String::new();
    for prop in &properties {
        if prop.category != last_category {
            if !last_category.is_empty() {
                code.push('\n');
            }
            code.push_str(&format!("    // {} properties\n", prop.category));
            last_category = prop.category.clone();
        }
        code.push_str(&format!("    {},\n", prop.rust_name));
    }

    code.push_str("}\n");
    code.push('\n');

    // Generate as_str method
    code.push_str("impl CssProperty {\n");
    code.push_str("    /// Get the CSS property name as a string.\n");
    code.push_str("    #[inline]\n");
    code.push_str("    pub fn as_str(&self) -> &'static str {\n");
    code.push_str("        match self {\n");

    for prop in &properties {
        code.push_str(&format!(
            "            CssProperty::{} => \"{}\",\n",
            prop.rust_name, prop.name
        ));
    }

    code.push_str("        }\n");
    code.push_str("    }\n");
    code.push('\n');

    // Generate category method
    code.push_str("    /// Get the category of this CSS property.\n");
    code.push_str("    #[inline]\n");
    code.push_str("    pub fn category(&self) -> CssCategory {\n");
    code.push_str("        match self {\n");

    for prop in &properties {
        let category_variant = match prop.category.as_str() {
            "BoxModel" => "CssCategory::BoxModel",
            "Flexbox" => "CssCategory::Flexbox",
            "Grid" => "CssCategory::Grid",
            "Typography" => "CssCategory::Typography",
            "Color" => "CssCategory::Color",
            "Visual" => "CssCategory::Visual",
            "Transform" => "CssCategory::Transform",
            "Transition" => "CssCategory::Transition",
            "Animation" => "CssCategory::Animation",
            "Interaction" => "CssCategory::Interaction",
            "List" => "CssCategory::List",
            "Table" => "CssCategory::Table",
            "Paged" => "CssCategory::Paged",
            "GeneratedContent" => "CssCategory::GeneratedContent",
            "FlexGridGap" => "CssCategory::FlexGridGap",
            "Miscellaneous" => "CssCategory::Miscellaneous",
            "MotionPath" => "CssCategory::MotionPath",
            "ScrollDriven" => "CssCategory::ScrollDriven",
            "Houdini" => "CssCategory::Houdini",
            "Svg" => "CssCategory::Svg",
            "Hardware" => "CssCategory::Hardware",
            _ => "CssCategory::Layout",
        };
        code.push_str(&format!(
            "            CssProperty::{} => {},\n",
            prop.rust_name, category_variant
        ));
    }

    code.push_str("        }\n");
    code.push_str("    }\n");
    code.push('\n');

    // Generate is_shorthand method
    code.push_str("    /// Check if this property is a shorthand property.\n");
    code.push_str("    #[inline]\n");
    code.push_str("    pub fn is_shorthand(&self) -> bool {\n");
    code.push_str("        match self {\n");

    for prop in &properties {
        code.push_str(&format!(
            "            CssProperty::{} => {},\n",
            prop.rust_name, prop.shorthand
        ));
    }

    code.push_str("        }\n");
    code.push_str("    }\n");
    code.push('\n');

    // Generate is_experimental method
    code.push_str("    /// Check if this property is experimental/non-standard.\n");
    code.push_str("    #[inline]\n");
    code.push_str("    pub fn is_experimental(&self) -> bool {\n");
    code.push_str("        match self {\n");

    for prop in &properties {
        let is_experimental = prop.status == "experimental";
        code.push_str(&format!(
            "            CssProperty::{} => {},\n",
            prop.rust_name, is_experimental
        ));
    }

    code.push_str("        }\n");
    code.push_str("    }\n");
    code.push('\n');

    // Generate mdn_url method
    code.push_str("    /// Get the MDN documentation URL for this property.\n");
    code.push_str("    #[inline]\n");
    code.push_str("    pub fn mdn_url(&self) -> &'static str {\n");
    code.push_str("        match self {\n");

    for prop in &properties {
        code.push_str(&format!(
            "            CssProperty::{} => \"{}\",\n",
            prop.rust_name, prop.mdn_url
        ));
    }

    code.push_str("        }\n");
    code.push_str("    }\n");

    code.push_str("}\n");
    code.push('\n');

    // Generate Property enum (wrapper for custom properties)
    code.push_str("#[derive(Debug, Clone, PartialEq)]\n");
    code.push_str("pub enum Property {\n");
    code.push_str("    Known(CssProperty),\n");
    code.push_str("    Custom(String),\n");
    code.push_str("}\n");
    code.push('\n');

    // Generate Property impl
    code.push_str("impl Property {\n");
    code.push_str("    /// Get the property name as a string.\n");
    code.push_str("    pub fn as_str(&self) -> &str {\n");
    code.push_str("        match self {\n");
    code.push_str("            Property::Known(prop) => prop.as_str(),\n");
    code.push_str("            Property::Custom(s) => s.as_str(),\n");
    code.push_str("        }\n");
    code.push_str("    }\n");
    code.push('\n');

    code.push_str("    /// Get the category of this property.\n");
    code.push_str("    pub fn category(&self) -> Option<CssCategory> {\n");
    code.push_str("        match self {\n");
    code.push_str("            Property::Known(prop) => Some(prop.category()),\n");
    code.push_str("            Property::Custom(_) => None,\n");
    code.push_str("        }\n");
    code.push_str("    }\n");

    code.push_str("}\n");
    code.push('\n');

    // Generate From implementations
    code.push_str("impl From<CssProperty> for Property {\n");
    code.push_str("    #[inline]\n");
    code.push_str("    fn from(prop: CssProperty) -> Self {\n");
    code.push_str("        Property::Known(prop)\n");
    code.push_str("    }\n");
    code.push_str("}\n");
    code.push('\n');

    code.push_str("impl From<String> for Property {\n");
    code.push_str("    #[inline]\n");
    code.push_str("    fn from(s: String) -> Self {\n");
    code.push_str("        Property::Custom(s)\n");
    code.push_str("    }\n");
    code.push_str("}\n");
    code.push('\n');

    code.push_str("impl From<&str> for Property {\n");
    code.push_str("    #[inline]\n");
    code.push_str("    fn from(s: &str) -> Self {\n");
    code.push_str("        Property::Custom(s.to_string())\n");
    code.push_str("    }\n");
    code.push_str("}\n");
    code.push('\n');

    // Generate Display implementation
    code.push_str("impl std::fmt::Display for CssProperty {\n");
    code.push_str("    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {\n");
    code.push_str("        write!(f, \"{}\", self.as_str())\n");
    code.push_str("    }\n");
    code.push_str("}\n");
    code.push('\n');

    code.push_str("impl std::fmt::Display for Property {\n");
    code.push_str("    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {\n");
    code.push_str("        write!(f, \"{}\", self.as_str())\n");
    code.push_str("    }\n");
    code.push_str("}\n");

    code
}
