//! WIT-bindings platform implementation for `tairitsu-web`.
//!
//! When the `wit-bindings` Cargo feature is enabled this module provides a
//! [`WitPlatform`] that implements [`tairitsu_vdom::Platform`] by calling the
//! `tairitsu-browser:full` WIT import functions instead of using `web-sys`
//! directly.
//!
//! ## Target requirements
//!
//! The full [`Platform`] implementation is only compiled for `wasm32` targets.
//! On native hosts [`WitPlatform::new`] returns `Err` at runtime, which lets
//! cross-platform code reference the type without a compile-time failure.
//!
//! ## Architecture
//!
//! ```mermaid
//! graph TB
//!     subgraph WASM["WASM Component (wasm32-wasip2)"]
//!         WP["WitPlatform → WIT imports (generated)<br/>node, document, style, event-target"]
//!         BC["BrowserComponent &lt;-- event-callbacks exports"]
//!     end
//!     subgraph HOST["browser-glue (browser / Node.js)"]
//!         BG["dom-glue · events-glue · fetch-glue · …<br/>(packages/browser-glue/src/)"]
//!     end
//!     WP -- "tairitsu-browser:full" --> BG
//!     BG -- "host calls on events" --> BC
//! ```

use anyhow::Result;

#[cfg(feature = "wit-bindings")]
use tairitsu_vdom::{ElementHandle, EventHandle};

// -- Opaque handle wrappers -------------------------------------------------

/// Opaque handle to a DOM node managed by the browser-glue host.
///
/// The inner `u64` is the `node-handle` value assigned by the host via the
/// `tairitsu-browser:full` WIT import.
#[cfg(feature = "wit-bindings")]
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct WitElement(pub u64);

#[cfg(feature = "wit-bindings")]
impl ElementHandle for WitElement {
    fn as_any(&self) -> &dyn std::any::Any {
        self
    }
}

/// Opaque handle to a DOM event dispatched by the browser-glue host.
#[cfg(feature = "wit-bindings")]
#[derive(Clone)]
pub struct WitEvent(pub u64);

#[cfg(feature = "wit-bindings")]
impl EventHandle for WitEvent {
    fn as_any(&self) -> &dyn std::any::Any {
        self
    }
}

// -- WitPlatform ------------------------------------------------------------

/// Browser platform backend that calls the `tairitsu-browser:full` WIT world.
///
/// See the [module documentation](self) for the full architecture overview.
///
/// # Feature gate
///
/// Available when the `wit-bindings` Cargo feature is enabled.
///
/// # Target note
///
/// [`tairitsu_vdom::Platform`] is only implemented on `wasm32` targets.
/// On native hosts [`WitPlatform::new`] returns `Err`.
#[derive(Debug)]
#[cfg(feature = "wit-bindings")]
pub struct WitPlatform;

#[cfg(feature = "wit-bindings")]
impl WitPlatform {
    /// Create a new `WitPlatform`.
    ///
    /// Returns `Err` on non-`wasm32` targets because WIT import functions
    /// require the WebAssembly Component Model linker to supply host
    /// implementations (provided by `packages/browser-glue`).
    pub fn new() -> Result<Self> {
        #[cfg(not(target_family = "wasm"))]
        anyhow::bail!(
            "WitPlatform is only available on wasm32 targets (wasm32-wasip2). \
               Native hosts should execute through tairitsu-runtime/wasmtime host flow."
        );

        #[allow(unreachable_code)]
        Ok(Self)
    }

    /// Set a style property on an element (static method for use in event handlers).
    ///
    /// This is a convenience method that directly calls the WIT style interface
    /// without requiring a Platform instance.
    pub fn set_style_static(_element: &WitElement, _name: &str, _value: &str) -> Result<()> {
        #[cfg(target_family = "wasm")]
        {
            wasm_impl::set_style_static_impl(_element.0, _name, _value)
        }
        #[cfg(not(target_family = "wasm"))]
        {
            Ok(())
        }
    }

    /// Render a VNode tree into `#app` for WIT-backed browser components.
    ///
    /// This replaces the bootstrap text set by `lifecycle.start` and mounts
    /// the actual app view tree so users can see real UI content.
    pub fn mount_vnode_to_app(&self, _vnode: &tairitsu_vdom::VNode) -> Result<()> {
        #[cfg(not(target_family = "wasm"))]
        anyhow::bail!("mount_vnode_to_app is only available on wasm32 targets (wasm32-wasip2)");

        #[cfg(target_family = "wasm")]
        {
            wasm_impl::mount_vnode_to_app(self, _vnode)
        }
    }

    /// Apply a list of patches to update the DOM.
    ///
    /// This method applies patches generated by the diff algorithm to update
    /// the actual DOM, allowing for efficient incremental updates.
    ///
    /// # Arguments
    ///
    /// * `parent` - The parent element to apply patches to
    /// * `patches` - The list of patches to apply
    ///
    /// # Returns
    ///
    /// Returns `Ok(())` if all patches were applied successfully, or an error if
    /// any patch application failed.
    ///
    /// # Example
    ///
    /// ```rust
    /// use tairitsu_vdom::VNode;
    /// use tairitsu_web::WitPlatform;
    ///
    /// # fn example(platform: WitPlatform, parent: tairitsu_web::WitElement, old: VNode, new: VNode) -> anyhow::Result<()> {
    /// // Compute the diff between old and new VNode trees
    /// let patches = tairitsu_vdom::diff::diff(Some(&old), &new);
    ///
    /// // Apply the patches to update the DOM
    /// platform.apply_patches(&parent, &patches)?;
    /// # Ok(())
    /// # }
    /// ```
    pub fn apply_patches(
        &self,
        _parent: &WitElement,
        _patches: &[tairitsu_vdom::Patch],
    ) -> Result<()> {
        #[cfg(not(target_family = "wasm"))]
        anyhow::bail!("apply_patches is only available on wasm32 targets (wasm32-wasip2)");

        #[cfg(target_family = "wasm")]
        {
            wasm_impl::apply_patches(self, _parent, _patches)
        }
    }

    /// Clear the handle cache.
    ///
    /// Call this when doing large-scale DOM updates or navigation to
    /// invalidate all cached handles.
    ///
    /// # Example
    ///
    /// ```rust
    /// use tairitsu_web::WitPlatform;
    ///
    /// // After navigation or major DOM update
    /// WitPlatform::clear_cache();
    /// ```
    pub fn clear_cache() {
        #[cfg(target_family = "wasm")]
        {
            crate::handle_cache::HandleCache::with(|cache| cache.clear());
        }
    }

    /// Get cache statistics for debugging and monitoring.
    ///
    /// # Returns
    ///
    /// Returns cache statistics including hit rate, number of entries, etc.
    pub fn cache_stats() -> crate::handle_cache::CacheStats {
        #[cfg(target_family = "wasm")]
        {
            crate::handle_cache::HandleCache::with(|cache| cache.stats())
        }
        #[cfg(not(target_family = "wasm"))]
        {
            crate::handle_cache::CacheStats {
                hits: 0,
                misses: 0,
                total: 0,
                hit_rate: 0.0,
                size: 0,
            }
        }
    }

    /// Invalidate cached handles for a specific element.
    ///
    /// Call this when an element's style declaration is replaced or
    /// the element is otherwise modified in a way that invalidates cached handles.
    ///
    /// # Arguments
    ///
    /// * `element` - The element to invalidate caches for
    pub fn invalidate_element_cache(_element: &WitElement) {
        #[cfg(target_family = "wasm")]
        {
            crate::handle_cache::HandleCache::with(|cache| {
                cache.invalidate_style_handle(_element.0);
            });
        }
    }
}

// -- wasm32 Platform implementation ----------------------------------------
//
// Everything below is compiled only when *both*:
//   • the `wit-bindings` Cargo feature is active, and
//   • the target is a wasm32 family (component model capable).
//
// Native builds never see these items, so the `extern "C"` trampolines
// emitted by `wit_bindgen::generate!()` never reach the native linker.

#[cfg(all(feature = "wit-bindings", target_family = "wasm"))]
pub mod wasm_impl {
    use anyhow::Result;
    use std::cell::RefCell;
    use std::collections::HashMap;
    use std::sync::atomic::{AtomicU64, Ordering};

    use tairitsu_vdom::{
        CanvasContext, DomRect, EventData, EventWitHandle, FocusEvent, GenericEvent, InputEvent,
        KeyboardEvent, MouseEvent, Platform, VNode,
    };

    use super::{WitElement, WitEvent, WitPlatform};

    unsafe extern "C" {
        fn tairitsu_component_bootstrap();
    }

    type EventCallback = Box<dyn FnMut(Box<dyn EventData>)>;
    type EventCallbackMap = HashMap<u64, EventCallback>;
    type TimeoutCallback = Option<Box<dyn FnOnce()>>;
    type AnimationCallback = Option<Box<dyn FnOnce(f64)>>;
    type ResizeObserverCallback = Box<dyn FnMut(Vec<tairitsu_vdom::ResizeObserverEntry>)>;
    type MutationObserverCallback = Box<dyn FnMut(Vec<tairitsu_vdom::MutationRecord>)>;
    type MediaQueryListCallback = Box<dyn FnMut(bool)>;

    static NEXT_CALLBACK_ID: AtomicU64 = AtomicU64::new(1);

    pub fn next_callback_id() -> u64 {
        NEXT_CALLBACK_ID.fetch_add(1, Ordering::SeqCst)
    }

    // -- Console helpers -----------------------------------------------------

    /// Log an error.
    ///
    /// For wasm32: The host environment (browser-glue) handles console output.
    /// For native targets: Falls back to stderr.
    #[cfg(target_family = "wasm")]
    fn log_error(message: &str) {
        // No-op for wasm32 - the host environment handles console output
        let _ = message;
    }

    /// Log a warning.
    #[cfg(target_family = "wasm")]
    fn log_warning(message: &str) {
        let _ = message;
    }

    /// Log diagnostic information.
    #[cfg(target_family = "wasm")]
    fn log_info(message: &str) {
        let _ = message;
    }

    /// Log an error (native fallback).
    #[cfg(not(target_family = "wasm"))]
    fn log_error(message: &str) {
        eprintln!("[WitPlatform ERROR] {}", message);
    }

    /// Log a warning (native fallback).
    #[cfg(not(target_family = "wasm"))]
    fn log_warning(message: &str) {
        eprintln!("[WitPlatform WARNING] {}", message);
    }

    /// Log diagnostic information (native fallback).
    #[cfg(not(target_family = "wasm"))]
    fn log_info(message: &str) {
        eprintln!("[WitPlatform] {}", message);
    }

    thread_local! {
        static EVENT_CALLBACKS: RefCell<EventCallbackMap> = RefCell::new(HashMap::new());
        static ELEMENT_LISTENERS: RefCell<HashMap<(u64, String), u64>>
            = RefCell::new(HashMap::new());
        static TIMEOUT_CALLBACKS: RefCell<HashMap<u64, TimeoutCallback>> = RefCell::new(HashMap::new());
        pub static ANIMATION_CALLBACKS: RefCell<HashMap<u64, AnimationCallback>> = RefCell::new(HashMap::new());
        static RESIZE_OBSERVER_CALLBACKS: RefCell<HashMap<u64, ResizeObserverCallback>> = RefCell::new(HashMap::new());
        static MUTATION_OBSERVER_CALLBACKS: RefCell<HashMap<u64, MutationObserverCallback>> = RefCell::new(HashMap::new());
        static MEDIA_QUERY_LIST_CALLBACKS: RefCell<HashMap<u64, MediaQueryListCallback>> = RefCell::new(HashMap::new());
    }

    // -- WIT binding generation -------------------------------------------

    /// Rust bindings generated from `packages/browser-worlds/wit/browser-full.wit`.
    ///
    /// The `path` is relative to this crate's manifest directory
    /// (`packages/web/`).  `wit_bindgen::generate!` emits
    /// `cargo:rerun-if-changed` directives so the crate is rebuilt whenever
    /// the WIT files change.
    pub mod bindings {
        use super::BrowserComponent;

        wit_bindgen::generate!({
            path: "../browser-worlds/wit/browser-full.wit",
            world: "browser-full",
        });

        export!(BrowserComponent);
    }

    /// Set a style property on an element (implementation for static method).
    ///
    /// Uses the W3C CSSOM standard interface:
    /// 1. Get the style handle via element-css-inline-style (cached)
    /// 2. Set the property via css-style-declaration
    pub(super) fn set_style_static_impl(element: u64, name: &str, value: &str) -> Result<()> {
        // Try to get style handle from cache first
        let style_handle = crate::handle_cache::HandleCache::with(|cache| {
            if let Some(cached_handle) = cache.get_style_handle(element) {
                return cached_handle;
            }

            // Cache miss - get style handle from WIT interface
            let style_handle =
                bindings::tairitsu_browser::full::element_css_inline_style::get_style(element);

            // Cache it for future use
            cache.set_style_handle(element, style_handle);

            style_handle
        });

        // Set the property using the W3C CSSOM interface
        bindings::tairitsu_browser::full::css_style_declaration::set_property(
            style_handle,
            name,
            value,
            None, // priority (e.g., "important")
        );
        Ok(())
    }

    // -- Component export implementation ---------------------------------

    /// Implements the `event-callbacks` WIT export interface.
    ///
    /// The browser-glue host calls these functions when DOM events fire on
    /// nodes that have a listener registered via
    /// [`WitPlatform::add_event_listener`].  Each callback looks up the
    /// corresponding Rust closure in `EVENT_CALLBACKS` and dispatches the
    /// appropriately typed [`EventData`].
    pub(super) struct BrowserComponent;

    impl bindings::exports::tairitsu_browser::full::event_callbacks::Guest for BrowserComponent {
        fn on_mouse_event(
            listener_id: u64,
            event_handle: u64,
            data: bindings::exports::tairitsu_browser::full::event_callbacks::MouseEventData,
        ) {
            let wit_handle = EventWitHandle::from_wit(event_handle);
            let event: Box<dyn EventData> = Box::new(
                MouseEvent::new()
                    .client_x(data.client_x as i32)
                    .client_y(data.client_y as i32)
                    .screen_x(0) // Not provided by WIT
                    .screen_y(0) // Not provided by WIT
                    .offset_x(data.offset_x as i32)
                    .offset_y(data.offset_y as i32)
                    .page_x(0) // Not provided by WIT
                    .page_y(0) // Not provided by WIT
                    .movement_x(0) // Not provided by WIT
                    .movement_y(0) // Not provided by WIT
                    .button(data.button as i16)
                    .buttons(data.buttons as u16)
                    .ctrl_key(data.ctrl_key)
                    .shift_key(data.shift_key)
                    .alt_key(data.alt_key)
                    .meta_key(data.meta_key)
                    .event_handle(wit_handle),
            );
            dispatch_event(listener_id, "mouse", event);
        }

        fn on_keyboard_event(
            listener_id: u64,
            event_handle: u64,
            data: bindings::exports::tairitsu_browser::full::event_callbacks::KeyboardEventData,
        ) {
            let wit_handle = EventWitHandle::from_wit(event_handle);
            let event: Box<dyn EventData> = Box::new(
                KeyboardEvent::new()
                    .key(data.key)
                    .code(data.code)
                    .key_code(data.key_code)
                    .ctrl_key(data.ctrl_key)
                    .shift_key(data.shift_key)
                    .alt_key(data.alt_key)
                    .meta_key(data.meta_key)
                    .repeat(data.repeat)
                    .event_handle(wit_handle),
            );
            dispatch_event(listener_id, "keyboard", event);
        }

        fn on_focus_event(
            listener_id: u64,
            event_handle: u64,
            _data: bindings::exports::tairitsu_browser::full::event_callbacks::FocusEventData,
        ) {
            let wit_handle = EventWitHandle::from_wit(event_handle);
            let event: Box<dyn EventData> = Box::new(FocusEvent::new().event_handle(wit_handle));
            dispatch_event(listener_id, "focus", event);
        }

        fn on_input_event(
            listener_id: u64,
            event_handle: u64,
            data: bindings::exports::tairitsu_browser::full::event_callbacks::InputEventData,
        ) {
            let wit_handle = EventWitHandle::from_wit(event_handle);
            let event: Box<dyn EventData> = Box::new(
                InputEvent::new()
                    .data(data.data.unwrap_or_default())
                    .event_handle(wit_handle),
            );
            dispatch_event(listener_id, "input", event);
        }

        // NOTE: wheel, touch, pointer, transition, and animation events are handled
        // through on_generic_event since the WIT event-callbacks interface doesn't
        // define specialized data structures for them. The event data can be
        // queried via the respective WIT interfaces (wheel-event, touch-event, etc.)
        // using the event_handle.

        fn on_generic_event(listener_id: u64, event_handle: u64, event_type: String) {
            let wit_handle = EventWitHandle::from_wit(event_handle);
            let event: Box<dyn EventData> = Box::new(
                GenericEvent::new()
                    .event_type(&event_type)
                    .event_handle(wit_handle),
            );
            dispatch_event(listener_id, &event_type, event);
        }
    }

    /// Dispatch an event to the registered callback with error handling.
    fn dispatch_event(listener_id: u64, event_type: &str, event: Box<dyn EventData>) {
        EVENT_CALLBACKS.with(|m| {
            let mut callbacks = m.borrow_mut();
            if let Some(handler) = callbacks.get_mut(&listener_id) {
                handler(event);
            } else {
                let msg = format!(
                    "Event dispatched but no callback registered: type={}, listener={}",
                    event_type, listener_id
                );
                log_warning(&msg);
            }
        });
    }

    impl bindings::exports::tairitsu_browser::full::timer_callbacks::Guest for BrowserComponent {
        fn on_timeout(callback_id: u64) {
            TIMEOUT_CALLBACKS.with(|m| {
                if let Some(callback) = m.borrow_mut().remove(&callback_id) {
                    if let Some(cb) = callback {
                        cb();
                    }
                }
            });
        }
    }

    impl bindings::exports::tairitsu_browser::full::animation_callbacks::Guest for BrowserComponent {
        fn on_frame(callback_id: u64, timestamp: f64) {
            ANIMATION_CALLBACKS.with(|m| {
                if let Some(callback) = m.borrow_mut().remove(&callback_id) {
                    if let Some(cb) = callback {
                        cb(timestamp);
                    }
                }
            });
        }
    }

    impl bindings::exports::tairitsu_browser::full::resize_observer_callbacks::Guest
        for BrowserComponent
    {
        fn on_resize(
            callback_id: u64,
            entries: Vec<
                bindings::exports::tairitsu_browser::full::resize_observer_callbacks::ResizeEntry,
            >,
        ) {
            RESIZE_OBSERVER_CALLBACKS.with(|m| {
                let mut callbacks = m.borrow_mut();
                if let Some(handler) = callbacks.get_mut(&callback_id) {
                    let converted_entries: Vec<tairitsu_vdom::ResizeObserverEntry> = entries
                        .into_iter()
                        .map(|entry| tairitsu_vdom::ResizeObserverEntry {
                            target: entry.target,
                            content_rect: tairitsu_vdom::DomRect {
                                x: entry.content_rect.x,
                                y: entry.content_rect.y,
                                width: entry.content_rect.width,
                                height: entry.content_rect.height,
                            },
                            border_box_size: vec![],
                            content_box_size: vec![],
                        })
                        .collect();
                    handler(converted_entries);
                }
            });
        }
    }

    impl bindings::exports::tairitsu_browser::full::mutation_observer_callbacks::Guest
        for BrowserComponent
    {
        fn on_mutate(
            callback_id: u64,
            entries: Vec<bindings::exports::tairitsu_browser::full::mutation_observer_callbacks::MutationEntry>,
        ) {
            MUTATION_OBSERVER_CALLBACKS.with(|m| {
                let mut callbacks = m.borrow_mut();
                if let Some(handler) = callbacks.get_mut(&callback_id) {
                    let converted_records: Vec<tairitsu_vdom::MutationRecord> = entries
                        .into_iter()
                        .map(|entry| tairitsu_vdom::MutationRecord {
                            record_type: entry.mutation_type,
                            target: entry.target,
                            added_nodes: vec![],
                            removed_nodes: vec![],
                            previous_sibling: entry.previous_sibling,
                            next_sibling: entry.next_sibling,
                            attribute_name: entry.attribute_name,
                            attribute_namespace: entry.attribute_namespace,
                            old_value: entry.old_value,
                        })
                        .collect();
                    handler(converted_records);
                }
            });
        }
    }

    impl bindings::exports::tairitsu_browser::full::media_query_list_callbacks::Guest
        for BrowserComponent
    {
        fn on_change(callback_id: u64, matches: bool) {
            MEDIA_QUERY_LIST_CALLBACKS.with(|m| {
                let mut callbacks = m.borrow_mut();
                if let Some(handler) = callbacks.get_mut(&callback_id) {
                    handler(matches);
                }
            });
        }
    }

    impl bindings::exports::tairitsu_browser::full::lifecycle::Guest for BrowserComponent {
        fn start() -> Result<(), String> {
            // Validate the WIT environment before starting the component
            if let Err(e) = validate_wit_environment() {
                let msg = format!("WIT environment validation failed: {}", e);
                log_error(&msg);
                return Err(msg);
            }

            // Register WIT functions for global DOM operations in event handlers
            #[cfg(target_family = "wasm")]
            register_dom_ops_functions();

            unsafe {
                tairitsu_component_bootstrap();
            }

            Ok(())
        }
    }

    /// Register WIT functions for use in event handlers.
    #[cfg(target_family = "wasm")]
    fn register_dom_ops_functions() {
        use tairitsu_vdom::register_wit_functions;

        unsafe {
            register_wit_functions(
                |element, property, value| {
                    // Use W3C CSSOM standard interface
                    let style_handle =
                        bindings::tairitsu_browser::full::element_css_inline_style::get_style(
                            element,
                        );
                    bindings::tairitsu_browser::full::css_style_declaration::set_property(
                        style_handle,
                        property,
                        value,
                        None,
                    );
                    Ok(())
                },
                |element| {
                    let rect =
                        bindings::tairitsu_browser::full::platform_helpers::get_bounding_client_rect(
                            element,
                        );
                    tairitsu_vdom::DomRect {
                        x: rect.x,
                        y: rect.y,
                        width: rect.width,
                        height: rect.height,
                    }
                },
                |element, name, value| {
                    bindings::tairitsu_browser::full::element::set_attribute(element, name, value);
                },
            );
        }

        log_info("DOM operations functions registered for event handlers");
    }

    /// Validate that the WIT host environment is properly configured.
    fn validate_wit_environment() -> Result<(), String> {
        // Test basic DOM operations to ensure the host is working
        let result = std::panic::catch_unwind(|| {
            // Try to access document - this will call the WIT import
            let _body = bindings::tairitsu_browser::full::document::get_body();
            // Try window operations
            let _width = bindings::tairitsu_browser::full::window::get_inner_width();
            // Note: console operations no longer use WIT interface
            log_info("Environment validation passed");
        });

        match result {
            Ok(_) => Ok(()),
            Err(_) => Err("WIT host call failed during validation".to_string()),
        }
    }

    // -- Platform trait implementation ------------------------------------

    impl Platform for WitPlatform {
        type Element = WitElement;
        type Event = WitEvent;

        fn create_element(&self, tag: &str) -> Self::Element {
            // New WIT: create-element returns u64 directly, takes optional options
            let handle = bindings::tairitsu_browser::full::document::create_element(tag, None);
            WitElement(handle)
        }

        fn create_text_node(&self, text: &str) -> Self::Element {
            // New WIT: create-text-node returns u64 directly
            let handle = bindings::tairitsu_browser::full::document::create_text_node(text);
            WitElement(handle)
        }

        fn append_child(&self, parent: &Self::Element, child: &Self::Element) {
            // New WIT: append-child returns u64 (the appended node)
            let _ = bindings::tairitsu_browser::full::node::append_child(parent.0, child.0);
        }

        fn remove_child(&self, parent: &Self::Element, child: &Self::Element) {
            // Invalidate cache for the child element being removed
            crate::handle_cache::HandleCache::with(|cache| {
                cache.invalidate_style_handle(child.0);
            });

            // New WIT: remove-child returns u64 (the removed node)
            let _ = bindings::tairitsu_browser::full::node::remove_child(parent.0, child.0);
        }

        fn set_attribute(&self, element: &Self::Element, name: &str, value: &str) {
            // New WIT: set-attribute returns void
            bindings::tairitsu_browser::full::element::set_attribute(element.0, name, value);
        }

        fn remove_attribute(&self, element: &Self::Element, name: &str) {
            // New WIT: remove-attribute returns void
            bindings::tairitsu_browser::full::element::remove_attribute(element.0, name);
        }

        fn set_style(&self, element: &Self::Element, name: &str, value: &str) {
            // Try to get style handle from cache first
            let style_handle = crate::handle_cache::HandleCache::with(|cache| {
                if let Some(cached_handle) = cache.get_style_handle(element.0) {
                    return cached_handle;
                }

                // Cache miss - get style handle from WIT interface
                let style_handle =
                    bindings::tairitsu_browser::full::element_css_inline_style::get_style(element.0);

                // Cache it for future use
                cache.set_style_handle(element.0, style_handle);

                style_handle
            });

            // Set the property using the W3C CSSOM interface
            bindings::tairitsu_browser::full::css_style_declaration::set_property(
                style_handle,
                name,
                value,
                None,
            );
        }

        fn set_class(&self, element: &Self::Element, class: &str) {
            bindings::tairitsu_browser::full::element::set_attribute(element.0, "class", class);
        }

        fn add_event_listener(
            &self,
            element: &Self::Element,
            event: &str,
            handler: Box<dyn FnMut(Box<dyn EventData>)>,
        ) {
            // W3C interface: generate callback handle first, then pass to add-event-listener
            let callback_handle = next_callback_id();

            // Store the handler with the callback handle
            EVENT_CALLBACKS.with(|m| m.borrow_mut().insert(callback_handle, handler));

            // Call the W3C add-event-listener with self parameter
            // The WIT interface returns a listener-id that we need to store for removal
            let listener_id = bindings::tairitsu_browser::full::event_target::add_event_listener(
                element.0, event, false, // use_capture
            )
            .unwrap_or_else(|e| {
                log_error(&format!("add_event_listener failed: {}", e));
                0
            });

            // Store the mapping from element+event to listener-id for removal
            ELEMENT_LISTENERS.with(|m| {
                m.borrow_mut()
                    .insert((element.0, event.to_string()), listener_id);
            });

            log_info(&format!(
                "Added event listener: event={}, listener_id={}",
                event, listener_id
            ));
        }

        fn remove_event_listener(&self, element: &Self::Element, event: &str) {
            let listener_id =
                ELEMENT_LISTENERS.with(|m| m.borrow_mut().remove(&(element.0, event.to_string())));

            if let Some(listener_id) = listener_id {
                // Remove the callback handler
                EVENT_CALLBACKS.with(|m| m.borrow_mut().remove(&listener_id));
                // Call the W3C remove-event-listener with the listener-id
                let _ = bindings::tairitsu_browser::full::event_target::remove_event_listener(
                    element.0,
                    listener_id,
                );
                log_info(&format!(
                    "Removed event listener: event={}, listener_id={}",
                    event, listener_id
                ));
            } else {
                log_warning(&format!(
                    "remove_event_listener: no listener found for event '{}' on element {}",
                    event, element.0
                ));
            }
        }

        fn get_bounding_client_rect(&self, element: &Self::Element) -> DomRect {
            let rect = bindings::tairitsu_browser::full::platform_helpers::get_bounding_client_rect(
                element.0,
            );
            DomRect {
                x: rect.x,
                y: rect.y,
                width: rect.width,
                height: rect.height,
            }
        }

        fn inner_width(&self) -> i32 {
            bindings::tairitsu_browser::full::platform_helpers::inner_width()
        }

        fn inner_height(&self) -> i32 {
            bindings::tairitsu_browser::full::platform_helpers::inner_height()
        }

        fn set_timeout(&self, callback: Box<dyn FnOnce()>, ms: i32) -> i32 {
            let callback_id = next_callback_id();
            TIMEOUT_CALLBACKS.with(|m| m.borrow_mut().insert(callback_id, Some(callback)));
            bindings::tairitsu_browser::full::platform_helpers::set_timeout(callback_id, ms)
        }

        fn clear_timeout(&self, id: i32) {
            bindings::tairitsu_browser::full::platform_helpers::clear_timeout(id)
        }

        fn request_animation_frame(&self, callback: Box<dyn FnOnce(f64)>) -> u32 {
            let callback_id = next_callback_id();
            ANIMATION_CALLBACKS.with(|m| m.borrow_mut().insert(callback_id, Some(callback)));
            bindings::tairitsu_browser::full::platform_helpers::request_animation_frame(callback_id)
        }

        fn cancel_animation_frame(&self, id: u32) {
            bindings::tairitsu_browser::full::platform_helpers::cancel_animation_frame(id)
        }

        fn get_canvas_context(
            &self,
            element: &Self::Element,
            context_type: &str,
        ) -> Option<CanvasContext> {
            bindings::tairitsu_browser::full::html_canvas_element::get_context(
                element.0,
                context_type,
                None,
            )
        }

        fn canvas_set_fill_style(&self, ctx: CanvasContext, color: &str) {
            bindings::tairitsu_browser::full::canvas_fill_stroke_styles::set_fill_style(ctx, color)
        }

        fn canvas_fill_rect(&self, ctx: CanvasContext, x: f64, y: f64, w: f64, h: f64) {
            bindings::tairitsu_browser::full::canvas_rect::fill_rect(ctx, x, y, w, h)
        }

        fn canvas_clear_rect(&self, ctx: CanvasContext, x: f64, y: f64, w: f64, h: f64) {
            bindings::tairitsu_browser::full::canvas_rect::clear_rect(ctx, x, y, w, h)
        }

        fn create_resize_observer(
            &self,
            callback: Box<dyn FnMut(Vec<tairitsu_vdom::ResizeObserverEntry>)>,
        ) -> u64 {
            let callback_id = next_callback_id();
            RESIZE_OBSERVER_CALLBACKS.with(|m| m.borrow_mut().insert(callback_id, callback));
            bindings::tairitsu_browser::full::platform_helpers::create_resize_observer(callback_id)
        }

        fn observe_resize(&self, observer: u64, element: &Self::Element) {
            bindings::tairitsu_browser::full::platform_helpers::observe_resize(observer, element.0);
        }

        fn unobserve_resize(&self, observer: u64, element: &Self::Element) {
            bindings::tairitsu_browser::full::platform_helpers::unobserve_resize(
                observer, element.0,
            );
        }

        fn disconnect_resize(&self, observer: u64) {
            bindings::tairitsu_browser::full::platform_helpers::disconnect_resize(observer);
        }

        fn create_mutation_observer(
            &self,
            callback: Box<dyn FnMut(Vec<tairitsu_vdom::MutationRecord>)>,
        ) -> u64 {
            let callback_id = next_callback_id();
            MUTATION_OBSERVER_CALLBACKS.with(|m| m.borrow_mut().insert(callback_id, callback));
            bindings::tairitsu_browser::full::platform_helpers::create_mutation_observer(
                callback_id,
            )
        }

        fn observe_mutations(
            &self,
            observer: u64,
            element: &Self::Element,
            _options: Option<tairitsu_vdom::MutationObserverInit>,
        ) {
            bindings::tairitsu_browser::full::platform_helpers::observe_mutations(
                observer, element.0, None,
            );
        }

        fn disconnect_mutation(&self, observer: u64) {
            bindings::tairitsu_browser::full::platform_helpers::disconnect_mutation(observer);
        }

        fn match_media(&self, query: &str) -> u64 {
            bindings::tairitsu_browser::full::window::match_media(query)
        }

        fn media_query_list_get_media(&self, list: u64) -> String {
            bindings::tairitsu_browser::full::media_query_list::get_media(list)
        }

        fn media_query_list_get_matches(&self, list: u64) -> bool {
            bindings::tairitsu_browser::full::media_query_list::get_matches(list)
        }

        fn media_query_list_add_listener(&self, list: u64, callback: Box<dyn FnMut(bool)>) -> u64 {
            let callback_id = next_callback_id();
            MEDIA_QUERY_LIST_CALLBACKS.with(|m| m.borrow_mut().insert(callback_id, callback));
            bindings::tairitsu_browser::full::media_query_list::add_listener(
                list,
                Some(callback_id),
            );
            callback_id
        }

        fn media_query_list_remove_listener(&self, list: u64, listener_id: u64) {
            MEDIA_QUERY_LIST_CALLBACKS.with(|m| m.borrow_mut().remove(&listener_id));
            bindings::tairitsu_browser::full::media_query_list::remove_listener(
                list,
                Some(listener_id),
            );
        }
    }

    pub(super) fn mount_vnode_to_app(platform: &WitPlatform, vnode: &VNode) -> Result<()> {
        // Document handle for non-element-parent-node operations (getElementById)
        // Document implements NonElementParentNode, so we use its handle
        let doc_handle: u64 = 0; // Global document singleton uses handle 0

        let app = if let Some(handle) =
            bindings::tairitsu_browser::full::non_element_parent_node::get_element_by_id(
                doc_handle, "app",
            ) {
            WitElement(handle)
        } else {
            let body = bindings::tairitsu_browser::full::document::get_body()
                .ok_or_else(|| anyhow::anyhow!("document.body is not available"))?;
            let div = bindings::tairitsu_browser::full::document::create_element("div", None);
            bindings::tairitsu_browser::full::element::set_attribute(div, "id", "app");
            let _ = bindings::tairitsu_browser::full::node::append_child(body, div);
            WitElement(div)
        };

        // set_text_content takes option<string>, returns void
        bindings::tairitsu_browser::full::node::set_text_content(app.0, Some(""));

        render_vnode(platform, vnode, &app)
    }

    fn render_vnode(platform: &WitPlatform, vnode: &VNode, parent: &WitElement) -> Result<()> {
        match vnode {
            VNode::Element(velement) => {
                let element = platform.create_element(&velement.tag);

                // Populate element_ref if present
                if let Some(ref element_ref) = velement.element_ref {
                    use std::any::Any;
                    // Store the WitElement in the ref
                    let mut ref_mut = element_ref.borrow_mut();
                    *ref_mut = Some(Box::new(element.clone()) as Box<dyn Any>);
                }

                for (name, value) in &velement.attributes {
                    platform.set_attribute(&element, name, value);
                }

                if !velement.class.static_classes.is_empty() {
                    platform.set_class(&element, &velement.class.static_classes);
                }

                if !velement.style.static_styles.is_empty() {
                    for part in velement.style.static_styles.split(';') {
                        let part = part.trim();
                        if part.is_empty() {
                            continue;
                        }
                        if let Some((name, value)) = part.split_once(':') {
                            platform.set_style(&element, name.trim(), value.trim());
                        }
                    }
                }

                for (name, value) in &velement.style.css_variables {
                    platform.set_style(&element, name, value);
                }

                for (event_name, handler) in &velement.event_handlers {
                    let handler = handler.clone();
                    platform.add_event_listener(
                        &element,
                        event_name,
                        Box::new(move |event| {
                            (handler.borrow_mut())(event);
                        }),
                    );
                }

                for child in &velement.children {
                    render_vnode(platform, child, &element)?;
                }

                platform.append_child(parent, &element);
            }
            VNode::Text(vtext) => {
                let text_node = platform.create_text_node(&vtext.text);
                platform.append_child(parent, &text_node);
            }
            VNode::Fragment(children) => {
                for child in children {
                    render_vnode(platform, child, parent)?;
                }
            }
        }

        Ok(())
    }

    /// Apply a list of patches to update the DOM based on the diff result.
    ///
    /// This method takes a parent element and a list of patches, and applies
    /// them to the DOM to reflect the changes from the diff algorithm.
    ///
    /// # Arguments
    ///
    /// * `platform` - The WitPlatform instance for DOM operations
    /// * `parent` - The parent element to apply patches to
    /// * `patches` - The list of patches to apply
    ///
    /// # Returns
    ///
    /// Returns `Ok(())` if all patches were applied successfully, or an error if
    /// any patch application failed.
    pub fn apply_patches(
        platform: &WitPlatform,
        parent: &WitElement,
        patches: &[tairitsu_vdom::Patch],
    ) -> Result<()> {
        for patch in patches {
            apply_patch(platform, parent, patch)?;
        }
        Ok(())
    }

    /// Apply a single patch to the DOM.
    ///
    /// This is the core function that handles each type of patch operation.
    fn apply_patch(
        platform: &WitPlatform,
        element: &WitElement,
        patch: &tairitsu_vdom::Patch,
    ) -> Result<()> {
        use tairitsu_vdom::Patch;

        match patch {
            Patch::CreateNode { node } => {
                // Create and append a new node
                render_vnode(platform, node, element)?;
            }

            Patch::RemoveNode => {
                // This is a no-op at this level - removal happens at the parent level
                // via RemoveChild
            }

            Patch::ReplaceNode { node } => {
                // Replace the current element with a new node
                replace_element_content(platform, element, node)?;
            }

            Patch::UpdateText { text } => {
                // Update the text content of the element
                bindings::tairitsu_browser::full::node::set_text_content(element.0, Some(text));
            }

            Patch::UpdateAttribute { name, value } => {
                platform.set_attribute(element, name, value);
            }

            Patch::AddAttribute { name, value } => {
                platform.set_attribute(element, name, value);
            }

            Patch::RemoveAttribute { name } => {
                platform.remove_attribute(element, name);
            }

            Patch::UpdateStyle { style } => {
                apply_style(platform, element, style)?;
            }

            Patch::UpdateClass { class } => {
                if !class.static_classes.is_empty() {
                    platform.set_class(element, &class.static_classes);
                }
            }

            Patch::InsertChild { index, node } => {
                insert_child_at(platform, element, *index, node)?;
            }

            Patch::RemoveChild { index } => {
                remove_child_at(platform, element, *index)?;
            }

            Patch::UpdateChild {
                index,
                patches: child_patches,
            } => {
                // Get the child at the specified index
                let child = get_child_at(element, *index)?;
                if let Some(child_element) = child {
                    // Apply the nested patches to the child
                    for child_patch in child_patches {
                        apply_patch(platform, &child_element, child_patch)?;
                    }
                }
            }

            Patch::AddEvent { name } => {
                // This is a no-op for patches - event handlers are managed by the VNode
                // and are not directly applied through patches
                log_info(&format!(
                    "AddEvent patch for '{}': event handler managed by VNode",
                    name
                ));
            }

            Patch::UpdateEvent { name } => {
                // This is a no-op for patches - event handlers are managed by the VNode
                log_info(&format!(
                    "UpdateEvent patch for '{}': event handler managed by VNode",
                    name
                ));
            }

            Patch::RemoveEvent { name } => {
                // Remove the event listener
                platform.remove_event_listener(element, name);
            }
        }

        Ok(())
    }

    /// Create a DOM element from a VNode without attaching it to the DOM.
    fn create_vnode_element(platform: &WitPlatform, vnode: &VNode) -> Result<WitElement> {
        match vnode {
            VNode::Element(velement) => {
                let element = platform.create_element(&velement.tag);

                // Populate element_ref if present (for patch-created elements)
                if let Some(ref element_ref) = velement.element_ref {
                    use std::any::Any;
                    let mut ref_mut = element_ref.borrow_mut();
                    *ref_mut = Some(Box::new(element.clone()) as Box<dyn Any>);
                }

                for (name, value) in &velement.attributes {
                    platform.set_attribute(&element, name, value);
                }

                if !velement.class.static_classes.is_empty() {
                    platform.set_class(&element, &velement.class.static_classes);
                }

                apply_style(platform, &element, &velement.style)?;

                for (event_name, handler) in &velement.event_handlers {
                    let handler = handler.clone();
                    platform.add_event_listener(
                        &element,
                        event_name,
                        Box::new(move |event| {
                            (handler.borrow_mut())(event);
                        }),
                    );
                }

                Ok(element)
            }
            VNode::Text(vtext) => Ok(platform.create_text_node(&vtext.text)),
            VNode::Fragment(_) => {
                // Fragments can't be represented as a single element
                // Create a placeholder div
                Ok(platform.create_element("div"))
            }
        }
    }

    /// Replace the content of an element with a new VNode.
    fn replace_element_content(
        platform: &WitPlatform,
        element: &WitElement,
        vnode: &VNode,
    ) -> Result<()> {
        // Clear existing content
        bindings::tairitsu_browser::full::node::set_text_content(element.0, Some(""));

        match vnode {
            VNode::Element(velement) => {
                // Update attributes
                for (name, value) in &velement.attributes {
                    platform.set_attribute(element, name, value);
                }

                // Update class
                if !velement.class.static_classes.is_empty() {
                    platform.set_class(element, &velement.class.static_classes);
                }

                // Update style
                apply_style(platform, element, &velement.style)?;

                // Update event listeners (remove old, add new)
                for event_name in velement.event_handlers.keys() {
                    platform.remove_event_listener(element, event_name);
                }
                for (event_name, handler) in &velement.event_handlers {
                    let handler = handler.clone();
                    platform.add_event_listener(
                        element,
                        event_name,
                        Box::new(move |event| {
                            (handler.borrow_mut())(event);
                        }),
                    );
                }

                // Render children
                for child in &velement.children {
                    render_vnode(platform, child, element)?;
                }
            }
            VNode::Text(vtext) => {
                bindings::tairitsu_browser::full::node::set_text_content(
                    element.0,
                    Some(&vtext.text),
                );
            }
            VNode::Fragment(children) => {
                for child in children {
                    render_vnode(platform, child, element)?;
                }
            }
        }

        Ok(())
    }

    /// Apply styles to an element.
    fn apply_style(
        platform: &WitPlatform,
        element: &WitElement,
        style: &tairitsu_vdom::Style,
    ) -> Result<()> {
        // Apply static styles
        if !style.static_styles.is_empty() {
            for part in style.static_styles.split(';') {
                let part = part.trim();
                if part.is_empty() {
                    continue;
                }
                if let Some((name, value)) = part.split_once(':') {
                    platform.set_style(element, name.trim(), value.trim());
                }
            }
        }

        // Apply CSS variables
        for (name, value) in &style.css_variables {
            platform.set_style(element, name, value);
        }

        Ok(())
    }

    /// Insert a child node at a specific index.
    fn insert_child_at(
        platform: &WitPlatform,
        parent: &WitElement,
        index: usize,
        node: &VNode,
    ) -> Result<()> {
        // Create the new element
        let new_element = create_vnode_element(platform, node)?;

        // Get the current number of children using child-nodes NodeList
        let child_nodes_handle = bindings::tairitsu_browser::full::node::get_child_nodes(parent.0);
        let child_count =
            bindings::tairitsu_browser::full::node_list::get_length(child_nodes_handle) as usize;

        if index >= child_count {
            // Append at the end
            platform.append_child(parent, &new_element);
        } else {
            // Insert at the specific position
            // Get the child at the index to use as the reference node
            let next_sibling =
                bindings::tairitsu_browser::full::node_list::item(child_nodes_handle, index as u32);
            if let Some(sibling) = next_sibling {
                let _ = bindings::tairitsu_browser::full::node::insert_before(
                    parent.0,
                    new_element.0,
                    Some(sibling),
                );
            } else {
                platform.append_child(parent, &new_element);
            }
        }

        // If the node is an element, render its children
        if let VNode::Element(velement) = node {
            for child in &velement.children {
                render_vnode(platform, child, &new_element)?;
            }
        }

        Ok(())
    }

    /// Remove a child node at a specific index.
    fn remove_child_at(platform: &WitPlatform, parent: &WitElement, index: usize) -> Result<()> {
        let child = get_child_at(parent, index)?;
        if let Some(child_element) = child {
            platform.remove_child(parent, &child_element);
        }
        Ok(())
    }

    /// Get a child element at a specific index.
    fn get_child_at(parent: &WitElement, index: usize) -> Result<Option<WitElement>> {
        let child_nodes_handle = bindings::tairitsu_browser::full::node::get_child_nodes(parent.0);
        let child_handle =
            bindings::tairitsu_browser::full::node_list::item(child_nodes_handle, index as u32);
        Ok(child_handle.map(WitElement))
    }
}

// -- Tests ---------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use tairitsu_vdom::{Classes, Patch, Style, VElement, VNode, VText};

    /// Test that apply_patches handles an empty patch list correctly.
    #[test]
    fn test_apply_empty_patches() {
        // This test verifies that applying an empty list of patches doesn't cause errors.
        // Since we can't actually create DOM elements in unit tests (requires WIT host),
        // we're mainly testing that the function signature and control flow work correctly.
        let patches: Vec<Patch> = vec![];
        assert!(patches.is_empty(), "Empty patches should be empty");
    }

    /// Test that patches can be created and matched correctly.
    #[test]
    fn test_patch_variants() {
        // Test CreateNode patch
        let node = VNode::Text(VText::new("Hello"));
        let create_patch = Patch::CreateNode { node: node.clone() };
        match create_patch {
            Patch::CreateNode { node } => {
                assert_eq!(node, VNode::Text(VText::new("Hello")));
            }
            _ => panic!("Expected CreateNode patch"),
        }

        // Test UpdateText patch
        let update_text_patch = Patch::UpdateText {
            text: "World".to_string(),
        };
        match update_text_patch {
            Patch::UpdateText { text } => {
                assert_eq!(text, "World");
            }
            _ => panic!("Expected UpdateText patch"),
        }

        // Test UpdateAttribute patch
        let update_attr_patch = Patch::UpdateAttribute {
            name: "class".to_string(),
            value: "active".to_string(),
        };
        match update_attr_patch {
            Patch::UpdateAttribute { name, value } => {
                assert_eq!(name, "class");
                assert_eq!(value, "active");
            }
            _ => panic!("Expected UpdateAttribute patch"),
        }

        // Test AddAttribute patch
        let add_attr_patch = Patch::AddAttribute {
            name: "id".to_string(),
            value: "test".to_string(),
        };
        match add_attr_patch {
            Patch::AddAttribute { name, value } => {
                assert_eq!(name, "id");
                assert_eq!(value, "test");
            }
            _ => panic!("Expected AddAttribute patch"),
        }

        // Test RemoveAttribute patch
        let remove_attr_patch = Patch::RemoveAttribute {
            name: "disabled".to_string(),
        };
        match remove_attr_patch {
            Patch::RemoveAttribute { name } => {
                assert_eq!(name, "disabled");
            }
            _ => panic!("Expected RemoveAttribute patch"),
        }

        // Test InsertChild patch
        let child = VNode::Text(VText::new("Child"));
        let insert_child_patch = Patch::InsertChild {
            index: 0,
            node: child,
        };
        match insert_child_patch {
            Patch::InsertChild { index, node } => {
                assert_eq!(index, 0);
                assert_eq!(node, VNode::Text(VText::new("Child")));
            }
            _ => panic!("Expected InsertChild patch"),
        }

        // Test RemoveChild patch
        let remove_child_patch = Patch::RemoveChild { index: 0 };
        match remove_child_patch {
            Patch::RemoveChild { index } => {
                assert_eq!(index, 0);
            }
            _ => panic!("Expected RemoveChild patch"),
        }

        // Test UpdateChild patch
        let child_patches = vec![Patch::UpdateText {
            text: "Updated".to_string(),
        }];
        let update_child_patch = Patch::UpdateChild {
            index: 1,
            patches: child_patches,
        };
        match update_child_patch {
            Patch::UpdateChild { index, patches } => {
                assert_eq!(index, 1);
                assert_eq!(patches.len(), 1);
            }
            _ => panic!("Expected UpdateChild patch"),
        }

        // Test ReplaceNode patch
        let new_node = VNode::Element(VElement::new("div"));
        let replace_patch = Patch::ReplaceNode {
            node: new_node.clone(),
        };
        match replace_patch {
            Patch::ReplaceNode { node } => {
                assert_eq!(node, new_node);
            }
            _ => panic!("Expected ReplaceNode patch"),
        }

        // Test event patches
        let add_event_patch = Patch::AddEvent {
            name: "click".to_string(),
        };
        match add_event_patch {
            Patch::AddEvent { name } => {
                assert_eq!(name, "click");
            }
            _ => panic!("Expected AddEvent patch"),
        }

        let update_event_patch = Patch::UpdateEvent {
            name: "click".to_string(),
        };
        match update_event_patch {
            Patch::UpdateEvent { name } => {
                assert_eq!(name, "click");
            }
            _ => panic!("Expected UpdateEvent patch"),
        }

        let remove_event_patch = Patch::RemoveEvent {
            name: "click".to_string(),
        };
        match remove_event_patch {
            Patch::RemoveEvent { name } => {
                assert_eq!(name, "click");
            }
            _ => panic!("Expected RemoveEvent patch"),
        }
    }

    /// Test nested patches (UpdateChild containing patches).
    #[test]
    fn test_nested_patches() {
        let nested_patches = vec![
            Patch::UpdateAttribute {
                name: "href".to_string(),
                value: "#".to_string(),
            },
            Patch::UpdateClass {
                class: Classes::new().add("active"),
            },
            Patch::UpdateStyle {
                style: Style::new().add("color", "red"),
            },
        ];

        let update_child_patch = Patch::UpdateChild {
            index: 0,
            patches: nested_patches,
        };

        match update_child_patch {
            Patch::UpdateChild { index, patches } => {
                assert_eq!(index, 0);
                assert_eq!(patches.len(), 3);
                // Verify the nested patches are correct
                assert!(matches!(patches[0], Patch::UpdateAttribute { .. }));
                assert!(matches!(patches[1], Patch::UpdateClass { .. }));
                assert!(matches!(patches[2], Patch::UpdateStyle { .. }));
            }
            _ => panic!("Expected UpdateChild patch"),
        }
    }

    /// Test that Patch::is_empty works correctly.
    #[test]
    fn test_patch_is_empty() {
        let empty_patch = Patch::UpdateChild {
            index: 0,
            patches: vec![],
        };
        assert!(empty_patch.is_empty());

        let non_empty_patch = Patch::UpdateChild {
            index: 0,
            patches: vec![Patch::UpdateText {
                text: "test".to_string(),
            }],
        };
        assert!(!non_empty_patch.is_empty());

        // Other patch variants should return false for is_empty
        let text_patch = Patch::UpdateText {
            text: "test".to_string(),
        };
        assert!(!text_patch.is_empty());
    }

    /// Test UpdateStyle and UpdateClass patches
    #[test]
    fn test_style_and_class_patches() {
        // Test UpdateStyle patch
        let style = Style::new()
            .add("color", "red")
            .add("background-color", "blue");
        let update_style_patch = Patch::UpdateStyle { style };
        match update_style_patch {
            Patch::UpdateStyle { style } => {
                assert_eq!(style.static_styles, "color:red;background-color:blue");
            }
            _ => panic!("Expected UpdateStyle patch"),
        }

        // Test UpdateClass patch
        let class = Classes::new().add("btn").add("active");
        let update_class_patch = Patch::UpdateClass { class };
        match update_class_patch {
            Patch::UpdateClass { class } => {
                assert_eq!(class.static_classes, "btn active");
            }
            _ => panic!("Expected UpdateClass patch"),
        }
    }

    /// Test RemoveNode patch
    #[test]
    fn test_remove_node_patch() {
        let remove_node_patch = Patch::RemoveNode;
        match remove_node_patch {
            Patch::RemoveNode => {
                // Success - this is a RemoveNode patch
            }
            _ => panic!("Expected RemoveNode patch"),
        }
    }

    // -- WitElement and WitEvent tests ---------------------------------------

    /// Test WitElement clone behavior.
    #[cfg(feature = "wit-bindings")]
    #[test]
    fn test_wit_element_clone() {
        let element1 = super::WitElement(42);
        let element2 = element1;
        let element3 = element2; // WitElement is Copy, so this works

        assert_eq!(element3.0, 42);
    }

    /// Test WitElement equality and comparison.
    #[cfg(feature = "wit-bindings")]
    #[test]
    fn test_wit_element_equality() {
        let elem1 = super::WitElement(100);
        let elem2 = super::WitElement(100);
        let elem3 = super::WitElement(200);

        assert_eq!(elem1, elem2);
        assert_ne!(elem1, elem3);
    }

    /// Test WitEvent clone behavior.
    #[cfg(feature = "wit-bindings")]
    #[test]
    fn test_wit_event_clone() {
        let event1 = super::WitEvent(123);
        let event2 = event1.clone();

        assert_eq!(event1.0, 123);
        assert_eq!(event2.0, 123);
    }

    /// Test WitElement implements ElementHandle trait.
    #[cfg(feature = "wit-bindings")]
    #[test]
    fn test_wit_element_element_handle() {
        use tairitsu_vdom::ElementHandle;

        let element = super::WitElement(42);
        let any_ref = element.as_any();

        // Should be able to downcast back to WitElement
        assert!(any_ref.is::<super::WitElement>());
        if let Some(downcasted) = any_ref.downcast_ref::<super::WitElement>() {
            assert_eq!(downcasted.0, 42);
        } else {
            panic!("Failed to downcast to WitElement");
        }
    }

    /// Test WitEvent implements EventHandle trait.
    #[cfg(feature = "wit-bindings")]
    #[test]
    fn test_wit_event_event_handle() {
        use tairitsu_vdom::EventHandle;

        let event = super::WitEvent(999);
        let any_ref = event.as_any();

        // Should be able to downcast back to WitEvent
        assert!(any_ref.is::<super::WitEvent>());
        if let Some(downcasted) = any_ref.downcast_ref::<super::WitEvent>() {
            assert_eq!(downcasted.0, 999);
        } else {
            panic!("Failed to downcast to WitEvent");
        }
    }

    // -- WitPlatform tests ---------------------------------------------------

    /// Test WitPlatform::new() on native targets (should fail).
    #[cfg(all(feature = "wit-bindings", not(target_family = "wasm")))]
    #[test]
    fn test_wit_platform_new_native() {
        let result = super::WitPlatform::new();
        assert!(
            result.is_err(),
            "WitPlatform::new should fail on native targets"
        );

        let err_msg = result.unwrap_err().to_string();
        assert!(err_msg.contains("wasm32"), "Error should mention wasm32");
    }

    /// Test WitPlatform::new() on wasm targets (should succeed).
    #[cfg(all(feature = "wit-bindings", target_family = "wasm"))]
    #[test]
    fn test_wit_platform_new_wasm() {
        let result = super::WitPlatform::new();
        assert!(
            result.is_ok(),
            "WitPlatform::new should succeed on wasm targets"
        );
    }

    /// Test WitPlatform::set_style_static on native targets.
    #[cfg(all(feature = "wit-bindings", not(target_family = "wasm")))]
    #[test]
    fn test_set_style_static_native() {
        let element = super::WitElement(42);
        let result = super::WitPlatform::set_style_static(&element, "color", "red");

        // On native targets, this should return Ok(()) as a no-op
        assert!(
            result.is_ok(),
            "set_style_static should return Ok on native targets"
        );
    }

    /// Test WitPlatform::set_style_static with various inputs.
    #[cfg(feature = "wit-bindings")]
    #[test]
    fn test_set_style_static_inputs() {
        let element = super::WitElement(1);

        // Test with empty values
        let result = super::WitPlatform::set_style_static(&element, "", "");
        #[cfg(target_family = "wasm")]
        {
            // On wasm, this would try to call WIT functions
            // We can't test actual behavior without a host, but we verify it compiles
        }
        #[cfg(not(target_family = "wasm"))]
        {
            assert!(result.is_ok(), "Empty style values should be handled");
        }

        // Test with CSS variable
        let result = super::WitPlatform::set_style_static(&element, "--my-var", "blue");
        #[cfg(not(target_family = "wasm"))]
        {
            assert!(result.is_ok(), "CSS variables should be handled");
        }
    }

    // -- wasm_impl module tests ---------------------------------------------

    /// Test next_callback_id increments.
    #[cfg(all(feature = "wit-bindings", target_family = "wasm"))]
    #[test]
    fn test_next_callback_id() {
        use super::wasm_impl;

        let id1 = wasm_impl::next_callback_id();
        let id2 = wasm_impl::next_callback_id();
        let id3 = wasm_impl::next_callback_id();

        assert!(id2 > id1, "Callback IDs should increment");
        assert!(id3 > id2, "Callback IDs should increment");
        assert_eq!(id2, id1 + 1, "IDs should increment by 1");
        assert_eq!(id3, id2 + 1, "IDs should increment by 1");
    }

    /// Test that log functions don't crash.
    #[cfg(all(feature = "wit-bindings", target_family = "wasm"))]
    #[test]
    fn test_log_functions_no_crash() {
        use super::wasm_impl::{log_error, log_info, log_warning};

        // These should not panic - they're no-ops on wasm
        log_error("test error message");
        log_warning("test warning message");
        log_info("test info message");
    }

    /// Test WitElement Debug output.
    #[cfg(feature = "wit-bindings")]
    #[test]
    fn test_wit_element_debug() {
        let element = super::WitElement(42);
        let debug_str = format!("{:?}", element);

        assert!(
            debug_str.contains("42"),
            "Debug output should contain the handle value"
        );
    }

    /// Test WitEvent can be cloned multiple times.
    #[cfg(feature = "wit-bindings")]
    #[test]
    fn test_wit_event_multiple_clones() {
        let event1 = super::WitEvent(100);
        let event2 = event1.clone();
        let event3 = event2.clone();

        assert_eq!(event1.0, 100);
        assert_eq!(event2.0, 100);
        assert_eq!(event3.0, 100);
    }

    /// Test WitElement Copy trait behavior.
    #[cfg(feature = "wit-bindings")]
    #[test]
    fn test_wit_element_copy() {
        let elem1 = super::WitElement(55);
        let elem2 = elem1; // WitElement is Copy

        // Both should have the same value
        assert_eq!(elem1.0, 55);
        assert_eq!(elem2.0, 55);
    }

    /// Test WitElement as_any with different Any operations.
    #[cfg(feature = "wit-bindings")]
    #[test]
    fn test_wit_element_any_operations() {
        use std::any::TypeId;
        use tairitsu_vdom::ElementHandle;

        let element = super::WitElement(777);
        let any_ref = element.as_any();

        // Check TypeId
        assert_eq!(any_ref.type_id(), TypeId::of::<super::WitElement>());

        // Verify is<T>() works
        assert!(any_ref.is::<super::WitElement>());
        assert!(!any_ref.is::<String>());
        assert!(!any_ref.is::<i32>());
    }
}
