[package]
authors = ["langyo <langyo.china@gmail.com>"]
name = "tairitsu-boot"

version = "0.1.0"
edition = "2021"
publish = false

[lib]
crate-type = ["rlib"]

[dependencies]
tairitsu-macro = { path = "../macro" }
tairitsu-macro-types = { path = "../macro-types" }

anyhow = "^1"
async-trait = "^0.1"
base64 = "^0.22"
derive_more = { version = "^1", features = ["full"] }
gloo = "^0.11"
serde = { version = "^1", features = ["derive"] }
serde_json = "^1"
strum = { version = "^0.26", features = ["derive"] }
