//! SSR stub code generator
//!
//! This build script generates stub implementations for all browser WIT interfaces
//! that are not manually implemented.

use std::collections::HashSet;
use std::fs::File;
use std::io::Write;
use std::path::Path;

fn main() {
    // Only regenerate if the WIT file changes
    println!("cargo:rerun-if-changed=../../browser-worlds/wit/browser-full.wit");

    // Read the WIT file to extract interface names
    let wit_path = "../../browser-worlds/wit/browser-full.wit";
    let wit_content = match std::fs::read_to_string(wit_path) {
        Ok(content) => content,
        Err(e) => {
            eprintln!("Warning: Could not read WIT file: {}", e);
            eprintln!("SSR stubs will not be generated");
            return;
        }
    };

    // Interfaces that are manually implemented (don't generate stubs for these)
    let manual_interfaces: HashSet<&'static str> = [
        "platform-helpers",
        "console",
        "event-target",
        "style",
        "document",
        "node",
        "element",
        "window",
        "types",
    ]
    .into_iter()
    .collect();

    // Parse the WIT file to find all interfaces
    let mut interfaces = Vec::new();
    for line in wit_content.lines() {
        let line = line.trim();
        if line.starts_with("interface ") {
            // Extract interface name
            let rest = &line[10..]; // Skip "interface "
            let name = rest
                .split_whitespace()
                .next()
                .and_then(|s| s.split('{').next())
                .unwrap_or("");
            if !name.is_empty() && !manual_interfaces.contains(name) {
                interfaces.push(name.to_string());
            }
        }
    }

    // Generate the stub code
    let generated_code = generate_stubs(&interfaces);

    // Write to the generated file
    let out_dir = std::env::var("OUT_DIR").unwrap();
    let generated_path = Path::new(&out_dir).join("ssr_stubs.rs");
    let mut file = File::create(&generated_path).expect("Failed to create generated file");
    file.write_all(generated_code.as_bytes())
        .expect("Failed to write generated code");

    println!("Generated {} stub interfaces", interfaces.len());
}

fn generate_stubs(interfaces: &[String]) -> String {
    let mut code = String::new();

    code.push_str("// Auto-generated SSR stub implementations\n");
    code.push_str("// DO NOT EDIT - This file is generated by build.rs\n\n");

    for interface_name in interfaces {
        code.push_str(&generate_interface_stub(interface_name));
    }

    // Generate a function to register all stubs
    code.push_str("\n/// Register all auto-generated stub interfaces with the linker\n");
    code.push_str("pub fn register_all_stubs<T>(\n");
    code.push_str("    _linker: &mut wasmtime::component::Linker<T>,\n");
    code.push_str(") -> anyhow::Result<()>\n");
    code.push_str("where\n");
    code.push_str("    T: Send,\n");
    code.push_str("{\n");
    code.push_str("    // Stubs are no-ops in SSR\n");
    code.push_str("    // The actual interface implementations are in the interfaces/ module\n");
    code.push_str("    Ok(())\n");
    code.push_str("}\n");

    code
}

fn generate_interface_stub(interface_name: &str) -> String {
    format!(
        r#"/// Stub for {interface_name} interface
///
/// This interface is not implemented in SSR.
/// All functions return appropriate default values or errors.
pub mod {sanitized} {{
    /// Add {interface_name} interface to the linker (stub - no-op)
    pub fn add_to_linker<T>(
        _linker: &mut wasmtime::component::Linker<T>,
        _get_state: impl FnMut(&mut T) -> &mut crate::host_state::SsrHostState + Send + Sync + Copy + 'static,
    ) -> anyhow::Result<()>
    where
        T: Send,
    {{
        // Stub implementation - interface not used in SSR
        Ok(())
    }}
}}
"#,
        interface_name = interface_name,
        sanitized = interface_name.replace('-', "_")
    )
}
