#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum CssProperty {
    Display,
    Position,
    Top,
    Right,
    Bottom,
    Left,
    ZIndex,
    Float,
    Clear,

    Width,
    MinWidth,
    MaxWidth,
    Height,
    MinHeight,
    MaxHeight,
    Margin,
    MarginTop,
    MarginRight,
    MarginBottom,
    MarginLeft,
    Padding,
    PaddingTop,
    PaddingRight,
    PaddingBottom,
    PaddingLeft,
    Border,
    BorderTop,
    BorderRight,
    BorderBottom,
    BorderLeft,
    BorderRadius,
    BorderWidth,
    BorderStyle,
    BorderColor,

    Flex,
    FlexBasis,
    FlexDirection,
    FlexFlow,
    FlexGrow,
    FlexShrink,
    FlexWrap,
    AlignContent,
    AlignItems,
    AlignSelf,
    JustifyContent,
    JustifyItems,
    JustifySelf,
    Gap,
    RowGap,
    ColumnGap,
    Order,

    Grid,
    GridArea,
    GridAutoColumns,
    GridAutoFlow,
    GridAutoRows,
    GridColumn,
    GridColumnEnd,
    GridColumnStart,
    GridRow,
    GridRowEnd,
    GridRowStart,
    GridTemplate,
    GridTemplateAreas,
    GridTemplateColumns,
    GridTemplateRows,

    Font,
    FontFamily,
    FontSize,
    FontSizeAdjust,
    FontStretch,
    FontStyle,
    FontVariant,
    FontWeight,
    LetterSpacing,
    LineHeight,
    TextAlign,
    TextDecoration,
    TextIndent,
    TextTransform,
    WhiteSpace,
    WordSpacing,
    WordBreak,
    WordWrap,

    Color,
    Background,
    BackgroundAttachment,
    BackgroundClip,
    BackgroundColor,
    BackgroundImage,
    BackgroundOrigin,
    BackgroundPosition,
    BackgroundRepeat,
    BackgroundSize,
    Opacity,

    Overflow,
    OverflowX,
    OverflowY,
    Visibility,
    Cursor,
    PointerEvents,
    UserSelect,
    ObjectFit,

    Transform,
    TransformOrigin,
    Transition,
    TransitionDelay,
    TransitionDuration,
    TransitionProperty,
    TransitionTimingFunction,
    Animation,
    AnimationDelay,
    AnimationDirection,
    AnimationDuration,
    AnimationFillMode,
    AnimationIterationCount,
    AnimationName,
    AnimationPlayState,
    AnimationTimingFunction,

    BoxShadow,
    Filter,
    TextShadow,
    ClipPath,
    Mask,
    MaskImage,
    MaskSize,
    MaskRepeat,
    MaskPosition,
    MaskClip,
    MaskOrigin,

    Content,
    Outline,
    OutlineOffset,
    OutlineWidth,
    OutlineStyle,
    OutlineColor,
    ListStyle,
    ListStyleType,
    ListStylePosition,
    ListStyleImage,
}

impl CssProperty {
    pub fn as_str(&self) -> &'static str {
        match self {
            CssProperty::Display => "display",
            CssProperty::Position => "position",
            CssProperty::Top => "top",
            CssProperty::Right => "right",
            CssProperty::Bottom => "bottom",
            CssProperty::Left => "left",
            CssProperty::ZIndex => "z-index",
            CssProperty::Float => "float",
            CssProperty::Clear => "clear",

            CssProperty::Width => "width",
            CssProperty::MinWidth => "min-width",
            CssProperty::MaxWidth => "max-width",
            CssProperty::Height => "height",
            CssProperty::MinHeight => "min-height",
            CssProperty::MaxHeight => "max-height",
            CssProperty::Margin => "margin",
            CssProperty::MarginTop => "margin-top",
            CssProperty::MarginRight => "margin-right",
            CssProperty::MarginBottom => "margin-bottom",
            CssProperty::MarginLeft => "margin-left",
            CssProperty::Padding => "padding",
            CssProperty::PaddingTop => "padding-top",
            CssProperty::PaddingRight => "padding-right",
            CssProperty::PaddingBottom => "padding-bottom",
            CssProperty::PaddingLeft => "padding-left",
            CssProperty::Border => "border",
            CssProperty::BorderTop => "border-top",
            CssProperty::BorderRight => "border-right",
            CssProperty::BorderBottom => "border-bottom",
            CssProperty::BorderLeft => "border-left",
            CssProperty::BorderRadius => "border-radius",
            CssProperty::BorderWidth => "border-width",
            CssProperty::BorderStyle => "border-style",
            CssProperty::BorderColor => "border-color",

            CssProperty::Flex => "flex",
            CssProperty::FlexBasis => "flex-basis",
            CssProperty::FlexDirection => "flex-direction",
            CssProperty::FlexFlow => "flex-flow",
            CssProperty::FlexGrow => "flex-grow",
            CssProperty::FlexShrink => "flex-shrink",
            CssProperty::FlexWrap => "flex-wrap",
            CssProperty::AlignContent => "align-content",
            CssProperty::AlignItems => "align-items",
            CssProperty::AlignSelf => "align-self",
            CssProperty::JustifyContent => "justify-content",
            CssProperty::JustifyItems => "justify-items",
            CssProperty::JustifySelf => "justify-self",
            CssProperty::Gap => "gap",
            CssProperty::RowGap => "row-gap",
            CssProperty::ColumnGap => "column-gap",
            CssProperty::Order => "order",

            CssProperty::Grid => "grid",
            CssProperty::GridArea => "grid-area",
            CssProperty::GridAutoColumns => "grid-auto-columns",
            CssProperty::GridAutoFlow => "grid-auto-flow",
            CssProperty::GridAutoRows => "grid-auto-rows",
            CssProperty::GridColumn => "grid-column",
            CssProperty::GridColumnEnd => "grid-column-end",
            CssProperty::GridColumnStart => "grid-column-start",
            CssProperty::GridRow => "grid-row",
            CssProperty::GridRowEnd => "grid-row-end",
            CssProperty::GridRowStart => "grid-row-start",
            CssProperty::GridTemplate => "grid-template",
            CssProperty::GridTemplateAreas => "grid-template-areas",
            CssProperty::GridTemplateColumns => "grid-template-columns",
            CssProperty::GridTemplateRows => "grid-template-rows",

            CssProperty::Font => "font",
            CssProperty::FontFamily => "font-family",
            CssProperty::FontSize => "font-size",
            CssProperty::FontSizeAdjust => "font-size-adjust",
            CssProperty::FontStretch => "font-stretch",
            CssProperty::FontStyle => "font-style",
            CssProperty::FontVariant => "font-variant",
            CssProperty::FontWeight => "font-weight",
            CssProperty::LetterSpacing => "letter-spacing",
            CssProperty::LineHeight => "line-height",
            CssProperty::TextAlign => "text-align",
            CssProperty::TextDecoration => "text-decoration",
            CssProperty::TextIndent => "text-indent",
            CssProperty::TextTransform => "text-transform",
            CssProperty::WhiteSpace => "white-space",
            CssProperty::WordSpacing => "word-spacing",
            CssProperty::WordBreak => "word-break",
            CssProperty::WordWrap => "word-wrap",

            CssProperty::Color => "color",
            CssProperty::Background => "background",
            CssProperty::BackgroundAttachment => "background-attachment",
            CssProperty::BackgroundClip => "background-clip",
            CssProperty::BackgroundColor => "background-color",
            CssProperty::BackgroundImage => "background-image",
            CssProperty::BackgroundOrigin => "background-origin",
            CssProperty::BackgroundPosition => "background-position",
            CssProperty::BackgroundRepeat => "background-repeat",
            CssProperty::BackgroundSize => "background-size",
            CssProperty::Opacity => "opacity",

            CssProperty::Overflow => "overflow",
            CssProperty::OverflowX => "overflow-x",
            CssProperty::OverflowY => "overflow-y",
            CssProperty::Visibility => "visibility",
            CssProperty::Cursor => "cursor",
            CssProperty::PointerEvents => "pointer-events",
            CssProperty::UserSelect => "user-select",
            CssProperty::ObjectFit => "object-fit",

            CssProperty::Transform => "transform",
            CssProperty::TransformOrigin => "transform-origin",
            CssProperty::Transition => "transition",
            CssProperty::TransitionDelay => "transition-delay",
            CssProperty::TransitionDuration => "transition-duration",
            CssProperty::TransitionProperty => "transition-property",
            CssProperty::TransitionTimingFunction => "transition-timing-function",
            CssProperty::Animation => "animation",
            CssProperty::AnimationDelay => "animation-delay",
            CssProperty::AnimationDirection => "animation-direction",
            CssProperty::AnimationDuration => "animation-duration",
            CssProperty::AnimationFillMode => "animation-fill-mode",
            CssProperty::AnimationIterationCount => "animation-iteration-count",
            CssProperty::AnimationName => "animation-name",
            CssProperty::AnimationPlayState => "animation-play-state",
            CssProperty::AnimationTimingFunction => "animation-timing-function",

            CssProperty::BoxShadow => "box-shadow",
            CssProperty::Filter => "filter",
            CssProperty::TextShadow => "text-shadow",
            CssProperty::ClipPath => "clip-path",
            CssProperty::Mask => "mask",
            CssProperty::MaskImage => "mask-image",
            CssProperty::MaskSize => "mask-size",
            CssProperty::MaskRepeat => "mask-repeat",
            CssProperty::MaskPosition => "mask-position",
            CssProperty::MaskClip => "mask-clip",
            CssProperty::MaskOrigin => "mask-origin",

            CssProperty::Content => "content",
            CssProperty::Outline => "outline",
            CssProperty::OutlineOffset => "outline-offset",
            CssProperty::OutlineWidth => "outline-width",
            CssProperty::OutlineStyle => "outline-style",
            CssProperty::OutlineColor => "outline-color",
            CssProperty::ListStyle => "list-style",
            CssProperty::ListStyleType => "list-style-type",
            CssProperty::ListStylePosition => "list-style-position",
            CssProperty::ListStyleImage => "list-style-image",
        }
    }
}

#[derive(Debug, Clone, PartialEq)]
pub enum Property {
    Known(CssProperty),
    Custom(String),
}

impl Property {
    pub fn as_str(&self) -> &str {
        match self {
            Property::Known(prop) => prop.as_str(),
            Property::Custom(s) => s,
        }
    }
}
