#!/usr/bin/env python3
"""Configuration and type mapping constants for browser glue generator."""

# Interface name → browser class mapping
INTERFACE_TO_BROWSER_CLASS = {
    "node": "Node",
    "element": "Element",
    "document": "Document",
    "window": "Window",
    "headers": "Headers",
    "request": "Request",
    "response": "Response",
    "body": "Body",
    "storage-manager": "StorageManager",
    "navigator-storage": "NavigatorStorage",
    "storage": "Storage",
    "url": "URL",
    "url-search-params": "URLSearchParams",
    "crypto": "Crypto",
    "subtle-crypto": "SubtleCrypto",
    "crypto-key": "CryptoKey",
    "event": "Event",
    "event-target": "EventTarget",
    "navigator": "Navigator",
    "battery-manager": "BatteryManager",
    "gamepad": "Gamepad",
    "gamepad-button": "GamepadButton",
    "gamepad-haptic-actuator": "GamepadHapticActuator",
    "geolocation-coordinates": "GeolocationCoordinates",
    "geolocation-position": "GeolocationPosition",
    "geolocation-position-error": "GeolocationPositionError",
    "screen-orientation": "ScreenOrientation",
    "media-capabilities": "MediaCapabilities",
    "media-devices": "MediaDevices",
    "media-session": "MediaSession",
    "media-stream": "MediaStream",
    "canvas-rendering-context": "CanvasRenderingContext2D",
    "webgl-rendering-context": "WebGLRenderingContext",
    "notification": "Notification",
    "permissions": "Permissions",
    "permission-status": "PermissionStatus",
    "readable-stream": "ReadableStream",
    "writable-stream": "WritableStream",
    "transform-stream": "TransformStream",
    "worker": "Worker",
    "service-worker": "ServiceWorker",
    "idb-database": "IDBDatabase",
    "idb-request": "IDBRequest",
    "idb-transaction": "IDBTransaction",
    "geolocation": "Geolocation",
    "performance": "Performance",
    "rtc-peer-connection": "RTCPeerConnection",
    "credential": "Credential",
    "password-credential": "PasswordCredential",
    "federated-credential": "FederatedCredential",
    "credential-user-data": "any",
}

# Types that don't exist in TypeScript DOM library (use 'any' for handles)
MISSING_TYPES_IN_DOM = {
    "credential-user-data": "any",
    "password-credential": "any",
    "federated-credential": "any",
}

# Known global singleton objects (not instantiated, use global reference)
GLOBAL_SINGLETONS = {
    "window": "window",
    "document": "document",
    "navigator": "navigator",
}

# Known async operation patterns (return Promises in browser)
ASYNC_PATTERNS = [
    "estimate", "persist", "persisted", "fetch", "respond",
    "array-buffer", "blob", "text", "json", "bytes", "form-data",
    "get-reader", "get-writer", "pipe-to", "pipe-through",
    "from", "create-image-bitmap",
    "get-user-media", "enumerate-devices",
    "query", "request",
    "get", "store", "create", "prevent-silent-access",
    "flush", "abort", "close", "start", "stop", "lock", "unlock",
]

# Attribute getters that return handles (need wrapping)
HANDLE_GETTER_PATTERNS = [
    "get-headers", "get-body", "get-signal",
    "get-storage", "get-crypto", "get-performance",
]

# Special browser API name mappings (WIT name -> browser API name)
BROWSER_API_NAME_MAPPINGS = {
    "get-random-values": "getRandomValues",
    "random-uuid": "randomUUID",
    "is-conditional-mediation-available": "isConditionalMediationAvailable",
    "to-json": "toJSON",
    "inner-html": "innerHTML",
    "outer-html": "outerHTML",
    "namespace-uri": "namespaceURI",
    "document-uri": "documentURI",
    "base-uri": "baseURI",
    "voice-uri": "voiceURI",
    "script-url": "scriptURL",
    "old-url": "oldURL",
    "new-url": "newURL",
    "current-css-zoom": "currentCSSZoom",
    "has-ua-visual-transition": "hasUAVisualTransition",
    "elements-by-tag-name": "getElementsByTagName",
    "elements-by-tag-name-ns": "getElementsByTagNameNS",
    "elements-by-class-name": "getElementsByClassName",
    "element-by-id": "getElementById",
    "elements-by-name": "getElementsByName",
    "client-rects": "getClientRects",
    "bounding-client-rect": "getBoundingClientRect",
    "client-rect": "getClientRect",
    "attribute": "getAttribute",
    "attribute-ns": "getAttributeNS",
    "attribute-node": "getAttributeNode",
    "attribute-node-ns": "getAttributeNodeNS",
    "attribute-names": "getAttributeNames",
    "set-attribute": "setAttribute",
    "set-attribute-ns": "setAttributeNS",
    "remove-attribute-ns": "removeAttributeNS",
    "has-attribute-ns": "hasAttributeNS",
    "named-item": "getNamedItem",
    "named-item-ns": "getNamedItemNS",
    "track-by-id": "getTrackById",
    "create-element-ns": "createElementNS",
    "create-attribute-ns": "createAttributeNS",
    "create-cdata-section": "createCDATASection",
    "create-ns-resolver": "createNSResolver",
    "insert-adjacent-html": "insertAdjacentHTML",
    "pointer-capture": "hasPointerCapture",
    "set-start-before": "setStartBefore",
    "set-start-after": "setStartAfter",
    "set-end-before": "setEndBefore",
    "lookup-namespace-uri": "lookupNamespaceURI",
    "remove-named-item-ns": "removeNamedItemNS",
    "modifier-state": "getModifierState",
    "coalesced-events": "getCoalescedEvents",
    "predicted-events": "getPredictedEvents",
    "set-cookie": "getSetCookie",
    "context-attributes": "getContextAttributes",
    "image-data": "getImageData",
    "set-transform": "setTransform",
    "form-value": "setFormValue",
    "drag-image": "setDragImage",
    "add-search-provider": "AddSearchProvider",
    "is-search-provider-installed": "IsSearchProviderInstalled",
    "audio-tracks": "getAudioTracks",
    "video-tracks": "getVideoTracks",
    "constraints": "getConstraints",
    "supported-constraints": "getSupportedConstraints",
    "user-media": "getUserMedia",
    "display-media": "getDisplayMedia",
    "action-handler": "setActionHandler",
    "position-state": "setPositionState",
    "microphone-active": "setMicrophoneActive",
    "camera-active": "setCameraActive",
    "notifications": "getNotifications",
    "resource-timing-buffer-size": "setResourceTimingBufferSize",
    "entries-by-type": "getEntriesByType",
    "entries-by-name": "getEntriesByName",
    "receivers": "getReceivers",
    "transceivers": "getTransceivers",
    "capabilities": "getCapabilities",
    "configuration": "getConfiguration",
    "css-keyframe-rule": "KEYFRAME_RULE",
    "current-position": "getCurrentPosition",
    "random-values": "getRandomValues",
    "registrations": "getRegistrations",
    "header-value": "setHeaderValue",
    "computed-style": "getComputedStyle",
    "html-unsafe": "setHTMLUnsafe",
    "context-attributes": "getContextAttributes",
    "supported-extensions": "getSupportedExtensions",
    "extension": "getExtension",
    "active-attrib": "getActiveAttrib",
    "active-uniform": "getActiveUniform",
    "attached-shaders": "getAttachedShaders",
    "attrib-location": "getAttribLocation",
    "buffer-parameter": "getBufferParameter",
    "parameter": "getParameter",
    "framebuffer-attachment-parameter": "getFramebufferAttachmentParameter",
    "program-parameter": "getProgramParameter",
    "program-info-log": "getProgramInfoLog",
    "renderbuffer-parameter": "getRenderbufferParameter",
    "shader-parameter": "getShaderParameter",
    "shader-precision-format": "getShaderPrecisionFormat",
    "shader-info-log": "getShaderInfoLog",
    "shader-source": "getShaderSource",
    "tex-parameter": "getTexParameter",
    "uniform": "getUniform",
    "uniform-location": "getUniformLocation",
    "vertex-attrib": "getVertexAttrib",
    "vertex-attrib-offset": "getVertexAttribOffset",
}

# Static method return type overrides (method name -> actual return type)
STATIC_METHOD_RETURN_OVERRIDES = {
    ("credential", "isConditionalMediationAvailable"): "Promise<boolean>",
}

# Static methods that need type assertions (methods missing from TypeScript DOM lib)
STATIC_METHOD_NEEDS_TYPE_ASSERTION = {
    ("Credential", "isConditionalMediationAvailable"),
}

# Functions that return browser objects (need to wrap in handle)
HANDLE_RETURNING_FUNCTIONS = {
    ("crypto", "getSubtle"): "subtle-crypto",
}

# Parameters that are handles and need to be looked up
# Maps (interface, function, param_name) -> (target_interface, target_type)
PARAMETER_HANDLE_MAPPING = {
    ("audio-decoder", "decode", "chunk"): ("canvas", "EncodedAudioChunk"),
    ("video-decoder", "decode", "chunk"): ("canvas", "EncodedVideoChunk"),
    ("audio-encoder", "encode", "data"): ("canvas", "AudioData"),
    ("audio-encoder", "encode", "options"): ("canvas", "AudioEncoderEncodeOptions"),
    ("video-encoder", "encode", "frame"): ("canvas", "VideoFrame"),
    ("video-encoder", "encode", "options"): ("canvas", "VideoEncoderEncodeOptions"),
}

# Parameters that are dictionary types (not handles) - should be passed directly as objects
# Maps (interface, function, param_name) -> TypeScript type
DICTIONARY_PARAMETER_TYPES = {
    ("audio-decoder", "configure", "config"): "AudioDecoderConfig",
    ("audio-decoder", "is-config-supported", "config"): "AudioDecoderConfig",
    ("video-decoder", "configure", "config"): "VideoDecoderConfig",
    ("video-decoder", "is-config-supported", "config"): "VideoDecoderConfig",
    ("audio-encoder", "configure", "config"): "AudioEncoderConfig",
    ("audio-encoder", "is-config-supported", "config"): "AudioEncoderConfig",
    ("audio-encoder", "encode", "options"): "AudioEncoderEncodeOptions",
    ("video-encoder", "configure", "config"): "VideoEncoderConfig",
    ("video-encoder", "is-config-supported", "config"): "VideoEncoderConfig",
    ("video-encoder", "encode", "options"): "VideoEncoderEncodeOptions",
}

# Parameters that need bigint to number conversion
# Maps (interface, function, param_name) -> boolean (true if number conversion needed)
PARAMETER_BIGINT_TO_NUMBER = {
    ("webgl-rendering-context-base", "bind-buffer", "target"): True,
    ("webgl-rendering-context-base", "bind-framebuffer", "target"): True,
    ("webgl-rendering-context-base", "bind-renderbuffer", "target"): True,
    ("webgl-rendering-context-base", "bind-texture", "target"): True,
    ("webgl-rendering-context-base", "disable", "cap"): True,
    ("webgl-rendering-context-base", "enable", "cap"): True,
    ("webgl-rendering-context-base", "get-attribute", "index"): True,
    ("webgl-rendering-context-base", "get-boolean", "pname"): True,
    ("webgl-rendering-context-base", "get-buffer-parameter", "target"): True,
    ("webgl-rendering-context-base", "get-framebuffer-attachment-parameter", "target"): True,
    ("webgl-rendering-context-base", "get-program-parameter", "pname"): True,
    ("webgl-rendering-context-base", "get-renderbuffer-parameter", "target"): True,
    ("webgl-rendering-context-base", "get-shader-parameter", "pname"): True,
    ("webgl-rendering-context-base", "get-tex-parameter", "target"): True,
    ("webgl-rendering-context-base", "get-uniform", "location"): True,
    ("webgl-rendering-context-base", "get-vertex-attrib", "index"): True,
    ("webgl-rendering-context-base", "vertex-attrib-pointer", "index"): True,
    ("webgl2-rendering-context-base", "bind-buffer", "target"): True,
    ("webgl2-rendering-context-base", "bind-framebuffer", "target"): True,
    ("webgl2-rendering-context-base", "bind-renderbuffer", "target"): True,
    ("webgl2-rendering-context-base", "bind-texture", "target"): True,
    ("webgl2-rendering-context-base", "bind-vertex-array", "array"): True,
    ("webgl2-rendering-context-base", "disable", "cap"): True,
    ("webgl2-rendering-context-base", "enable", "cap"): True,
    ("webgl2-rendering-context-base", "get-buffer-parameter", "target"): True,
    ("webgl2-rendering-context-base", "get-framebuffer-attachment-parameter", "target"): True,
    ("webgl2-rendering-context-base", "get-program-parameter", "pname"): True,
    ("webgl2-rendering-context-base", "get-renderbuffer-parameter", "target"): True,
    ("webgl2-rendering-context-base", "get-tex-parameter", "target"): True,
    ("webgl2-rendering-context-base", "get-uniform", "location"): True,
    ("webgl2-rendering-context-base", "get-vertex-attrib", "index"): True,
    ("webgl2-rendering-context-base", "vertex-attrib-pointer", "index"): True,
    ("webgl2-rendering-context-base", "vertex-attrib-pointer", "index"): True,
}

# Properties that are enums (string in DOM, bigint in WIT)
# Maps (interface, property) to enum type name
ENUM_PROPERTIES = {
    ("audio-decoder", "state"): "CodecState",
    ("video-decoder", "state"): "CodecState",
    ("audio-encoder", "state"): "CodecState",
    ("video-encoder", "state"): "CodecState",
}

# Enum value mappings (string → bigint)
# Values are Python integers that will be rendered as bigint literals (e.g., 0n)
ENUM_VALUE_MAPPINGS = {
    "CodecState": {
        "unconfigured": 0,
        "configured": 1,
        "closed": 2,
    },
}

# Functions that are defined as getters in WIT but are actually methods in DOM API
GETTER_BUT_ACTUALLY_METHOD = {
    "context-attributes", "supported-extensions", "extension", "active-attrib",
    "active-uniform", "attached-shaders", "attrib-location", "buffer-parameter",
    "parameter", "framebuffer-attachment-parameter", "program-parameter",
    "program-info-log", "renderbuffer-parameter", "shader-parameter",
    "shader-precision-format", "shader-info-log", "shader-source",
    "tex-parameter", "uniform", "uniform-location", "vertex-attrib",
    "vertex-attrib-offset",
}

# Type definitions that need to be generated in glue code
CUSTOM_TYPE_DEFINITIONS = {
    "EventHandlerRecord": "any",
}

# Type name casing corrections for TypeScript DOM types
TYPE_NAME_CASING_OVERRIDES = {
    "IdbCursor": "IDBCursor",
    "IdbCursorWithValue": "IDBCursorWithValue",
    "IdbDatabase": "IDBDatabase",
    "IdbFactory": "IDBFactory",
    "IdbIndex": "IDBIndex",
    "IdbKeyRange": "IDBKeyRange",
    "IdbObjectStore": "IDBObjectStore",
    "IdbOpenDBRequest": "IDBOpenDBRequest",
    "IdbRequest": "IDBRequest",
    "IdbTransaction": "IDBTransaction",
    "IdbVersionChangeEvent": "IDBVersionChangeEvent",
    "WebGlObject": "WebGLObject",
    "WebGlBuffer": "WebGLBuffer",
    "WebGlFramebuffer": "WebGLFramebuffer",
    "WebGlProgram": "WebGLProgram",
    "WebGlRenderbuffer": "WebGLRenderbuffer",
    "WebGlShader": "WebGLShader",
    "WebGlTexture": "WebGLTexture",
    "WebGlUniformLocation": "WebGLUniformLocation",
    "WebGlActiveInfo": "WebGLActiveInfo",
    "WebGlShaderPrecisionFormat": "WebGLShaderPrecisionFormat",
    "WebGlContextEvent": "WebGLContextEvent",
    "WebGlRenderingContext": "WebGLRenderingContext",
    "WebGlRenderingContextBase": "WebGLRenderingContextBase",
    "WebGlRenderingContextOverloads": "WebGLRenderingContextOverloads",
    "WebGl2RenderingContext": "WebGL2RenderingContext",
    "WebGl2RenderingContextBase": "WebGL2RenderingContextBase",
    "WebGl2RenderingContextOverloads": "WebGL2RenderingContextOverloads",
    "HtmlElement": "HTMLElement",
    "HtmlAllCollection": "HTMLAllCollection",
    "HtmlCollection": "HTMLCollection",
    "HtmlCollectionBase": "HTMLCollectionBase",
    "HtmlCollectionOf": "HTMLCollectionOf",
    "HtmlFormControlsCollection": "HTMLFormControlsCollection",
    "HtmlOptionsCollection": "HTMLOptionsCollection",
    "HtmlAnchorElement": "HTMLAnchorElement",
    "HtmlAreaElement": "HTMLAreaElement",
    "HtmlAudioElement": "HTMLAudioElement",
    "HtmlBaseElement": "HTMLBaseElement",
    "HtmlBodyElement": "HTMLBodyElement",
    "HtmlBrElement": "HTMLBRElement",
    "HtmlButtonElement": "HTMLButtonElement",
    "HtmlCanvasElement": "HTMLCanvasElement",
    "HtmlDataElement": "HTMLDataElement",
    "HtmlDataListElement": "HTMLDataListElement",
    "HtmlDetailsElement": "HTMLDetailsElement",
    "HtmlDialogElement": "HTMLDialogElement",
    "HtmlDirectoryElement": "HTMLDirectoryElement",
    "HtmlDivElement": "HTMLDivElement",
    "HtmlDListElement": "HTMLDListElement",
    "HtmlEmbedElement": "HTMLEmbedElement",
    "HtmlFieldSetElement": "HTMLFieldSetElement",
    "HtmlFontElement": "HTMLFontElement",
    "HtmlFormElement": "HTMLFormElement",
    "HtmlFrameElement": "HTMLFrameElement",
    "HtmlFrameSetElement": "HTMLFrameSetElement",
    "HtmlHeadElement": "HTMLHeadElement",
    "HtmlHeadingElement": "HTMLHeadingElement",
    "HtmlHrElement": "HTMLHRElement",
    "HtmlHtmlElement": "HTMLHtmlElement",
    "HtmlIFrameElement": "HTMLIFrameElement",
    "HtmlImageElement": "HTMLImageElement",
    "HtmlInputElement": "HTMLInputElement",
    "HtmlLabelElement": "HTMLLabelElement",
    "HtmlLegendElement": "HTMLLegendElement",
    "HtmlLiElement": "HTMLLIElement",
    "HtmlLinkElement": "HTMLLinkElement",
    "HtmlMapElement": "HTMLMapElement",
    "HtmlMarqueeElement": "HTMLMarqueeElement",
    "HtmlMediaElement": "HTMLMediaElement",
    "HtmlMenuElement": "HTMLMenuElement",
    "HtmlMetaElement": "HTMLMetaElement",
    "HtmlMeterElement": "HTMLMeterElement",
    "HtmlModElement": "HTMLModElement",
    "HtmlObjectElement": "HTMLObjectElement",
    "HtmlOListElement": "HTMLOListElement",
    "HtmlOptGroupElement": "HTMLOptGroupElement",
    "HtmlOptionElement": "HTMLOptionElement",
    "HtmlOutputElement": "HTMLOutputElement",
    "HtmlParagraphElement": "HTMLParagraphElement",
    "HtmlParamElement": "HTMLParamElement",
    "HtmlPictureElement": "HTMLPictureElement",
    "HtmlPreElement": "HTMLPreElement",
    "HtmlProgressElement": "HTMLProgressElement",
    "HtmlQuoteElement": "HTMLQuoteElement",
    "HtmlScriptElement": "HTMLScriptElement",
    "HtmlSelectElement": "HTMLSelectElement",
    "HtmlSlotElement": "HTMLSlotElement",
    "HtmlSourceElement": "HTMLSourceElement",
    "HtmlSpanElement": "HTMLSpanElement",
    "HtmlStyleElement": "HTMLStyleElement",
    "HtmlTableCaptionElement": "HTMLTableCaptionElement",
    "HtmlTableCellElement": "HTMLTableCellElement",
    "HtmlTableColElement": "HTMLTableColElement",
    "HtmlTableElement": "HTMLTableElement",
    "HtmlTableRowElement": "HTMLTableRowElement",
    "HtmlTableSectionElement": "HTMLTableSectionElement",
    "HtmlTemplateElement": "HTMLTemplateElement",
    "HtmlTextAreaElement": "HTMLTextAreaElement",
    "HtmlTimeElement": "HTMLTimeElement",
    "HtmlTitleElement": "HTMLTitleElement",
    "HtmlTrackElement": "HTMLTrackElement",
    "HtmlUListElement": "HTMLUListElement",
    "HtmlUnknownElement": "HTMLUnknownElement",
    "HtmlVideoElement": "HTMLVideoElement",
    "HtmlOrSvgElement": "HTMLOrSVGElement",
    "HtmlHyperlinkElementUtils": "HTMLHyperlinkElementUtils",
    "DomImplementation": "DOMImplementation",
    "DomParser": "DOMParser",
    "DomRect": "DOMRect",
    "DomRectList": "DOMRectList",
    "DomRectReadOnly": "DOMRectReadOnly",
    "DomStringList": "DOMStringList",
    "DomStringMap": "DOMStringMap",
    "DomTokenList": "DOMTokenList",
    "DomMatrix": "DOMMatrix",
    "DomMatrixReadOnly": "DOMMatrixReadOnly",
    "DomPoint": "DOMPoint",
    "DomPointReadOnly": "DOMPointReadOnly",
    "DomQuad": "DOMQuad",
    "DomSettableTokenList": "DOMSettableTokenList",
    "CssRule": "CSSRule",
    "CssRuleList": "CSSRuleList",
    "CssStyleDeclaration": "CSSStyleDeclaration",
    "CssStyleRule": "CSSStyleRule",
    "CssStyleSheet": "CSSStyleSheet",
    "CssConditionRule": "CSSConditionRule",
    "CssContainerRule": "CSSContainerRule",
    "CssCounterStyleRule": "CSSCounterStyleRule",
    "CssFontFaceRule": "CSSFontFaceRule",
    "CssFontFeatureValuesRule": "CSSFontFeatureValuesRule",
    "CssFontPaletteValuesRule": "CSSFontPaletteValuesRule",
    "CssGroupingRule": "CSSGroupingRule",
    "CssImageLayerRepetition": "CSSImageLayerRepetition",
    "CssImportRule": "CSSImportRule",
    "CssKeyframeRule": "CSSKeyframeRule",
    "CssKeyframesRule": "CSSKeyframesRule",
    "CssKeywordValue": "CSSKeywordValue",
    "CssMarginRule": "CSSMarginRule",
    "CssMediaRule": "CSSMediaRule",
    "CssNamespaceRule": "CSSNamespaceRule",
    "CssNumericValue": "CSSNumericValue",
    "CssPageRule": "CSSPageRule",
    "CssPerspective": "CSSPerspective",
    "CssPositionValue": "CSSPositionValue",
    "CssPrimitiveValue": "CSSPrimitiveValue",
    "CssPropertyRule": "CSSPropertyRule",
    "CssRotate": "CSSRotate",
    "CssScale": "CSSScale",
    "CssSkew": "CSSSkew",
    "CssStyleValue": "CSSStyleValue",
    "CssSupportsRule": "CSSSupportsRule",
    "CssTransformComponent": "CSSTransformComponent",
    "CssTransformValue": "CSSTransformValue",
    "CssTranslate": "CSSTranslate",
    "CssUnitValue": "CSSUnitValue",
    "CssUnparsedValue": "CSSUnparsedValue",
    "CssValue": "CSSValue",
    "CssValueList": "CSSValueList",
    "CssVariableReferenceValue": "CSSVariableReferenceValue",
    "CssFontFaceDescriptors": "CSSFontFaceDescriptors",
    "CssFontFeatureValuesMap": "CSSFontFeatureValuesMap",
    "CssPageDescriptors": "CSSPageDescriptors",
    "CssStyleProperties": "CSSStyleProperties",
    "ElementCssInlineStyle": "ElementCSSInlineStyle",
    "XmlDocument": "XMLDocument",
    "XmlHttpRequest": "XMLHttpRequest",
    "XmlHttpRequestEventTarget": "XMLHttpRequestEventTarget",
    "XmlHttpRequestUpload": "XMLHttpRequestUpload",
    "XmlSerializer": "XMLSerializer",
    "UiEvent": "UIEvent",
    "RtcCertificate": "RTCCertificate",
    "RtcDataChannel": "RTCDataChannel",
    "RtcDataChannelEvent": "RTCDataChannelEvent",
    "RtcDtlsTransport": "RTCDtlsTransport",
    "RtcEncodedAudioFrame": "RTCEncodedAudioFrame",
    "RtcEncodedVideoFrame": "RTCEncodedVideoFrame",
    "RtcError": "RTCError",
    "RtcErrorEvent": "RTCErrorEvent",
    "RtcIceCandidate": "RTCIceCandidate",
    "RtcIceCandidatePair": "RTCIceCandidatePair",
    "RtcIceTransport": "RTCIceTransport",
    "RtcPeerConnection": "RTCPeerConnection",
    "RtcPeerConnectionIceErrorEvent": "RTCPeerConnectionIceEvent",
    "RtcPeerConnectionIceEvent": "RTCPeerConnectionIceEvent",
    "RtcRtpReceiver": "RTCRtpReceiver",
    "RtcRtpScriptTransform": "RTCRtpScriptTransform",
    "RtcRtpSender": "RTCRtpSender",
    "RtcRtpTransceiver": "RTCRtpTransceiver",
    "RtcSctpTransport": "RTCSctpTransport",
    "RtcSessionDescription": "RTCSessionDescription",
    "RtcStatsReport": "RTCStatsReport",
    "RtcTrackEvent": "RTCTrackEvent",
    "RtcTransformEvent": "RTCTransformEvent",
    "RtcdtmfSender": "RTCDTMFSender",
    "RtcdtmfToneChangeEvent": "RTCDTMFToneChangeEvent",
    "Url": "URL",
    "UrlSearchParams": "URLSearchParams",
    "Origin": "Origin",
    "Module": "Module",
    "Instance": "Instance",
    "Table": "Table",
    "Memory": "Memory",
    "Global": "Global",
    "Exception": "Exception",
    "GeometryUtils": "GeometryUtils",
    "XPathNsResolver": "XPathNSResolver",
    "XsltProcessor": "XSLTProcessor",
    "HyperlinkElementUtils": "HyperlinkElementUtils",
    "SpeechGrammar": "SpeechGrammar",
    "SpeechGrammarList": "SpeechGrammarList",
    "SpeechRecognition": "SpeechRecognition",
    "SpeechRecognitionErrorEvent": "SpeechRecognitionErrorEvent",
    "SpeechRecognitionEvent": "SpeechRecognitionEvent",
    "SpeechRecognitionPhrase": "SpeechRecognitionPhrase",
    "FetchLaterResult": "FetchLaterResult",
    "VisibilityStateEntry": "VisibilityStateEntry",
    "CommandEvent": "CommandEvent",
    "CloseWatcher": "CloseWatcher",
    "PopoverTargetAttributes": "PopoverTargetAttributes",
    "Navigation": "Navigation",
    "NavigationTransition": "NavigationTransition",
    "NavigateEvent": "NavigateEvent",
    "NavigationPrecommitController": "NavigationPrecommitController",
    "NavigationDestination": "NavigationDestination",
    "NavigationCurrentEntryChangeEvent": "NavigationCurrentEntryChangeEvent",
    "NotRestoredReasonDetails": "NotRestoredReasonDetails",
    "NotRestoredReasons": "NotRestoredReasons",
    "NavigatorId": "NavigatorID",
    "WorkerGlobalScope": "WorkerGlobalScope",
    "DedicatedWorkerGlobalScope": "DedicatedWorkerGlobalScope",
    "SharedWorkerGlobalScope": "SharedWorkerGlobalScope",
    "WorkerNavigator": "WorkerNavigator",
    "WorkerLocation": "WorkerLocation",
    "PerformanceTimingConfidence": "PerformanceTimingConfidence",
    "OnErrorEventHandlerRecord": "OnErrorEventHandlerNonNull",
    "OnBeforeUnloadEventHandlerRecord": "OnBeforeUnloadEventHandlerNonNull",
    "VoidFunctionRecord": "VoidFunction",
    "MessageEventTarget": "MessageEventTarget",
    "AudioTrackList": "AudioTrackList",
    "AudioTrack": "AudioTrack",
    "VideoTrackList": "VideoTrackList",
    "VideoTrack": "VideoTrack",
    "TextTrackCue": "TextTrackCue",
    "TextTrackList": "TextTrackList",
    "ReadableStreamByobReader": "ReadableStreamBYOBReader",
    "ReadableStreamByobRequest": "ReadableStreamBYOBRequest",
    "ClipboardChangeEvent": "ClipboardEvent",
}

# JavaScript/TypeScript reserved keywords
JS_RESERVED_WORDS = {
    "break", "case", "catch", "continue", "debugger", "default", "delete",
    "do", "else", "finally", "for", "function", "if", "in", "instanceof",
    "new", "return", "switch", "this", "throw", "try", "typeof", "var",
    "void", "while", "with", "class", "const", "enum", "export", "extends",
    "import", "super", "implements", "interface", "let", "package", "private",
    "protected", "public", "static", "yield", "null", "true", "false",
    "undefined", "NaN", "Infinity", "await", "async", "of", "get", "set",
    "arguments", "eval",
}


def correct_type_casing(name: str) -> str:
    """Correct the casing of a type name to match TypeScript DOM conventions."""
    if name in TYPE_NAME_CASING_OVERRIDES:
        return TYPE_NAME_CASING_OVERRIDES[name]
    return name
