#!/usr/bin/env python3
"""
Fetch W3C / WHATWG WebIDL specifications from the W3C WebRef repository.

Data source: https://github.com/w3c/webref  (curated branch)
  - The `curated` branch is auto-generated by the W3C toolchain and guarantees
    validity + consistency of every IDL extract.
  - Raw files live at:
      https://raw.githubusercontent.com/w3c/webref/curated/ed/idl/<spec>.idl
  - Covers all specs tracked by https://github.com/w3c/browser-specs

Downloaded IDL files are cached under scripts/idl-cache/ and are used by
scripts/webidl_to_wit.py to generate WIT interface files.

Usage:
    python scripts/fetch_w3c_idl.py             # fetch all configured specs
    python scripts/fetch_w3c_idl.py dom fetch   # fetch specific specs only
    python scripts/fetch_w3c_idl.py --list      # list all configured specs
"""

import argparse
import sys
import urllib.request
import urllib.error
from pathlib import Path

# ---------------------------------------------------------------------------
# Data source
# ---------------------------------------------------------------------------

WEBREF_BASE = (
    "https://raw.githubusercontent.com/w3c/webref/curated/ed/idl"
)

# Spec name → IDL file name in the webref repository.
# Keys are the short names used within this project; values are the filenames
# in the curated/ed/idl/ directory of w3c/webref.
SPECS: dict[str, str] = {
    # Core platform
    "dom":                  "dom.idl",
    "fetch":                "fetch.idl",
    "html":                 "html.idl",
    # Communication
    "websockets":           "websockets.idl",
    "xhr":                  "xhr.idl",
    # Storage
    "storage":              "storage.idl",
    "indexed-db":           "IndexedDB.idl",
    "cookie-store":         "cookiestore.idl",
    # Streams
    "streams":              "streams.idl",
    # Files
    "file-api":             "FileAPI.idl",
    # Workers
    "service-workers":      "service-workers.idl",
    # Observers
    "intersection-observer": "intersection-observer.idl",
    "resize-observer":      "resize-observer.idl",
    "mutation-observer":    None,   # folded into dom.idl
    # Animations
    "web-animations":       "web-animations.idl",
    # Geolocation
    "geolocation":          "geolocation.idl",
    # Screen / Visibility
    "page-visibility":      "page-visibility.idl",
    "screen-orientation":   "screen-orientation.idl",
    # WebGL (canvas ecosystem)
    "webgl1":               "webgl1.idl",
    "webgl2":               "webgl2.idl",
    # Permissions
    "permissions":          "permissions.idl",
    # Push / Notifications
    "notifications":        "notifications.idl",
    "push-api":             "push-api.idl",
}


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def make_url(filename: str) -> str:
    return f"{WEBREF_BASE}/{filename}"


def download(url: str, dest: Path, dry_run: bool = False) -> bool:
    """Download *url* to *dest*.  Returns True on success."""
    if dry_run:
        print(f"  [dry-run] would download {url}")
        return True

    dest.parent.mkdir(parents=True, exist_ok=True)

    req = urllib.request.Request(
        url, headers={"User-Agent": "tairitsu-webidl-fetcher/1.0"}
    )
    try:
        with urllib.request.urlopen(req, timeout=30) as resp:
            dest.write_bytes(resp.read())
        return True
    except urllib.error.HTTPError as exc:
        print(f"  [WARN] HTTP {exc.code} — {url}", file=sys.stderr)
        return False
    except urllib.error.URLError as exc:
        print(f"  [WARN] network error — {url} ({exc.reason})", file=sys.stderr)
        return False


# ---------------------------------------------------------------------------
# Main logic
# ---------------------------------------------------------------------------

def fetch_specs(
    names: list[str],
    cache_dir: Path,
    dry_run: bool = False,
    force: bool = False,
) -> dict[str, bool]:
    """Fetch the given spec names into *cache_dir*.

    Returns a dict mapping spec name → success flag.
    """
    results: dict[str, bool] = {}
    for name in names:
        filename = SPECS.get(name)
        if filename is None:
            # Some specs (e.g. mutation-observer) are folded into another spec.
            print(f"  [skip] {name!r} — IDL is embedded in another spec")
            results[name] = True
            continue

        dest = cache_dir / filename
        if dest.exists() and not force:
            print(f"  [cached] {name} → {dest.name}")
            results[name] = True
            continue

        url = make_url(filename)
        print(f"  fetching {name} … {url}")
        ok = download(url, dest, dry_run=dry_run)
        results[name] = ok
        if ok and not dry_run:
            size_kb = dest.stat().st_size / 1024
            print(f"    saved {dest.name}  ({size_kb:.1f} KB)")

    return results


def main() -> int:
    script_dir = Path(__file__).parent
    default_cache = script_dir / "idl-cache"

    parser = argparse.ArgumentParser(description=__doc__,
                                     formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument(
        "specs", nargs="*",
        help="Spec short-names to fetch (default: all configured specs)",
    )
    parser.add_argument(
        "--list", action="store_true",
        help="List all configured spec names and exit",
    )
    parser.add_argument(
        "--cache-dir", default=str(default_cache), metavar="DIR",
        help=f"Directory to store downloaded IDL files (default: {default_cache})",
    )
    parser.add_argument(
        "--force", action="store_true",
        help="Re-download even if the file already exists in the cache",
    )
    parser.add_argument(
        "--dry-run", action="store_true",
        help="Print what would be downloaded without actually downloading",
    )
    args = parser.parse_args()

    if args.list:
        print("Configured specs:")
        for name, filename in sorted(SPECS.items()):
            note = "(embedded in another spec)" if filename is None else filename
            print(f"  {name:<30} {note}")
        return 0

    cache_dir = Path(args.cache_dir)
    names = args.specs if args.specs else list(SPECS.keys())

    # Validate requested spec names
    unknown = [n for n in names if n not in SPECS]
    if unknown:
        print(f"[ERROR] Unknown spec name(s): {', '.join(unknown)}", file=sys.stderr)
        print(f"Run with --list to see all configured specs.", file=sys.stderr)
        return 1

    print(f"Cache directory: {cache_dir}")
    print(f"Fetching {len(names)} spec(s)…")
    print()

    results = fetch_specs(names, cache_dir, dry_run=args.dry_run, force=args.force)

    ok = sum(1 for v in results.values() if v)
    fail = len(results) - ok
    print()
    if fail:
        print(f"[WARN] {ok}/{len(results)} specs fetched successfully; "
              f"{fail} failed (network issues or spec not yet in webref)")
    else:
        print(f"[OK] All {ok} spec(s) fetched successfully")

    return 0 if fail == 0 else 1


if __name__ == "__main__":
    sys.exit(main())
