/**
 * @tairitsu/browser-glue/generated
 *
 * Auto-generated TypeScript glue code for browser WIT interfaces.
 *
 * Generated by: scripts/generate_browser_glue.py
 * Source: packages/browser-worlds/wit/generated/*.wit
 *
 * DO NOT EDIT MANUALLY - regenerate with: just glue-gen
 *
 * ## Package layout
 *
 * - `./auth` — `tairitsu-browser:auth` (5 interfaces)
 * - `./canvas` — `tairitsu-browser:canvas` (20 interfaces)
 * - `./crypto` — `tairitsu-browser:crypto` (3 interfaces)
 * - `./css` — `tairitsu-browser:css` (44 interfaces)
 * - `./device` — `tairitsu-browser:device` (12 interfaces)
 * - `./dom` — `tairitsu-browser:dom` (34 interfaces)
 * - `./events` — `tairitsu-browser:events` (15 interfaces)
 * - `./fetch` — `tairitsu-browser:fetch` (25 interfaces)
 * - `./html` — `tairitsu-browser:html` (1 interfaces)
 * - `./media` — `tairitsu-browser:media` (29 interfaces)
 * - `./notifications` — `tairitsu-browser:notifications` (4 interfaces)
 * - `./observers` — `tairitsu-browser:observers` (5 interfaces)
 * - `./payments` — `tairitsu-browser:payments` (4 interfaces)
 * - `./performance` — `tairitsu-browser:performance` (11 interfaces)
 * - `./permissions` — `tairitsu-browser:permissions` (2 interfaces)
 * - `./service-workers` — `tairitsu-browser:service-workers` (2 interfaces)
 * - `./storage` — `tairitsu-browser:storage` (2 interfaces)
 * - `./url` — `tairitsu-browser:url` (2 interfaces)
 * - `./wasm` — `tairitsu-browser:wasm` (6 interfaces)
 * - `./webrtc` — `tairitsu-browser:webrtc` (20 interfaces)
 * - `./websocket` — `tairitsu-browser:websocket` (2 interfaces)
 * - `./workers` — `tairitsu-browser:workers` (12 interfaces)
 */

// Re-export all generated modules
export * as auth from "./generated/authGlue.js";
export * as canvas from "./generated/canvasGlue.js";
export * as crypto from "./generated/cryptoGlue.js";
export * as css from "./generated/cssGlue.js";
export * as device from "./generated/deviceGlue.js";
export * as dom from "./generated/domGlue.js";
export * as events from "./generated/eventsGlue.js";
export * as fetch from "./generated/fetchGlue.js";
export * as html from "./generated/htmlGlue.js";
export * as media from "./generated/mediaGlue.js";
export * as notifications from "./generated/notificationsGlue.js";
export * as observers from "./generated/observersGlue.js";
export * as payments from "./generated/paymentsGlue.js";
export * as performance from "./generated/performanceGlue.js";
export * as permissions from "./generated/permissionsGlue.js";
export * as serviceworkers from "./generated/serviceworkersGlue.js";
export * as storage from "./generated/storageGlue.js";
export * as url from "./generated/urlGlue.js";
export * as wasm from "./generated/wasmGlue.js";
export * as webrtc from "./generated/webrtcGlue.js";
export * as websocket from "./generated/websocketGlue.js";
export * as workers from "./generated/workersGlue.js";

// Statistics
export const GLUE_STATS = {
  totalDomains: 22,
  totalInterfaces: 260,
  totalFunctions: 2446,
  generatedAt: "2026-03-19T23:38:03.066246",
};
