/**
 * @tairitsu/browser-glue/generated
 *
 * Auto-generated TypeScript glue code for browser WIT interfaces.
 *
 * Generated by: scripts/generate_browser_glue.py
 * Source: packages/browser-worlds/wit/generated/*.wit
 *
 * DO NOT EDIT MANUALLY - regenerate with: just glue-gen
 *
 * ## Package layout
 *
 * - `./auth` — `tairitsu-browser:auth` (5 interfaces)
 * - `./canvas` — `tairitsu-browser:canvas` (20 interfaces)
 * - `./crypto` — `tairitsu-browser:crypto` (3 interfaces)
 * - `./css` — `tairitsu-browser:css` (44 interfaces)
 * - `./device` — `tairitsu-browser:device` (12 interfaces)
 * - `./dom` — `tairitsu-browser:dom` (34 interfaces)
 * - `./events` — `tairitsu-browser:events` (15 interfaces)
 * - `./fetch` — `tairitsu-browser:fetch` (25 interfaces)
 * - `./html` — `tairitsu-browser:html` (1 interfaces)
 * - `./media` — `tairitsu-browser:media` (29 interfaces)
 * - `./notifications` — `tairitsu-browser:notifications` (4 interfaces)
 * - `./observers` — `tairitsu-browser:observers` (5 interfaces)
 * - `./payments` — `tairitsu-browser:payments` (4 interfaces)
 * - `./performance` — `tairitsu-browser:performance` (11 interfaces)
 * - `./permissions` — `tairitsu-browser:permissions` (2 interfaces)
 * - `./service-workers` — `tairitsu-browser:service-workers` (2 interfaces)
 * - `./storage` — `tairitsu-browser:storage` (2 interfaces)
 * - `./url` — `tairitsu-browser:url` (2 interfaces)
 * - `./wasm` — `tairitsu-browser:wasm` (6 interfaces)
 * - `./webrtc` — `tairitsu-browser:webrtc` (20 interfaces)
 * - `./websocket` — `tairitsu-browser:websocket` (2 interfaces)
 * - `./workers` — `tairitsu-browser:workers` (12 interfaces)
 */

// Re-export all generated modules
export * as auth from "./generated/auth-glue.js";
export * as canvas from "./generated/canvas-glue.js";
export * as crypto from "./generated/crypto-glue.js";
export * as css from "./generated/css-glue.js";
export * as device from "./generated/device-glue.js";
export * as dom from "./generated/dom-glue.js";
export * as events from "./generated/events-glue.js";
export * as fetch from "./generated/fetch-glue.js";
export * as html from "./generated/html-glue.js";
export * as media from "./generated/media-glue.js";
export * as notifications from "./generated/notifications-glue.js";
export * as observers from "./generated/observers-glue.js";
export * as payments from "./generated/payments-glue.js";
export * as performance from "./generated/performance-glue.js";
export * as permissions from "./generated/permissions-glue.js";
export * as serviceworkers from "./generated/service-workers-glue.js";
export * as storage from "./generated/storage-glue.js";
export * as url from "./generated/url-glue.js";
export * as wasm from "./generated/wasm-glue.js";
export * as webrtc from "./generated/webrtc-glue.js";
export * as websocket from "./generated/websocket-glue.js";
export * as workers from "./generated/workers-glue.js";

// Statistics
export const GLUE_STATS = {
  totalDomains: 22,
  totalInterfaces: 260,
  totalFunctions: 2446,
  generatedAt: "2026-03-19T19:42:22.360541",
};
