/**
 * wasm glue — implements the `tairitsu-browser:wasm` WIT import interfaces.
 *
 * Auto-generated from: /mnt/sdb1/tairitsu/packages/browser-worlds/wit/generated/wasm.wit
 * Generated by: scripts/generate_browser_glue.py
 *
 * DO NOT EDIT MANUALLY - regenerate with: just glue-gen
 *
 * All browser objects are represented as opaque bigint handles.
 */

// ---------------------------------------------------------------------------
// Custom type definitions
// ---------------------------------------------------------------------------

/** Type definition for DOMTokenListValue */
export type DOMTokenListValue = string;

/** Type definition for EventHandlerRecord */
export type EventHandlerRecord = any;

/** Type definition for WebGLObject */
export type WebGLObject = any;

/** Type definition for u64 */
export type u64 = bigint;

/** Type definition for RTCDataChannelBinaryType */
export type RTCDataChannelBinaryType = "blob" | "arraybuffer";

/** Type definition for CSSFontFaceDescriptors */
export type CSSFontFaceDescriptors = any;

/** Type definition for CSSFontFeatureValuesMap */
export type CSSFontFeatureValuesMap = any;

/** Type definition for OnBeforeUnloadEventHandlerRecord */
export type OnBeforeUnloadEventHandlerRecord = OnBeforeUnloadEventHandlerNonNull | null;

/** Type definition for OnErrorEventHandlerRecord */
export type OnErrorEventHandlerRecord = OnErrorEventHandlerNonNull | null;

/** Type definition for VoidFunctionRecord */
export type VoidFunctionRecord = VoidFunction;

/** Type definition for EventHandler */
export type EventHandler = (this: any, ev: any) => any;

/** Type definition for GeometryUtils */
export type GeometryUtils = any;

/** Type definition for HyperlinkElementUtils */
export type HyperlinkElementUtils = any;

/** Type definition for PopoverTargetAttributes */
export type PopoverTargetAttributes = any;

/** Type definition for CSSPageDescriptors */
export type CSSPageDescriptors = any;

/** Type definition for CSSMarginRule */
export type CSSMarginRule = CSSRule;

/** Type definition for CSSStyleProperties */
export type CSSStyleProperties = Record<string, string>;

/** Type definition for Origin */
export type Origin = string;

/** Type definition for FetchLaterResult */
export type FetchLaterResult = any;

/** Type definition for NotRestoredReasonDetails */
export type NotRestoredReasonDetails = any;

/** Type definition for NotRestoredReasons */
export type NotRestoredReasons = any;

/** Type definition for DeviceChangeEvent */
export type DeviceChangeEvent = Event;

/** Type definition for ChapterInformation */
export type ChapterInformation = any;

/** Type definition for PerformanceTimingConfidence */
export type PerformanceTimingConfidence = any;

/** Type definition for NotificationEvent */
export type NotificationEvent = Event;

/** Type definition for VisibilityStateEntry */
export type VisibilityStateEntry = PerformanceEntry;

/** Type definition for CommandEvent */
export type CommandEvent = Event;

/** Type definition for CloseWatcher */
export type CloseWatcher = EventTarget;

/** Type definition for CaptureController */
export type CaptureController = any;

/** Type definition for Navigation */
export type Navigation = any;

/** Type definition for NavigationTransition */
export type NavigationTransition = any;

/** Type definition for NavigateEvent */
export type NavigateEvent = Event;

/** Type definition for NavigationPrecommitController */
export type NavigationPrecommitController = any;

/** Type definition for NavigationDestination */
export type NavigationDestination = any;

/** Type definition for NavigationCurrentEntryChangeEvent */
export type NavigationCurrentEntryChangeEvent = Event;

/** Type definition for BatteryManager */
export type BatteryManager = any;

/** Type definition for AudioTrackList */
export type AudioTrackList = any;

/** Type definition for AudioTrack */
export type AudioTrack = any;

/** Type definition for VideoTrackList */
export type VideoTrackList = any;

/** Type definition for VideoTrack */
export type VideoTrack = any;

/** Type definition for WorkerGlobalScope */
export type WorkerGlobalScope = any;

/** Type definition for DedicatedWorkerGlobalScope */
export type DedicatedWorkerGlobalScope = any;

/** Type definition for SharedWorkerGlobalScope */
export type SharedWorkerGlobalScope = any;

/** Type definition for WorkerNavigator */
export type WorkerNavigator = any;

/** Type definition for WorkerLocation */
export type WorkerLocation = any;

/** Type definition for ServiceWorkerGlobalScope */
export type ServiceWorkerGlobalScope = any;

/** Type definition for Client */
export type Client = any;

/** Type definition for WindowClient */
export type WindowClient = any;

/** Type definition for Clients */
export type Clients = any;

/** Type definition for ExtendableEvent */
export type ExtendableEvent = Event;

/** Type definition for InstallEvent */
export type InstallEvent = Event;

/** Type definition for FetchEvent */
export type FetchEvent = Event;

/** Type definition for ExtendableMessageEvent */
export type ExtendableMessageEvent = MessageEvent;

/** Type definition for SpeechRecognition */
export type SpeechRecognition = any;

/** Type definition for SpeechRecognitionErrorEvent */
export type SpeechRecognitionErrorEvent = Event;

/** Type definition for SpeechRecognitionEvent */
export type SpeechRecognitionEvent = Event;

/** Type definition for SpeechGrammar */
export type SpeechGrammar = any;

/** Type definition for SpeechGrammarList */
export type SpeechGrammarList = any;

/** Type definition for SpeechRecognitionPhrase */
export type SpeechRecognitionPhrase = any;

/** Type definition for Module */
export type Module = typeof WebAssembly.Module;

/** Type definition for Instance */
export type Instance = typeof WebAssembly.Instance;

/** Type definition for Memory */
export type Memory = typeof WebAssembly.Memory;

/** Type definition for Table */
export type Table = typeof WebAssembly.Table;

/** Type definition for Global */
export type Global = typeof WebAssembly.Global;

/** Type definition for Exception */
export type Exception = any;

/** Type definition for HTMLString */
export type HTMLString = string;

/** Type definition for MediaText */
export type MediaText = string;

/** Type definition for HTMLHyperlinkHref */
export type HTMLHyperlinkHref = string;

/** Type definition for LocationHref */
export type LocationHref = string;

/** Type definition for URLHref */
export type URLHref = string;


// ---------------------------------------------------------------------------
// Async handle table for Promise-based operations
// ---------------------------------------------------------------------------

let _nextAsyncHandle = 1n;

interface AsyncHandle<T> {
  promise: Promise<T>;
  result: { ok: true; value: T } | { ok: false; error: string } | null;
}

const _asyncHandles = new Map<bigint, AsyncHandle<unknown>>();

// ---------------------------------------------------------------------------
// Synthetic handle tables for primitive/utility types
// ---------------------------------------------------------------------------

/** Handle table for any values */
const _anyHandles = new Map<bigint, any>();
let _nextAny = 1n;

// ---------------------------------------------------------------------------
// Helper functions for handle lookups
// ---------------------------------------------------------------------------

/** Lookup a any value by handle. */
function lookupAny(handle: bigint): any {
  const obj = _anyHandles.get(handle);
  if (obj === undefined) {
    throw new Error(`any handle ${handle} not found`);
  }
  return obj!;
}

/** Lookup an optional any value by handle. */
function lookupOptionAny(handle: bigint | undefined): any | null {
  if (handle === undefined || handle === 0n) {
    return null;
  }
  return _anyHandles.get(handle) ?? null;
}

// ---------------------------------------------------------------------------
// WIT interface: module
// ---------------------------------------------------------------------------

/** Type alias */
export type ModuleHandle = bigint;

/** Handle table for WebAssembly.Module instances */
const _moduleHandles = new Map<bigint, WebAssembly.Module>();
let _nextModule = 1n;

/** Lookup a WebAssembly.Module by handle, throwing if not found. */
function lookupModule(handle: bigint): WebAssembly.Module {
  const obj = _moduleHandles.get(handle);
  if (!obj) {
    throw new Error(`WebAssembly.Module handle ${handle} not found`);
  }
  return obj!;
}

/** Lookup an optional WebAssembly.Module by handle. */
function lookupOptionModule(handle: bigint | undefined): WebAssembly.Module | null {
  if (handle === undefined || handle === 0n) {
    return null;
  }
  return _moduleHandles.get(handle) ?? null;
}
/**
 * `exports()` operation.
 */
export function exports(moduleObject: bigint): (bigint)[] {
  return (globalThis as any).WebAssembly.Module.exports(moduleObject);
}

/**
 * `imports()` operation.
 */
export function imports(moduleObject: bigint): (bigint)[] {
  return (globalThis as any).WebAssembly.Module.imports(moduleObject);
}

/**
 * `custom-sections()` operation.
 */
export function customSections(moduleObject: bigint, sectionName: string): (Uint8Array)[] {
  return (globalThis as any).WebAssembly.Module.customSections(moduleObject, sectionName);
}

// ---------------------------------------------------------------------------
// WIT interface: instance
// ---------------------------------------------------------------------------

/** Type alias */
export type InstanceHandle = bigint;

/** Handle table for Instance instances */
const _instanceHandles = new Map<bigint, Instance>();
let _nextInstance = 1n;

/** Lookup a Instance by handle, throwing if not found. */
function lookupInstance(handle: bigint): Instance {
  const obj = _instanceHandles.get(handle);
  if (!obj) {
    throw new Error(`Instance handle ${handle} not found`);
  }
  return obj!;
}

/** Lookup an optional Instance by handle. */
function lookupOptionInstance(handle: bigint | undefined): Instance | null {
  if (handle === undefined || handle === 0n) {
    return null;
  }
  return _instanceHandles.get(handle) ?? null;
}
/**
 * `get-exports()` operation.
 */
export function getExports(self: bigint): bigint {
  const obj = lookupInstance(self);
  const _callResult = (obj as any).exports;
  const handle = _nextAny++;
  _anyHandles.set(handle, _callResult);
  return handle;
}

// ---------------------------------------------------------------------------
// WIT interface: memory
// ---------------------------------------------------------------------------

/** Type alias */
export type MemoryHandle = bigint;

/** Handle table for Memory instances */
const _memoryHandles = new Map<bigint, Memory>();
let _nextMemory = 1n;

/** Lookup a Memory by handle, throwing if not found. */
function lookupMemory(handle: bigint): Memory {
  const obj = _memoryHandles.get(handle);
  if (!obj) {
    throw new Error(`Memory handle ${handle} not found`);
  }
  return obj!;
}

/** Lookup an optional Memory by handle. */
function lookupOptionMemory(handle: bigint | undefined): Memory | null {
  if (handle === undefined || handle === 0n) {
    return null;
  }
  return _memoryHandles.get(handle) ?? null;
}
/**
 * `grow()` operation.
 */
export function MemoryGrow(self: bigint, delta: bigint): bigint {
  const obj = lookupMemory(self);
  return (obj as any).grow(delta);
}

/**
 * `to-fixed-length-buffer()` operation.
 */
export function toFixedLengthBuffer(self: bigint): Uint8Array {
  const obj = lookupMemory(self);
  return (obj as any).toFixedLengthBuffer();
}

/**
 * `to-resizable-buffer()` operation.
 */
export function toResizableBuffer(self: bigint): Uint8Array {
  const obj = lookupMemory(self);
  return (obj as any).toResizableBuffer();
}

/**
 * `get-buffer()` operation.
 */
export function getBuffer(self: bigint): Uint8Array {
  const obj = lookupMemory(self);
  return (obj as any).buffer;
}

// ---------------------------------------------------------------------------
// WIT interface: table
// ---------------------------------------------------------------------------

/** Type alias */
export type TableHandle = bigint;

/** Handle table for Table instances */
const _tableHandles = new Map<bigint, Table>();
let _nextTable = 1n;

/** Lookup a Table by handle, throwing if not found. */
function lookupTable(handle: bigint): Table {
  const obj = _tableHandles.get(handle);
  if (!obj) {
    throw new Error(`Table handle ${handle} not found`);
  }
  return obj!;
}

/** Lookup an optional Table by handle. */
function lookupOptionTable(handle: bigint | undefined): Table | null {
  if (handle === undefined || handle === 0n) {
    return null;
  }
  return _tableHandles.get(handle) ?? null;
}
/**
 * `grow()` operation.
 */
export function TableGrow(self: bigint, delta: bigint, value: string | undefined): bigint {
  const obj = lookupTable(self);
  return (obj as any).grow(delta, value);
}

/**
 * `get()` operation.
 *
 * Async operation: returns request ID, poll with `pollGet()`
 */
export function _get(self: bigint, index: bigint): bigint {
  const requestId = _nextAsyncHandle++;
  const obj = lookupTable(self);
  const promise = (obj as any).get(index)
    .then((result: unknown) => {
      const entry = _asyncHandles.get(requestId);
      if (entry) {
        entry.result = { ok: true, value: result };
      }
    })
    .catch((err: Error) => {
      const entry = _asyncHandles.get(requestId);
      if (entry) {
        entry.result = { ok: false, error: err.message };
      }
    });

  _asyncHandles.set(requestId, { promise, result: null });
  return requestId;
}

/**
 * Poll an async `_get()` operation.
 * Returns undefined if still pending, or the result if complete.
 */
export function pollGet(requestId: bigint): { ok: true } | { ok: false; error: string } | undefined {
  const entry = _asyncHandles.get(requestId);
  if (!entry) {
    return { ok: false, error: `Unknown request ID ${requestId}` };
  }
  return entry.result ?? undefined;
}

/**
 * `set()` operation.
 */
export function _set(self: bigint, index: bigint, value: string | undefined): void {
  const obj = lookupTable(self);
  (obj as any).set(index, value);
}

/**
 * `get-length()` operation.
 */
export function getLength(self: bigint): bigint {
  const obj = lookupTable(self);
  return BigInt(obj.length);
}

// ---------------------------------------------------------------------------
// WIT interface: global
// ---------------------------------------------------------------------------

/** Type alias */
export type GlobalHandle = bigint;

/** Handle table for Global instances */
const _globalHandles = new Map<bigint, Global>();
let _nextGlobal = 1n;

/** Lookup a Global by handle, throwing if not found. */
function lookupGlobal(handle: bigint): Global {
  const obj = _globalHandles.get(handle);
  if (!obj) {
    throw new Error(`Global handle ${handle} not found`);
  }
  return obj!;
}

/** Lookup an optional Global by handle. */
function lookupOptionGlobal(handle: bigint | undefined): Global | null {
  if (handle === undefined || handle === 0n) {
    return null;
  }
  return _globalHandles.get(handle) ?? null;
}
/**
 * `value-of()` operation.
 */
export function valueOf(self: bigint): string {
  const obj = lookupGlobal(self);
  return (obj as any).valueOf();
}

/**
 * `get-value()` operation.
 */
export function getValue(self: bigint): bigint {
  const obj = lookupGlobal(self);
  const _callResult = (obj as any).value;
  const handle = _nextAny++;
  _anyHandles.set(handle, _callResult);
  return handle;
}

/**
 * `set-value()` operation.
 */
export function setValue(self: bigint, value: string): void {
  const obj = lookupGlobal(self);
  (obj as any).value = value;
}

// ---------------------------------------------------------------------------
// WIT interface: exception
// ---------------------------------------------------------------------------

/** Type alias */
export type ExceptionHandle = bigint;

/** Handle table for Exception instances */
const _exceptionHandles = new Map<bigint, Exception>();
let _nextException = 1n;

/** Lookup a Exception by handle, throwing if not found. */
function lookupException(handle: bigint): Exception {
  const obj = _exceptionHandles.get(handle);
  if (!obj) {
    throw new Error(`Exception handle ${handle} not found`);
  }
  return obj!;
}

/** Lookup an optional Exception by handle. */
function lookupOptionException(handle: bigint | undefined): Exception | null {
  if (handle === undefined || handle === 0n) {
    return null;
  }
  return _exceptionHandles.get(handle) ?? null;
}
/**
 * `get-arg()` operation.
 */
export function getArg(self: bigint, exceptionTag: bigint, index: number): string {
  const obj = lookupException(self);
  return obj.arg;
}

/**
 * `is()` operation.
 */
export function is(self: bigint, exceptionTag: bigint): boolean {
  const obj = lookupException(self);
  return obj.is(exceptionTag);
}

/**
 * `get-stack()` operation.
 */
export function getStack(self: bigint): string {
  const obj = lookupException(self);
  return obj.stack;
}

// ---------------------------------------------------------------------------
// Exports
// ---------------------------------------------------------------------------

export default {
  exports,
  imports,
  customSections,
  getExports,
  MemoryGrow,
  toFixedLengthBuffer,
  toResizableBuffer,
  getBuffer,
  TableGrow,
  _get,
  pollGet,
  _set,
  getLength,
  valueOf,
  getValue,
  setValue,
  getArg,
  is,
  getStack
};
