/**
 * web-animations glue — implements the `tairitsu-browser:web-animations` WIT import interfaces.
 *
 * Auto-generated from: /mnt/sdb1/tairitsu/packages/browser-worlds/wit/generated/web-animations.wit
 * Generated by: scripts/generate_browser_glue.py
 *
 * DO NOT EDIT MANUALLY - regenerate with: just glue-gen
 *
 * All browser objects are represented as opaque bigint handles.
 */

// ---------------------------------------------------------------------------
// Custom type definitions
// ---------------------------------------------------------------------------

/** Type definition for DOMTokenListValue */
export type DOMTokenListValue = string;

/** Type definition for EventHandlerRecord */
export type EventHandlerRecord = any;

/** Type definition for WebGLObject */
export type WebGLObject = any;

/** Type definition for u64 */
export type u64 = bigint;

/** Type definition for RTCDataChannelBinaryType */
export type RTCDataChannelBinaryType = "blob" | "arraybuffer";

/** Type definition for CSSFontFaceDescriptors */
export type CSSFontFaceDescriptors = any;

/** Type definition for CSSFontFeatureValuesMap */
export type CSSFontFeatureValuesMap = any;

/** Type definition for OnBeforeUnloadEventHandlerRecord */
export type OnBeforeUnloadEventHandlerRecord = OnBeforeUnloadEventHandlerNonNull | null;

/** Type definition for OnErrorEventHandlerRecord */
export type OnErrorEventHandlerRecord = OnErrorEventHandlerNonNull | null;

/** Type definition for VoidFunctionRecord */
export type VoidFunctionRecord = VoidFunction;

/** Type definition for GeometryUtils */
export type GeometryUtils = any;

/** Type definition for HyperlinkElementUtils */
export type HyperlinkElementUtils = any;

/** Type definition for PopoverTargetAttributes */
export type PopoverTargetAttributes = any;

/** Type definition for CSSPageDescriptors */
export type CSSPageDescriptors = any;

/** Type definition for CSSMarginRule */
export type CSSMarginRule = CSSRule;

/** Type definition for CSSStyleProperties */
export type CSSStyleProperties = Record<string, string>;

/** Type definition for Origin */
export type Origin = string;

/** Type definition for FetchLaterResult */
export type FetchLaterResult = any;

/** Type definition for NotRestoredReasonDetails */
export type NotRestoredReasonDetails = any;

/** Type definition for NotRestoredReasons */
export type NotRestoredReasons = any;

/** Type definition for DeviceChangeEvent */
export type DeviceChangeEvent = Event;

/** Type definition for ChapterInformation */
export type ChapterInformation = any;

/** Type definition for PerformanceTimingConfidence */
export type PerformanceTimingConfidence = any;

/** Type definition for NotificationEvent */
export type NotificationEvent = Event;

/** Type definition for VisibilityStateEntry */
export type VisibilityStateEntry = PerformanceEntry;

/** Type definition for CommandEvent */
export type CommandEvent = Event;

/** Type definition for CloseWatcher */
export type CloseWatcher = EventTarget;

/** Type definition for CaptureController */
export type CaptureController = any;

/** Type definition for Navigation */
export type Navigation = any;

/** Type definition for NavigationTransition */
export type NavigationTransition = any;

/** Type definition for NavigateEvent */
export type NavigateEvent = Event;

/** Type definition for NavigationPrecommitController */
export type NavigationPrecommitController = any;

/** Type definition for NavigationDestination */
export type NavigationDestination = any;

/** Type definition for NavigationCurrentEntryChangeEvent */
export type NavigationCurrentEntryChangeEvent = Event;

/** Type definition for BatteryManager */
export type BatteryManager = any;

/** Type definition for AudioTrackList */
export type AudioTrackList = any;

/** Type definition for AudioTrack */
export type AudioTrack = any;

/** Type definition for VideoTrackList */
export type VideoTrackList = any;

/** Type definition for VideoTrack */
export type VideoTrack = any;

/** Type definition for WorkerGlobalScope */
export type WorkerGlobalScope = any;

/** Type definition for DedicatedWorkerGlobalScope */
export type DedicatedWorkerGlobalScope = any;

/** Type definition for SharedWorkerGlobalScope */
export type SharedWorkerGlobalScope = any;

/** Type definition for WorkerNavigator */
export type WorkerNavigator = any;

/** Type definition for WorkerLocation */
export type WorkerLocation = any;

/** Type definition for ServiceWorkerGlobalScope */
export type ServiceWorkerGlobalScope = any;

/** Type definition for Client */
export type Client = any;

/** Type definition for WindowClient */
export type WindowClient = any;

/** Type definition for Clients */
export type Clients = any;

/** Type definition for ExtendableEvent */
export type ExtendableEvent = Event;

/** Type definition for InstallEvent */
export type InstallEvent = Event;

/** Type definition for FetchEvent */
export type FetchEvent = Event;

/** Type definition for ExtendableMessageEvent */
export type ExtendableMessageEvent = MessageEvent;

/** Type definition for SpeechRecognition */
export type SpeechRecognition = any;

/** Type definition for SpeechRecognitionErrorEvent */
export type SpeechRecognitionErrorEvent = Event;

/** Type definition for SpeechRecognitionEvent */
export type SpeechRecognitionEvent = Event;

/** Type definition for SpeechGrammar */
export type SpeechGrammar = any;

/** Type definition for SpeechGrammarList */
export type SpeechGrammarList = any;

/** Type definition for SpeechRecognitionPhrase */
export type SpeechRecognitionPhrase = any;

/** Type definition for Module */
export type Module = typeof WebAssembly.Module;

/** Type definition for Instance */
export type Instance = typeof WebAssembly.Instance;

/** Type definition for Memory */
export type Memory = typeof WebAssembly.Memory;

/** Type definition for Table */
export type Table = typeof WebAssembly.Table;

/** Type definition for Global */
export type Global = typeof WebAssembly.Global;

/** Type definition for Exception */
export type Exception = any;

/** Type definition for HTMLString */
export type HTMLString = string;

/** Type definition for MediaText */
export type MediaText = string;

/** Type definition for HTMLHyperlinkHref */
export type HTMLHyperlinkHref = string;

/** Type definition for LocationHref */
export type LocationHref = string;

/** Type definition for URLHref */
export type URLHref = string;


// ---------------------------------------------------------------------------
// Async handle table for Promise-based operations
// ---------------------------------------------------------------------------

let _nextAsyncHandle = 1n;

interface AsyncHandle<T> {
  promise: Promise<T>;
  result: { ok: true; value: T } | { ok: false; error: string } | null;
}

const _asyncHandles = new Map<bigint, AsyncHandle<unknown>>();

// ---------------------------------------------------------------------------
// WIT interface: animation
// ---------------------------------------------------------------------------

/** Type alias */
export type AnimationHandle = bigint;

/** Handle table for Animation instances */
const _animationHandles = new Map<bigint, Animation>();
let _nextAnimation = 1n;

/** Lookup a Animation by handle, throwing if not found. */
function lookupAnimation(handle: bigint): Animation {
  const obj = _animationHandles.get(handle);
  if (!obj) {
    throw new Error(`Animation handle ${handle} not found`);
  }
  return obj!;
}

/** Lookup an optional Animation by handle. */
function lookupOptionAnimation(handle: bigint | undefined): Animation | null {
  if (handle === undefined || handle === 0n) {
    return null;
  }
  return _animationHandles.get(handle) ?? null;
}
/**
 * `get-id()` operation.
 */
export function getId(handle: bigint): string {
  const obj = lookupAnimation(handle);
  return (obj as any).id;
}

/**
 * `set-id()` operation.
 */
export function setId(handle: bigint, value: string): void {
  const obj = lookupAnimation(handle);
  (obj as any).id = value;
}

/**
 * `get-playback-rate()` operation.
 */
export function getPlaybackRate(handle: bigint): number {
  const obj = lookupAnimation(handle);
  return (obj as any).playbackRate;
}

/**
 * `set-playback-rate()` operation.
 */
export function setPlaybackRate(handle: bigint, value: number): void {
  const obj = lookupAnimation(handle);
  (obj as any).playbackRate = value;
}

/**
 * `pending()` operation.
 */
export function pending(handle: bigint): boolean {
  const obj = lookupAnimation(handle);
  return (obj as any).pending();
}

/**
 * `cancel()` operation.
 */
export function cancel(handle: bigint): void {
  const obj = lookupAnimation(handle);
  obj.cancel();
}

/**
 * `finish()` operation.
 */
export function finish(handle: bigint): void {
  const obj = lookupAnimation(handle);
  obj.finish();
}

/**
 * `play()` operation.
 */
export function play(handle: bigint): void {
  const obj = lookupAnimation(handle);
  obj.play();
}

/**
 * `pause()` operation.
 */
export function pause(handle: bigint): void {
  const obj = lookupAnimation(handle);
  obj.pause();
}

/**
 * `update-playback-rate()` operation.
 */
export function updatePlaybackRate(handle: bigint, playbackRate: number): void {
  const obj = lookupAnimation(handle);
  obj.updatePlaybackRate(Number(playbackRate));
}

/**
 * `reverse()` operation.
 */
export function reverse(handle: bigint): void {
  const obj = lookupAnimation(handle);
  obj.reverse();
}

/**
 * `persist()` operation.
 *
 * Async operation: returns request ID, poll with `pollPersist()`
 */
export function persist(handle: bigint): bigint {
  const requestId = _nextAsyncHandle++;
  const obj = lookupAnimation(handle);
  const promise = (obj as any).persist()
    .then((result: unknown) => {
      const entry = _asyncHandles.get(requestId);
      if (entry) {
        entry.result = { ok: true, value: result };
      }
    })
    .catch((err: Error) => {
      const entry = _asyncHandles.get(requestId);
      if (entry) {
        entry.result = { ok: false, error: err.message };
      }
    });

  _asyncHandles.set(requestId, { promise, result: null });
  return requestId;
}

/**
 * Poll an async `persist()` operation.
 * Returns undefined if still pending, or the result if complete.
 */
export function pollPersist(requestId: bigint): { ok: true } | { ok: false; error: string } | undefined {
  const entry = _asyncHandles.get(requestId);
  if (!entry) {
    return { ok: false, error: `Unknown request ID ${requestId}` };
  }
  return entry.result ?? undefined;
}

/**
 * `commit-styles()` operation.
 */
export function commitStyles(handle: bigint): void {
  const obj = lookupAnimation(handle);
  obj.commitStyles();
}

// ---------------------------------------------------------------------------
// Exports
// ---------------------------------------------------------------------------

export default {
  getId,
  setId,
  getPlaybackRate,
  setPlaybackRate,
  pending,
  cancel,
  finish,
  play,
  pause,
  updatePlaybackRate,
  reverse,
  persist,
  pollPersist,
  commitStyles
};
