// @ts-nocheck
// Auto-generated by build_npm_glue_packages.py

// === document ===
export const document_exports = {
  createElement(localName) {
    const el = document.createElement(localName);
    return globalThis.__storeElement(el);
  },
  createTextNode(data) {
    const text = document.createTextNode(data);
    return globalThis.__storeText(text);
  },
  getBody() {
    return globalThis.__storeElement(document.body);
  },
};

// === element ===
export const element_exports = {
  setAttribute(self, qualifiedName, value) {
    const name = typeof qualifiedName === 'string' && qualifiedName.startsWith('r#')
      ? qualifiedName.slice(2)
      : qualifiedName;
    globalThis.__lookupElement(self).setAttribute(name, value);
  },
  removeAttribute(self, qualifiedName) {
    const name = typeof qualifiedName === 'string' && qualifiedName.startsWith('r#')
      ? qualifiedName.slice(2)
      : qualifiedName;
    globalThis.__lookupElement(self).removeAttribute(name);
  },
  getBoundingClientRect(element) {
    const el = globalThis.__elementHandles.get(element);
    if (!el) {
      return { x: 0, y: 0, width: 0, height: 0 };
    }
    const rect = el.getBoundingClientRect();
    return { x: rect.x, y: rect.y, width: rect.width, height: rect.height };
  },
  setInnerHtml(self, html) {
    globalThis.__lookupElement(self).innerHTML = html;
  },
  getAttribute(self, name) {
    return globalThis.__lookupElement(self).getAttribute(name);
  },
  getTagName(self) {
    return globalThis.__lookupElement(self).tagName || '';
  },
  getClassList(self) {
    return self;
  },
  getClientHeight(self) {
    return globalThis.__lookupElement(self).clientHeight || 0;
  },
  getScrollHeight(self) {
    return globalThis.__lookupElement(self).scrollHeight || 0;
  },
  getScrollTop(self) {
    return globalThis.__lookupElement(self).scrollTop || 0;
  },
  setScrollTop(self, value) {
    globalThis.__lookupElement(self).scrollTop = value;
  },
};

// === node ===
export const node_exports = {
  appendChild(self, child) {
    const parent = globalThis.__lookupNode(self);
    const childNode = globalThis.__lookupNode(child);
    const result = parent.appendChild(childNode);
    return globalThis.__storeNode(result);
  },
  removeChild(self, child) {
    const parent = globalThis.__lookupNode(self);
    const childNode = globalThis.__lookupNode(child);
    const result = parent.removeChild(childNode);
    return globalThis.__storeNode(result);
  },
  setTextContent(self, text) {
    globalThis.__lookupNode(self).textContent = text;
  },
  getTextContent(self) {
    return globalThis.__lookupNode(self).textContent || "";
  },
  getParentElement(self) {
    const el = globalThis.__lookupNode(self).parentElement;
    if (!el) return undefined;
    return globalThis.__elementHandles.get(el);
  },
  getFirstChild(self) {
    const node = globalThis.__lookupNode(self);
    const first = node.firstChild;
    if (!first) return undefined;
    return globalThis.__storeNode(first);
  },
};

// === nonElementParentNode ===
export const nonElementParentNode_exports = {
  getElementById(self, elementId) {
    const doc = globalThis.__documentHandles.get(self) || document;
    const el = doc.getElementById(elementId);
    return globalThis.__storeElement(el);
  },
};

// === parentNode ===
export const parentNode_exports = {
  querySelector(self, selectors) {
    const el = globalThis.__lookupElement(self);
    const result = el.querySelector(selectors);
    if (!result) return undefined;
    return globalThis.__storeElement(result);
  },
  querySelectorAll(self, selectors) {
    const el = globalThis.__lookupElement(self);
    const result = el.querySelectorAll(selectors);
    if (!globalThis.__nodeListHandles) {
      globalThis.__nodeListHandles = new Map();
      globalThis.__nextNodeList = 1n;
    }
    const handle = globalThis.__nextNodeList++;
    globalThis.__nodeListHandles.set(handle, result);
    return handle;
  },
};

// === Registry ===
export const INTERFACES = {
  "@tairitsu-glue/document": document_exports,
  "@tairitsu-glue/element": element_exports,
  "@tairitsu-glue/node": node_exports,
  "@tairitsu-glue/non-element-parent-node": nonElementParentNode_exports,
  "@tairitsu-glue/parent-node": parentNode_exports,
};
