[package]
authors = ["langyo <langyo.china@gmail.com>"]
name = "tairitsu-utils"

version = "0.1.0"
edition = "2021"
publish = false

[lib]
crate-type = ["rlib"]

[dependencies]
anyhow = "^1"
chrono = { version = "^0.4", features = [
  "serde",
  "wasmbind",
  "unstable-locales",
] }
log = "^0.4"
serde = { version = "^1", features = ["derive"] }
serde_json = { version = "^1" }
strum = { version = "^0.26", features = ["derive"] }
uuid = { version = "^1", features = [
  'v4',
  'fast-rng',
  'macro-diagnostics',
  'serde',
] }

bcrypt = "^0.15"
sea-orm = { version = "1.0.0-rc.4", features = ["proxy"] }
