// @ts-nocheck
// Auto-generated stub — delegates to browser-glue glue module

/**
 * storage glue — implements the `tairitsu-browser:storage` WIT import interfaces.
 *
 * Auto-generated from: /mnt/sdb1/tairitsu/packages/browser-glue/../../packages/browser-worlds/wit/generated/storage.wit
 * Generated by: scripts/generate_browser_glue.py
 *
 * DO NOT EDIT MANUALLY - regenerate with: just glue-gen
 *
 * All browser objects are represented as opaque bigint handles.
 */

// ---------------------------------------------------------------------------
// Custom type definitions
// ---------------------------------------------------------------------------

/** Type definition for DOMTokenListValue */
export type DOMTokenListValue = string;

/** Type definition for EventHandlerRecord */
export type EventHandlerRecord = any;

/** Type definition for WebGLObject */
export type WebGLObject = any;

/** Type definition for u64 */
export type u64 = bigint;

/** Type definition for RTCDataChannelBinaryType */
export type RTCDataChannelBinaryType = "blob" | "arraybuffer";

/** Type definition for CSSFontFaceDescriptors */
export type CSSFontFaceDescriptors = any;

/** Type definition for CSSFontFeatureValuesMap */
export type CSSFontFeatureValuesMap = any;

/** Type definition for OnBeforeUnloadEventHandlerRecord */
export type OnBeforeUnloadEventHandlerRecord = OnBeforeUnloadEventHandlerNonNull | null;

/** Type definition for OnErrorEventHandlerRecord */
export type OnErrorEventHandlerRecord = OnErrorEventHandlerNonNull | null;

/** Type definition for VoidFunctionRecord */
export type VoidFunctionRecord = VoidFunction;

/** Type definition for EventHandler */
export type EventHandler = (this: any, ev: any) => any;

/** Type definition for GeometryUtils */
export type GeometryUtils = any;

/** Type definition for HyperlinkElementUtils */
export type HyperlinkElementUtils = any;

/** Type definition for PopoverTargetAttributes */
export type PopoverTargetAttributes = any;

/** Type definition for CSSPageDescriptors */
export type CSSPageDescriptors = any;

/** Type definition for CSSMarginRule */
export type CSSMarginRule = CSSRule;

/** Type definition for CSSStyleProperties */
export type CSSStyleProperties = Record<string, string>;

/** Type definition for Origin */
export type Origin = string;

/** Type definition for FetchLaterResult */
export type FetchLaterResult = any;

/** Type definition for NotRestoredReasonDetails */
export type NotRestoredReasonDetails = any;

/** Type definition for NotRestoredReasons */
export type NotRestoredReasons = any;

/** Type definition for DeviceChangeEvent */
export type DeviceChangeEvent = Event;

/** Type definition for ChapterInformation */
export type ChapterInformation = any;

/** Type definition for PerformanceTimingConfidence */
export type PerformanceTimingConfidence = any;

/** Type definition for NotificationEvent */
export type NotificationEvent = Event;

/** Type definition for VisibilityStateEntry */
export type VisibilityStateEntry = PerformanceEntry;

/** Type definition for CommandEvent */
export type CommandEvent = Event;

/** Type definition for CloseWatcher */
export type CloseWatcher = EventTarget;

/** Type definition for CaptureController */
export type CaptureController = any;

/** Type definition for Navigation */
export type Navigation = any;

/** Type definition for NavigationTransition */
export type NavigationTransition = any;

/** Type definition for NavigateEvent */
export type NavigateEvent = Event;

/** Type definition for NavigationPrecommitController */
export type NavigationPrecommitController = any;

/** Type definition for NavigationDestination */
export type NavigationDestination = any;

/** Type definition for NavigationCurrentEntryChangeEvent */
export type NavigationCurrentEntryChangeEvent = Event;

/** Type definition for BatteryManager */
export type BatteryManager = any;

/** Type definition for AudioTrackList */
export type AudioTrackList = any;

/** Type definition for AudioTrack */
export type AudioTrack = any;

/** Type definition for VideoTrackList */
export type VideoTrackList = any;

/** Type definition for VideoTrack */
export type VideoTrack = any;

/** Type definition for WorkerGlobalScope */
export type WorkerGlobalScope = any;

/** Type definition for DedicatedWorkerGlobalScope */
export type DedicatedWorkerGlobalScope = any;

/** Type definition for SharedWorkerGlobalScope */
export type SharedWorkerGlobalScope = any;

/** Type definition for WorkerNavigator */
export type WorkerNavigator = any;

/** Type definition for WorkerLocation */
export type WorkerLocation = any;

/** Type definition for ServiceWorkerGlobalScope */
export type ServiceWorkerGlobalScope = any;

/** Type definition for Client */
export type Client = any;

/** Type definition for WindowClient */
export type WindowClient = any;

/** Type definition for Clients */
export type Clients = any;

/** Type definition for ExtendableEvent */
export type ExtendableEvent = Event;

/** Type definition for InstallEvent */
export type InstallEvent = Event;

/** Type definition for FetchEvent */
export type FetchEvent = Event;

/** Type definition for ExtendableMessageEvent */
export type ExtendableMessageEvent = MessageEvent;

/** Type definition for SpeechRecognition */
export type SpeechRecognition = any;

/** Type definition for SpeechRecognitionErrorEvent */
export type SpeechRecognitionErrorEvent = Event;

/** Type definition for SpeechRecognitionEvent */
export type SpeechRecognitionEvent = Event;

/** Type definition for SpeechGrammar */
export type SpeechGrammar = any;

/** Type definition for SpeechGrammarList */
export type SpeechGrammarList = any;

/** Type definition for SpeechRecognitionPhrase */
export type SpeechRecognitionPhrase = any;

/** Type definition for Module */
export type Module = typeof WebAssembly.Module;

/** Type definition for Instance */
export type Instance = typeof WebAssembly.Instance;

/** Type definition for Memory */
export type Memory = typeof WebAssembly.Memory;

/** Type definition for Table */
export type Table = typeof WebAssembly.Table;

/** Type definition for Global */
export type Global = typeof WebAssembly.Global;

/** Type definition for Exception */
export type Exception = any;

/** Type definition for HTMLString */
export type HTMLString = string;

/** Type definition for MediaText */
export type MediaText = string;

/** Type definition for HTMLHyperlinkHref */
export type HTMLHyperlinkHref = string;

/** Type definition for LocationHref */
export type LocationHref = string;

/** Type definition for URLHref */
export type URLHref = string;


// ---------------------------------------------------------------------------
// Async handle table for Promise-based operations
// ---------------------------------------------------------------------------

let _nextAsyncHandle = 1n;

interface AsyncHandle<T> {
  promise: Promise<T>;
  result: { ok: true; value: T } | { ok: false; error: string } | null;
}

const _asyncHandles = new Map<bigint, AsyncHandle<unknown>>();

// ---------------------------------------------------------------------------
// Synthetic handle tables for primitive/utility types
// ---------------------------------------------------------------------------

/** Handle table for cache-storage values */
const _cacheStorageHandles = new Map<bigint, CacheStorage>();
let _nextCacheStorage = 1n;

/** Handle table for crypto values */
const _cryptoHandles = new Map<bigint, Crypto>();
let _nextCrypto = 1n;

/** Handle table for performance values */
const _performanceHandles = new Map<bigint, Performance>();
let _nextPerformance = 1n;

// ---------------------------------------------------------------------------
// Helper functions for handle lookups
// ---------------------------------------------------------------------------

/** Lookup a cache-storage value by handle. */
function lookupCacheStorage(handle: bigint): CacheStorage {
  const obj = _cacheStorageHandles.get(handle);
  if (obj === undefined) {
    throw new Error(`cache-storage handle ${handle} not found`);
  }
  return obj!;
}

/** Lookup an optional cache-storage value by handle. */
function lookupOptionCacheStorage(handle: bigint | undefined): CacheStorage | null {
  if (handle === undefined || handle === 0n) {
    return null;
  }
  return _cacheStorageHandles.get(handle) ?? null;
}

/** Lookup a crypto value by handle. */
function lookupCrypto(handle: bigint): Crypto {
  const obj = _cryptoHandles.get(handle);
  if (obj === undefined) {
    throw new Error(`crypto handle ${handle} not found`);
  }
  return obj!;
}

/** Lookup an optional crypto value by handle. */
function lookupOptionCrypto(handle: bigint | undefined): Crypto | null {
  if (handle === undefined || handle === 0n) {
    return null;
  }
  return _cryptoHandles.get(handle) ?? null;
}

/** Lookup a performance value by handle. */
function lookupPerformance(handle: bigint): Performance {
  const obj = _performanceHandles.get(handle);
  if (obj === undefined) {
    throw new Error(`performance handle ${handle} not found`);
  }
  return obj!;
}

/** Lookup an optional performance value by handle. */
function lookupOptionPerformance(handle: bigint | undefined): Performance | null {
  if (handle === undefined || handle === 0n) {
    return null;
  }
  return _performanceHandles.get(handle) ?? null;
}

// ---------------------------------------------------------------------------
// WIT interface: idb-request
// ---------------------------------------------------------------------------

/** Type alias */
export type IdbRequestHandle = bigint;

/** Handle table for IDBRequest instances */
const _idbRequesthandles = new Map<bigint, IDBRequest>();
let _nextIDBRequest = 1n;

/** Lookup a IDBRequest by handle, throwing if not found. */
function lookupIDBRequest(handle: bigint): IDBRequest {
  const obj = _idbRequesthandles.get(handle);
  if (!obj) {
    throw new Error(`IDBRequest handle ${handle} not found`);
  }
  return obj!;
}

/** Lookup an optional IDBRequest by handle. */
function lookupOptionIDBRequest(handle: bigint | undefined): IDBRequest | null {
  if (handle === undefined || handle === 0n) {
    return null;
  }
  return _idbRequesthandles.get(handle) ?? null;
}
/**
 * `get-result()` operation.
 */
export function getResult(self: bigint): string {
  const obj = lookupIDBRequest(self);
  return obj.result;
}

/**
 * `get-error()` operation.
 */
export function IdbRequestGetError(self: bigint): bigint | undefined {
  const obj = lookupIDBRequest(self);
  return obj.error ?? undefined;
}

/**
 * `get-source()` operation.
 */
export function IdbRequestGetSource(self: bigint): bigint | undefined {
  const obj = lookupIDBRequest(self);
  return (obj as any).source ?? undefined;
}

/**
 * `get-transaction()` operation.
 */
export function IdbRequestGetTransaction(self: bigint): bigint | undefined {
  const obj = lookupIDBRequest(self);
  return obj.transaction ?? undefined;
}

/**
 * `get-ready-state()` operation.
 */
export function getReadyState(self: bigint): bigint {
  const obj = lookupIDBRequest(self);
  return obj.readyState;
}

/**
 * `get-onsuccess()` operation.
 */
export function getOnsuccess(self: bigint): bigint {
  const obj = lookupIDBRequest(self);
  return obj.onsuccess;
}

/**
 * `set-onsuccess()` operation.
 */
export function setOnsuccess(self: bigint, value: bigint): void {
  const obj = lookupIDBRequest(self);
  obj.onsuccess = value;
}

/**
 * `get-onerror()` operation.
 */
export function IdbRequestGetOnerror(self: bigint): bigint {
  const obj = lookupIDBRequest(self);
  return obj.onerror;
}

/**
 * `set-onerror()` operation.
 */
export function IdbRequestSetOnerror(self: bigint, value: bigint): void {
  const obj = lookupIDBRequest(self);
  obj.onerror = value;
}

// ---------------------------------------------------------------------------
// WIT interface: idb-open-db-request
// ---------------------------------------------------------------------------

/** Type alias */
export type IdbOpenDbRequestHandle = bigint;

/** Handle table for IdbOpenDbRequest instances */
const _idbOpenDbRequesthandles = new Map<bigint, IdbOpenDbRequest>();
let _nextIdbOpenDbRequest = 1n;

/** Lookup a IdbOpenDbRequest by handle, throwing if not found. */
function lookupIdbOpenDbRequest(handle: bigint): IdbOpenDbRequest {
  const obj = _idbOpenDbRequesthandles.get(handle);
  if (!obj) {
    throw new Error(`IdbOpenDbRequest handle ${handle} not found`);
  }
  return obj!;
}

/** Lookup an optional IdbOpenDbRequest by handle. */
function lookupOptionIdbOpenDbRequest(handle: bigint | undefined): IdbOpenDbRequest | null {
  if (handle === undefined || handle === 0n) {
    return null;
  }
  return _idbOpenDbRequesthandles.get(handle) ?? null;
}
/**
 * `get-onblocked()` operation.
 */
export function getOnblocked(self: bigint): bigint {
  const obj = lookupIdbOpenDbRequest(self);
  return obj.onblocked;
}

/**
 * `set-onblocked()` operation.
 */
export function setOnblocked(self: bigint, value: bigint): void {
  const obj = lookupIdbOpenDbRequest(self);
  obj.onblocked = value;
}

/**
 * `get-onupgradeneeded()` operation.
 */
export function getOnupgradeneeded(self: bigint): bigint {
  const obj = lookupIdbOpenDbRequest(self);
  return obj.onupgradeneeded;
}

/**
 * `set-onupgradeneeded()` operation.
 */
export function setOnupgradeneeded(self: bigint, value: bigint): void {
  const obj = lookupIdbOpenDbRequest(self);
  obj.onupgradeneeded = value;
}

// ---------------------------------------------------------------------------
// WIT interface: idb-version-change-event
// ---------------------------------------------------------------------------

/** Type alias */
export type IdbVersionChangeEventHandle = bigint;

/** Handle table for IDBVersionChangeEvent instances */
const _idbVersionChangeEventhandles = new Map<bigint, IDBVersionChangeEvent>();
let _nextIDBVersionChangeEvent = 1n;

/** Lookup a IDBVersionChangeEvent by handle, throwing if not found. */
function lookupIDBVersionChangeEvent(handle: bigint): IDBVersionChangeEvent {
  const obj = _idbVersionChangeEventhandles.get(handle);
  if (!obj) {
    throw new Error(`IDBVersionChangeEvent handle ${handle} not found`);
  }
  return obj!;
}

/** Lookup an optional IDBVersionChangeEvent by handle. */
function lookupOptionIDBVersionChangeEvent(handle: bigint | undefined): IDBVersionChangeEvent | null {
  if (handle === undefined || handle === 0n) {
    return null;
  }
  return _idbVersionChangeEventhandles.get(handle) ?? null;
}
/**
 * `get-old-version()` operation.
 */
export function getOldVersion(self: bigint): bigint {
  const obj = lookupIDBVersionChangeEvent(self);
  return obj.oldVersion;
}

/**
 * `get-new-version()` operation.
 */
export function getNewVersion(self: bigint): bigint | undefined {
  const obj = lookupIDBVersionChangeEvent(self);
  return obj.newVersion ?? undefined;
}

// ---------------------------------------------------------------------------
// WIT interface: window-or-worker-global-scope
// ---------------------------------------------------------------------------

/** Type alias */
export type WindowOrWorkerGlobalScopeHandle = bigint;

/** Handle table for WindowOrWorkerGlobalScope instances */
const _windowOrWorkerGlobalScopehandles = new Map<bigint, WindowOrWorkerGlobalScope>();
let _nextWindowOrWorkerGlobalScope = 1n;

/** Register a new WindowOrWorkerGlobalScope and return its handle. */
function registerWindowOrWorkerGlobalScope(obj: WindowOrWorkerGlobalScope): bigint {
  const handle = _nextWindowOrWorkerGlobalScope++;
  _windowOrWorkerGlobalScopehandles.set(handle, obj);
  return handle;
}
/** Lookup a WindowOrWorkerGlobalScope by handle, throwing if not found. */
function lookupWindowOrWorkerGlobalScope(handle: bigint): WindowOrWorkerGlobalScope {
  const obj = _windowOrWorkerGlobalScopehandles.get(handle);
  if (!obj) {
    throw new Error(`WindowOrWorkerGlobalScope handle ${handle} not found`);
  }
  return obj!;
}

/** Lookup an optional WindowOrWorkerGlobalScope by handle. */
function lookupOptionWindowOrWorkerGlobalScope(handle: bigint | undefined): WindowOrWorkerGlobalScope | null {
  if (handle === undefined || handle === 0n) {
    return null;
  }
  return _windowOrWorkerGlobalScopehandles.get(handle) ?? null;
}
/**
 * `get-indexed-db()` operation.
 */
export function getIndexedDb(self: bigint): bigint {
  const obj = lookupWindowOrWorkerGlobalScope(self);
  return obj.indexedDb;
}

/**
 * `fetch()` operation.
 *
 * Async operation: returns request ID, poll with `pollFetch()`
 */
export function fetch(self: bigint, input: bigint, init: bigint | undefined): bigint {
  const requestId = _nextAsyncHandle++;
  const obj = lookupWindowOrWorkerGlobalScope(self);
  const promise = obj.fetch(input as any, init as any)
    .then((result: unknown) => {
      const entry = _asyncHandles.get(requestId);
      if (entry) {
        entry.result = { ok: true, value: result };
      }
    })
    .catch((err: Error) => {
      const entry = _asyncHandles.get(requestId);
      if (entry) {
        entry.result = { ok: false, error: err.message };
      }
    });

  _asyncHandles.set(requestId, { promise, result: null });
  return requestId;
}

/**
 * Poll an async `fetch()` operation.
 * Returns undefined if still pending, or the result if complete.
 */
export function pollFetch(requestId: bigint): { ok: true; value: bigint } | { ok: false; error: string } | undefined {
  const entry = _asyncHandles.get(requestId);
  if (!entry) {
    return { ok: false, error: `Unknown request ID ${requestId}` };
  }
  return entry.result as { ok: true; value: bigint } | { ok: false; error: string } | null ?? undefined;
}

/**
 * `get-performance()` operation.
 */
export function getPerformance(self: bigint): bigint {
  const obj = lookupWindowOrWorkerGlobalScope(self);
  const _callResult = obj.performance;
  const handle = _nextPerformance++;
  _performanceHandles.set(handle, _callResult);
  return handle;
}

/**
 * `get-origin()` operation.
 */
export function getOrigin(self: bigint): string {
  const obj = lookupWindowOrWorkerGlobalScope(self);
  return obj.origin;
}

/**
 * `get-is-secure-context()` operation.
 */
export function getIsSecureContext(self: bigint): bigint {
  const obj = lookupWindowOrWorkerGlobalScope(self);
  return obj.isSecureContext ? 1n : 0n;
}

/**
 * `get-cross-origin-isolated()` operation.
 */
export function getCrossOriginIsolated(self: bigint): bigint {
  const obj = lookupWindowOrWorkerGlobalScope(self);
  return obj.crossOriginIsolated ? 1n : 0n;
}

/**
 * `report-error()` operation.
 */
export function reportError(self: bigint, e: string): void {
  const obj = lookupWindowOrWorkerGlobalScope(self);
  obj.reportError(e);
}

/**
 * `btoa()` operation.
 */
export function btoa(self: bigint, data: string): string {
  const obj = lookupWindowOrWorkerGlobalScope(self);
  return obj.btoa(data);
}

/**
 * `atob()` operation.
 */
export function atob(self: bigint, data: string): string {
  const obj = lookupWindowOrWorkerGlobalScope(self);
  return obj.atob(data as any);
}

/**
 * `set-timeout()` operation.
 */
export function setTimeout(self: bigint, handler: bigint, timeout: number | undefined, _arguments: (string)[]): number {
  const obj = lookupWindowOrWorkerGlobalScope(self);
  return (obj as any).setTimeout(handler, timeout, _arguments);
}

/**
 * `clear-timeout()` operation.
 */
export function clearTimeout(self: bigint, id: number | undefined): void {
  const obj = lookupWindowOrWorkerGlobalScope(self);
  obj.clearTimeout(Number(id));
}

/**
 * `set-interval()` operation.
 */
export function setInterval(self: bigint, handler: bigint, timeout: number | undefined, _arguments: (string)[]): number {
  const obj = lookupWindowOrWorkerGlobalScope(self);
  return (obj as any).setInterval(handler, timeout, _arguments);
}

/**
 * `clear-interval()` operation.
 */
export function clearInterval(self: bigint, id: number | undefined): void {
  const obj = lookupWindowOrWorkerGlobalScope(self);
  obj.clearInterval(Number(id));
}

/**
 * `queue-microtask()` operation.
 */
export function queueMicrotask(self: bigint, callback: bigint): void {
  const obj = lookupWindowOrWorkerGlobalScope(self);
  obj.queueMicrotask(callback as any);
}

/**
 * `create-image-bitmap()` operation.
 *
 * Async operation: returns request ID, poll with `pollCreateImageBitmap()`
 */
export function createImageBitmap(self: bigint, image: bigint, options: bigint | undefined): bigint {
  const requestId = _nextAsyncHandle++;
  const obj = lookupWindowOrWorkerGlobalScope(self);
  const promise = obj.createImageBitmap(image as any, options as any)
    .then((result: unknown) => {
      const entry = _asyncHandles.get(requestId);
      if (entry) {
        entry.result = { ok: true, value: result };
      }
    })
    .catch((err: Error) => {
      const entry = _asyncHandles.get(requestId);
      if (entry) {
        entry.result = { ok: false, error: err.message };
      }
    });

  _asyncHandles.set(requestId, { promise, result: null });
  return requestId;
}

/**
 * Poll an async `createImageBitmap()` operation.
 * Returns undefined if still pending, or the result if complete.
 */
export function pollCreateImageBitmap(requestId: bigint): { ok: true; value: bigint } | { ok: false; error: string } | undefined {
  const entry = _asyncHandles.get(requestId);
  if (!entry) {
    return { ok: false, error: `Unknown request ID ${requestId}` };
  }
  return entry.result as { ok: true; value: bigint } | { ok: false; error: string } | null ?? undefined;
}

/**
 * `structured-clone()` operation.
 */
export function structuredClone(self: bigint, value: string, options: bigint | undefined): string {
  const obj = lookupWindowOrWorkerGlobalScope(self);
  return obj.structuredClone(value as any, options as any);
}

/**
 * `get-caches()` operation.
 */
export function getCaches(self: bigint): bigint {
  const obj = lookupWindowOrWorkerGlobalScope(self);
  const _callResult = obj.caches;
  const handle = _nextCacheStorage++;
  _cacheStorageHandles.set(handle, _callResult);
  return handle;
}

/**
 * `get-crypto()` operation.
 */
export function getCrypto(self: bigint): bigint {
  const obj = lookupWindowOrWorkerGlobalScope(self);
  const _callResult = obj.crypto;
  const handle = _nextCrypto++;
  _cryptoHandles.set(handle, _callResult);
  return handle;
}

// ---------------------------------------------------------------------------
// WIT interface: idb-factory
// ---------------------------------------------------------------------------

/** Type alias */
export type IdbFactoryHandle = bigint;

/** Handle table for IDBFactory instances */
const _idbFactoryhandles = new Map<bigint, IDBFactory>();
let _nextIDBFactory = 1n;

/** Lookup a IDBFactory by handle, throwing if not found. */
function lookupIDBFactory(handle: bigint): IDBFactory {
  const obj = _idbFactoryhandles.get(handle);
  if (!obj) {
    throw new Error(`IDBFactory handle ${handle} not found`);
  }
  return obj!;
}

/** Lookup an optional IDBFactory by handle. */
function lookupOptionIDBFactory(handle: bigint | undefined): IDBFactory | null {
  if (handle === undefined || handle === 0n) {
    return null;
  }
  return _idbFactoryhandles.get(handle) ?? null;
}
/**
 * `open()` operation.
 */
export function open(self: bigint, name: string, version: bigint | undefined): bigint {
  const obj = lookupIDBFactory(self);
  return obj.open(name, version);
}

/**
 * `delete-database()` operation.
 */
export function deleteDatabase(self: bigint, name: string): bigint {
  const obj = lookupIDBFactory(self);
  return obj.deleteDatabase(name);
}

/**
 * `databases()` operation.
 */
export function databases(self: bigint): bigint {
  const obj = lookupIDBFactory(self);
  return obj.databases();
}

/**
 * `cmp()` operation.
 */
export function cmp(self: bigint, first: string, second: string): number {
  const obj = lookupIDBFactory(self);
  return obj.cmp(first, second);
}

// ---------------------------------------------------------------------------
// WIT interface: idb-database
// ---------------------------------------------------------------------------

/** Type alias */
export type IdbDatabaseHandle = bigint;

/** Handle table for IDBDatabase instances */
const _idbDatabasehandles = new Map<bigint, IDBDatabase>();
let _nextIDBDatabase = 1n;

/** Register a new IDBDatabase and return its handle. */
function registerIDBDatabase(obj: IDBDatabase): bigint {
  const handle = _nextIDBDatabase++;
  _idbDatabasehandles.set(handle, obj);
  return handle;
}
/** Lookup a IDBDatabase by handle, throwing if not found. */
function lookupIDBDatabase(handle: bigint): IDBDatabase {
  const obj = _idbDatabasehandles.get(handle);
  if (!obj) {
    throw new Error(`IDBDatabase handle ${handle} not found`);
  }
  return obj!;
}

/** Lookup an optional IDBDatabase by handle. */
function lookupOptionIDBDatabase(handle: bigint | undefined): IDBDatabase | null {
  if (handle === undefined || handle === 0n) {
    return null;
  }
  return _idbDatabasehandles.get(handle) ?? null;
}
/**
 * `get-name()` operation.
 */
export function IdbDatabaseGetName(self: bigint): string {
  const obj = lookupIDBDatabase(self);
  return (obj as any).name;
}

/**
 * `get-version()` operation.
 */
export function getVersion(self: bigint): bigint {
  const obj = lookupIDBDatabase(self);
  return (obj as any).version;
}

/**
 * `get-object-store-names()` operation.
 */
export function IdbDatabaseGetObjectStoreNames(self: bigint): (string)[] {
  const obj = lookupIDBDatabase(self);
  return obj.objectStoreNames;
}

/**
 * `transaction()` operation.
 */
export function transaction(self: bigint, storeNames: string, mode: bigint | undefined, options: bigint | undefined): bigint {
  const obj = lookupIDBDatabase(self);
  return obj.transaction(storeNames, mode, options);
}

/**
 * `close()` operation.
 */
export function close(self: bigint): void {
  const obj = lookupIDBDatabase(self);
  obj.close();
}

/**
 * `create-object-store()` operation.
 */
export function createObjectStore(self: bigint, name: string, options: bigint | undefined): bigint {
  const obj = lookupIDBDatabase(self);
  return obj.createObjectStore(name, options);
}

/**
 * `delete-object-store()` operation.
 */
export function deleteObjectStore(self: bigint, name: string): void {
  const obj = lookupIDBDatabase(self);
  obj.deleteObjectStore(name);
}

/**
 * `get-onabort()` operation.
 */
export function IdbDatabaseGetOnabort(self: bigint): bigint {
  const obj = lookupIDBDatabase(self);
  return obj.onabort;
}

/**
 * `set-onabort()` operation.
 */
export function IdbDatabaseSetOnabort(self: bigint, value: bigint): void {
  const obj = lookupIDBDatabase(self);
  obj.onabort = value;
}

/**
 * `get-onclose()` operation.
 */
export function getOnclose(self: bigint): bigint {
  const obj = lookupIDBDatabase(self);
  return obj.onclose;
}

/**
 * `set-onclose()` operation.
 */
export function setOnclose(self: bigint, value: bigint): void {
  const obj = lookupIDBDatabase(self);
  obj.onclose = value;
}

/**
 * `get-onerror()` operation.
 */
export function IdbDatabaseGetOnerror(self: bigint): bigint {
  const obj = lookupIDBDatabase(self);
  return obj.onerror;
}

/**
 * `set-onerror()` operation.
 */
export function IdbDatabaseSetOnerror(self: bigint, value: bigint): void {
  const obj = lookupIDBDatabase(self);
  obj.onerror = value;
}

/**
 * `get-onversionchange()` operation.
 */
export function getOnversionchange(self: bigint): bigint {
  const obj = lookupIDBDatabase(self);
  return obj.onversionchange;
}

/**
 * `set-onversionchange()` operation.
 */
export function setOnversionchange(self: bigint, value: bigint): void {
  const obj = lookupIDBDatabase(self);
  obj.onversionchange = value;
}

// ---------------------------------------------------------------------------
// WIT interface: idb-object-store
// ---------------------------------------------------------------------------

/** Type alias */
export type IdbObjectStoreHandle = bigint;

/** Handle table for IDBObjectStore instances */
const _idbObjectStorehandles = new Map<bigint, IDBObjectStore>();
let _nextIDBObjectStore = 1n;

/** Register a new IDBObjectStore and return its handle. */
function registerIDBObjectStore(obj: IDBObjectStore): bigint {
  const handle = _nextIDBObjectStore++;
  _idbObjectStorehandles.set(handle, obj);
  return handle;
}
/** Lookup a IDBObjectStore by handle, throwing if not found. */
function lookupIDBObjectStore(handle: bigint): IDBObjectStore {
  const obj = _idbObjectStorehandles.get(handle);
  if (!obj) {
    throw new Error(`IDBObjectStore handle ${handle} not found`);
  }
  return obj!;
}

/** Lookup an optional IDBObjectStore by handle. */
function lookupOptionIDBObjectStore(handle: bigint | undefined): IDBObjectStore | null {
  if (handle === undefined || handle === 0n) {
    return null;
  }
  return _idbObjectStorehandles.get(handle) ?? null;
}
/**
 * `get-name()` operation.
 */
export function IdbObjectStoreGetName(self: bigint): string {
  const obj = lookupIDBObjectStore(self);
  return obj.name;
}

/**
 * `set-name()` operation.
 */
export function IdbObjectStoreSetName(self: bigint, value: string): void {
  const obj = lookupIDBObjectStore(self);
  obj.name = value as any;
}

/**
 * `get-key-path()` operation.
 */
export function IdbObjectStoreGetKeyPath(self: bigint): string {
  const obj = lookupIDBObjectStore(self);
  return (obj as any).keyPath;
}

/**
 * `get-index-names()` operation.
 */
export function getIndexNames(self: bigint): (string)[] {
  const obj = lookupIDBObjectStore(self);
  return obj.indexNames;
}

/**
 * `get-transaction()` operation.
 */
export function IdbObjectStoreGetTransaction(self: bigint): bigint {
  const obj = lookupIDBObjectStore(self);
  return obj.transaction;
}

/**
 * `get-auto-increment()` operation.
 */
export function getAutoIncrement(self: bigint): boolean {
  const obj = lookupIDBObjectStore(self);
  return (obj as any).autoIncrement;
}

/**
 * `put()` operation.
 */
export function put(self: bigint, value: string, key: string | undefined): bigint {
  const obj = lookupIDBObjectStore(self);
  return obj.put(value, key);
}

/**
 * `add()` operation.
 */
export function add(self: bigint, value: string, key: string | undefined): bigint {
  const obj = lookupIDBObjectStore(self);
  return obj.add(value, key);
}

/**
 * `delete()` operation.
 */
export function IdbObjectStoreDelete(self: bigint, query: string): bigint {
  const obj = lookupIDBObjectStore(self);
  return obj.delete(query);
}

/**
 * `clear()` operation.
 */
export function clear(self: bigint): bigint {
  const obj = lookupIDBObjectStore(self);
  return obj.clear();
}

/**
 * `get()` operation.
 *
 * Async operation: returns request ID, poll with `IdbObjectStorePollGet()`
 */
export function IdbObjectStoreGet(self: bigint, query: string): bigint {
  const requestId = _nextAsyncHandle++;
  const obj = lookupIDBObjectStore(self);
  const promise = obj.get(query)
    .then((result: unknown) => {
      const entry = _asyncHandles.get(requestId);
      if (entry) {
        entry.result = { ok: true, value: result };
      }
    })
    .catch((err: Error) => {
      const entry = _asyncHandles.get(requestId);
      if (entry) {
        entry.result = { ok: false, error: err.message };
      }
    });

  _asyncHandles.set(requestId, { promise, result: null });
  return requestId;
}

/**
 * Poll an async `_get()` operation.
 * Returns undefined if still pending, or the result if complete.
 */
export function IdbObjectStorePollGet(requestId: bigint): { ok: true; value: bigint } | { ok: false; error: string } | undefined {
  const entry = _asyncHandles.get(requestId);
  if (!entry) {
    return { ok: false, error: `Unknown request ID ${requestId}` };
  }
  return entry.result as { ok: true; value: bigint } | { ok: false; error: string } | null ?? undefined;
}

/**
 * `get-key()` operation.
 */
export function IdbObjectStoreGetKey(self: bigint, query: string): bigint {
  const obj = lookupIDBObjectStore(self);
  return obj.key;
}

/**
 * `get-all()` operation.
 */
export function IdbObjectStoreGetAll(self: bigint, queryOrOptions: string | undefined, count: number | undefined): bigint {
  const obj = lookupIDBObjectStore(self);
  return obj.all;
}

/**
 * `get-all-keys()` operation.
 */
export function IdbObjectStoreGetAllKeys(self: bigint, queryOrOptions: string | undefined, count: number | undefined): bigint {
  const obj = lookupIDBObjectStore(self);
  return obj.allKeys;
}

/**
 * `get-all-records()` operation.
 */
export function IdbObjectStoreGetAllRecords(self: bigint, options: bigint | undefined): bigint {
  const obj = lookupIDBObjectStore(self);
  return obj.allRecords;
}

/**
 * `count()` operation.
 */
export function IdbObjectStoreCount(self: bigint, query: string | undefined): bigint {
  const obj = lookupIDBObjectStore(self);
  return obj.count(query);
}

/**
 * `open-cursor()` operation.
 */
export function IdbObjectStoreOpenCursor(self: bigint, query: string | undefined, direction: bigint | undefined): bigint {
  const obj = lookupIDBObjectStore(self);
  return obj.openCursor(query, direction);
}

/**
 * `open-key-cursor()` operation.
 */
export function IdbObjectStoreOpenKeyCursor(self: bigint, query: string | undefined, direction: bigint | undefined): bigint {
  const obj = lookupIDBObjectStore(self);
  return obj.openKeyCursor(query, direction);
}

/**
 * `index()` operation.
 */
export function index(self: bigint, name: string): bigint {
  const obj = lookupIDBObjectStore(self);
  return obj.index(name);
}

/**
 * `create-index()` operation.
 */
export function createIndex(self: bigint, name: string, keyPath: string, options: bigint | undefined): bigint {
  const obj = lookupIDBObjectStore(self);
  return obj.createIndex(name, keyPath, options);
}

/**
 * `delete-index()` operation.
 */
export function deleteIndex(self: bigint, name: string): void {
  const obj = lookupIDBObjectStore(self);
  obj.deleteIndex(name);
}

// ---------------------------------------------------------------------------
// WIT interface: idb-index
// ---------------------------------------------------------------------------

/** Type alias */
export type IdbIndexHandle = bigint;

/** Handle table for IDBIndex instances */
const _idbIndexhandles = new Map<bigint, IDBIndex>();
let _nextIDBIndex = 1n;

/** Lookup a IDBIndex by handle, throwing if not found. */
function lookupIDBIndex(handle: bigint): IDBIndex {
  const obj = _idbIndexhandles.get(handle);
  if (!obj) {
    throw new Error(`IDBIndex handle ${handle} not found`);
  }
  return obj!;
}

/** Lookup an optional IDBIndex by handle. */
function lookupOptionIDBIndex(handle: bigint | undefined): IDBIndex | null {
  if (handle === undefined || handle === 0n) {
    return null;
  }
  return _idbIndexhandles.get(handle) ?? null;
}
/**
 * `get-name()` operation.
 */
export function IdbIndexGetName(self: bigint): string {
  const obj = lookupIDBIndex(self);
  return obj.name;
}

/**
 * `set-name()` operation.
 */
export function IdbIndexSetName(self: bigint, value: string): void {
  const obj = lookupIDBIndex(self);
  obj.name = value;
}

/**
 * `get-object-store()` operation.
 */
export function getObjectStore(self: bigint): bigint {
  const obj = lookupIDBIndex(self);
  return obj.objectStore;
}

/**
 * `get-key-path()` operation.
 */
export function IdbIndexGetKeyPath(self: bigint): string {
  const obj = lookupIDBIndex(self);
  return (obj as any).keyPath;
}

/**
 * `get-multi-entry()` operation.
 */
export function getMultiEntry(self: bigint): boolean {
  const obj = lookupIDBIndex(self);
  return (obj as any).multiEntry;
}

/**
 * `get-unique()` operation.
 */
export function getUnique(self: bigint): boolean {
  const obj = lookupIDBIndex(self);
  return (obj as any).unique;
}

/**
 * `get()` operation.
 *
 * Async operation: returns request ID, poll with `IdbIndexPollGet()`
 */
export function IdbIndexGet(self: bigint, query: string): bigint {
  const requestId = _nextAsyncHandle++;
  const obj = lookupIDBIndex(self);
  const promise = obj.get(query)
    .then((result: unknown) => {
      const entry = _asyncHandles.get(requestId);
      if (entry) {
        entry.result = { ok: true, value: result };
      }
    })
    .catch((err: Error) => {
      const entry = _asyncHandles.get(requestId);
      if (entry) {
        entry.result = { ok: false, error: err.message };
      }
    });

  _asyncHandles.set(requestId, { promise, result: null });
  return requestId;
}

/**
 * Poll an async `_get()` operation.
 * Returns undefined if still pending, or the result if complete.
 */
export function IdbIndexPollGet(requestId: bigint): { ok: true; value: bigint } | { ok: false; error: string } | undefined {
  const entry = _asyncHandles.get(requestId);
  if (!entry) {
    return { ok: false, error: `Unknown request ID ${requestId}` };
  }
  return entry.result as { ok: true; value: bigint } | { ok: false; error: string } | null ?? undefined;
}

/**
 * `get-key()` operation.
 */
export function IdbIndexGetKey(self: bigint, query: string): bigint {
  const obj = lookupIDBIndex(self);
  return obj.key;
}

/**
 * `get-all()` operation.
 */
export function IdbIndexGetAll(self: bigint, queryOrOptions: string | undefined, count: number | undefined): bigint {
  const obj = lookupIDBIndex(self);
  return obj.all;
}

/**
 * `get-all-keys()` operation.
 */
export function IdbIndexGetAllKeys(self: bigint, queryOrOptions: string | undefined, count: number | undefined): bigint {
  const obj = lookupIDBIndex(self);
  return obj.allKeys;
}

/**
 * `get-all-records()` operation.
 */
export function IdbIndexGetAllRecords(self: bigint, options: bigint | undefined): bigint {
  const obj = lookupIDBIndex(self);
  return obj.allRecords;
}

/**
 * `count()` operation.
 */
export function IdbIndexCount(self: bigint, query: string | undefined): bigint {
  const obj = lookupIDBIndex(self);
  return obj.count(query);
}

/**
 * `open-cursor()` operation.
 */
export function IdbIndexOpenCursor(self: bigint, query: string | undefined, direction: bigint | undefined): bigint {
  const obj = lookupIDBIndex(self);
  return obj.openCursor(query, direction);
}

/**
 * `open-key-cursor()` operation.
 */
export function IdbIndexOpenKeyCursor(self: bigint, query: string | undefined, direction: bigint | undefined): bigint {
  const obj = lookupIDBIndex(self);
  return obj.openKeyCursor(query, direction);
}

// ---------------------------------------------------------------------------
// WIT interface: idb-key-range
// ---------------------------------------------------------------------------

/** Type alias */
export type IdbKeyRangeHandle = bigint;

/** Handle table for IDBKeyRange instances */
const _idbKeyRangehandles = new Map<bigint, IDBKeyRange>();
let _nextIDBKeyRange = 1n;

/** Lookup a IDBKeyRange by handle, throwing if not found. */
function lookupIDBKeyRange(handle: bigint): IDBKeyRange {
  const obj = _idbKeyRangehandles.get(handle);
  if (!obj) {
    throw new Error(`IDBKeyRange handle ${handle} not found`);
  }
  return obj!;
}

/** Lookup an optional IDBKeyRange by handle. */
function lookupOptionIDBKeyRange(handle: bigint | undefined): IDBKeyRange | null {
  if (handle === undefined || handle === 0n) {
    return null;
  }
  return _idbKeyRangehandles.get(handle) ?? null;
}
/**
 * `get-lower()` operation.
 */
export function getLower(self: bigint): string {
  const obj = lookupIDBKeyRange(self);
  return obj.lower;
}

/**
 * `get-upper()` operation.
 */
export function getUpper(self: bigint): string {
  const obj = lookupIDBKeyRange(self);
  return obj.upper;
}

/**
 * `get-lower-open()` operation.
 */
export function getLowerOpen(self: bigint): boolean {
  const obj = lookupIDBKeyRange(self);
  return obj.lowerOpen;
}

/**
 * `get-upper-open()` operation.
 */
export function getUpperOpen(self: bigint): boolean {
  const obj = lookupIDBKeyRange(self);
  return obj.upperOpen;
}

/**
 * `only()` operation.
 */
export function only(value: string): bigint {
  return IDBKeyRange.only(value);
}

/**
 * `lower-bound()` operation.
 */
export function lowerBound(lower: string, open: boolean | undefined): bigint {
  return IDBKeyRange.lowerBound(lower, open);
}

/**
 * `upper-bound()` operation.
 */
export function upperBound(upper: string, open: boolean | undefined): bigint {
  return IDBKeyRange.upperBound(upper, open);
}

/**
 * `bound()` operation.
 */
export function bound(lower: string, upper: string, lowerOpen: boolean | undefined, upperOpen: boolean | undefined): bigint {
  return IDBKeyRange.bound(lower, upper, lowerOpen, upperOpen);
}

/**
 * `includes()` operation.
 */
export function includes(self: bigint, key: string): boolean {
  const obj = lookupIDBKeyRange(self);
  return obj.includes(key);
}

// ---------------------------------------------------------------------------
// WIT interface: idb-record
// ---------------------------------------------------------------------------

/** Type alias */
export type IdbRecordHandle = bigint;

/** Handle table for IdbRecord instances */
const _idbRecordhandles = new Map<bigint, IdbRecord>();
let _nextIdbRecord = 1n;

/** Lookup a IdbRecord by handle, throwing if not found. */
function lookupIdbRecord(handle: bigint): IdbRecord {
  const obj = _idbRecordhandles.get(handle);
  if (!obj) {
    throw new Error(`IdbRecord handle ${handle} not found`);
  }
  return obj!;
}

/** Lookup an optional IdbRecord by handle. */
function lookupOptionIdbRecord(handle: bigint | undefined): IdbRecord | null {
  if (handle === undefined || handle === 0n) {
    return null;
  }
  return _idbRecordhandles.get(handle) ?? null;
}
/**
 * `get-key()` operation.
 */
export function IdbRecordGetKey(self: bigint): string {
  const obj = lookupIdbRecord(self);
  return obj.key;
}

/**
 * `get-primary-key()` operation.
 */
export function IdbRecordGetPrimaryKey(self: bigint): string {
  const obj = lookupIdbRecord(self);
  return obj.primaryKey;
}

/**
 * `get-value()` operation.
 */
export function IdbRecordGetValue(self: bigint): string {
  const obj = lookupIdbRecord(self);
  return obj.value;
}

// ---------------------------------------------------------------------------
// WIT interface: idb-cursor
// ---------------------------------------------------------------------------

/** Type alias */
export type IdbCursorHandle = bigint;

/** Handle table for IDBCursor instances */
const _idbCursorhandles = new Map<bigint, IDBCursor>();
let _nextIDBCursor = 1n;

/** Lookup a IDBCursor by handle, throwing if not found. */
function lookupIDBCursor(handle: bigint): IDBCursor {
  const obj = _idbCursorhandles.get(handle);
  if (!obj) {
    throw new Error(`IDBCursor handle ${handle} not found`);
  }
  return obj!;
}

/** Lookup an optional IDBCursor by handle. */
function lookupOptionIDBCursor(handle: bigint | undefined): IDBCursor | null {
  if (handle === undefined || handle === 0n) {
    return null;
  }
  return _idbCursorhandles.get(handle) ?? null;
}
/**
 * `get-source()` operation.
 */
export function IdbCursorGetSource(self: bigint): bigint {
  const obj = lookupIDBCursor(self);
  return (obj as any).source;
}

/**
 * `get-direction()` operation.
 */
export function getDirection(self: bigint): bigint {
  const obj = lookupIDBCursor(self);
  return obj.direction;
}

/**
 * `get-key()` operation.
 */
export function IdbCursorGetKey(self: bigint): string {
  const obj = lookupIDBCursor(self);
  return (obj as any).key;
}

/**
 * `get-primary-key()` operation.
 */
export function IdbCursorGetPrimaryKey(self: bigint): string {
  const obj = lookupIDBCursor(self);
  return (obj as any).primaryKey;
}

/**
 * `get-request()` operation.
 */
export function getRequest(self: bigint): bigint {
  const obj = lookupIDBCursor(self);
  return obj.request;
}

/**
 * `advance()` operation.
 */
export function advance(self: bigint, count: number): void {
  const obj = lookupIDBCursor(self);
  obj.advance(Number(count));
}

/**
 * `continue()` operation.
 */
export function _continue(self: bigint, key: string | undefined): void {
  const obj = lookupIDBCursor(self);
  obj.continue(key as any);
}

/**
 * `continue-primary-key()` operation.
 */
export function continuePrimaryKey(self: bigint, key: string, primaryKey: string): void {
  const obj = lookupIDBCursor(self);
  obj.continuePrimaryKey(key, primaryKey);
}

/**
 * `update()` operation.
 */
export function update(self: bigint, value: string): bigint {
  const obj = lookupIDBCursor(self);
  return obj.update(value);
}

/**
 * `delete()` operation.
 */
export function IdbCursorDelete(self: bigint): bigint {
  const obj = lookupIDBCursor(self);
  return obj.delete();
}

// ---------------------------------------------------------------------------
// WIT interface: idb-cursor-with-value
// ---------------------------------------------------------------------------

/** Type alias */
export type IdbCursorWithValueHandle = bigint;

/** Handle table for IDBCursorWithValue instances */
const _idbCursorWithValuehandles = new Map<bigint, IDBCursorWithValue>();
let _nextIDBCursorWithValue = 1n;

/** Lookup a IDBCursorWithValue by handle, throwing if not found. */
function lookupIDBCursorWithValue(handle: bigint): IDBCursorWithValue {
  const obj = _idbCursorWithValuehandles.get(handle);
  if (!obj) {
    throw new Error(`IDBCursorWithValue handle ${handle} not found`);
  }
  return obj!;
}

/** Lookup an optional IDBCursorWithValue by handle. */
function lookupOptionIDBCursorWithValue(handle: bigint | undefined): IDBCursorWithValue | null {
  if (handle === undefined || handle === 0n) {
    return null;
  }
  return _idbCursorWithValuehandles.get(handle) ?? null;
}
/**
 * `get-value()` operation.
 */
export function IdbCursorWithValueGetValue(self: bigint): string {
  const obj = lookupIDBCursorWithValue(self);
  return obj.value;
}

// ---------------------------------------------------------------------------
// WIT interface: idb-transaction
// ---------------------------------------------------------------------------

/** Type alias */
export type IdbTransactionHandle = bigint;

/** Handle table for IDBTransaction instances */
const _idbTransactionhandles = new Map<bigint, IDBTransaction>();
let _nextIDBTransaction = 1n;

/** Lookup a IDBTransaction by handle, throwing if not found. */
function lookupIDBTransaction(handle: bigint): IDBTransaction {
  const obj = _idbTransactionhandles.get(handle);
  if (!obj) {
    throw new Error(`IDBTransaction handle ${handle} not found`);
  }
  return obj!;
}

/** Lookup an optional IDBTransaction by handle. */
function lookupOptionIDBTransaction(handle: bigint | undefined): IDBTransaction | null {
  if (handle === undefined || handle === 0n) {
    return null;
  }
  return _idbTransactionhandles.get(handle) ?? null;
}
/**
 * `get-object-store-names()` operation.
 */
export function IdbTransactionGetObjectStoreNames(self: bigint): (string)[] {
  const obj = lookupIDBTransaction(self);
  return obj.objectStoreNames;
}

/**
 * `get-mode()` operation.
 */
export function IdbTransactionGetMode(self: bigint): bigint {
  const obj = lookupIDBTransaction(self);
  return obj.mode;
}

/**
 * `get-durability()` operation.
 */
export function getDurability(self: bigint): bigint {
  const obj = lookupIDBTransaction(self);
  return obj.durability;
}

/**
 * `get-db()` operation.
 */
export function getDb(self: bigint): bigint {
  const obj = lookupIDBTransaction(self);
  return obj.db;
}

/**
 * `get-error()` operation.
 */
export function IdbTransactionGetError(self: bigint): bigint | undefined {
  const obj = lookupIDBTransaction(self);
  return obj.error ?? undefined;
}

/**
 * `object-store()` operation.
 */
export function objectStore(self: bigint, name: string): bigint {
  const obj = lookupIDBTransaction(self);
  return obj.objectStore(name);
}

/**
 * `commit()` operation.
 */
export function commit(self: bigint): void {
  const obj = lookupIDBTransaction(self);
  obj.commit();
}

/**
 * `abort()` operation.
 */
export function abort(self: bigint): void {
  const obj = lookupIDBTransaction(self);
  obj.abort();
}

/**
 * `get-onabort()` operation.
 */
export function IdbTransactionGetOnabort(self: bigint): bigint {
  const obj = lookupIDBTransaction(self);
  return obj.onabort;
}

/**
 * `set-onabort()` operation.
 */
export function IdbTransactionSetOnabort(self: bigint, value: bigint): void {
  const obj = lookupIDBTransaction(self);
  obj.onabort = value;
}

/**
 * `get-oncomplete()` operation.
 */
export function getOncomplete(self: bigint): bigint {
  const obj = lookupIDBTransaction(self);
  return obj.oncomplete;
}

/**
 * `set-oncomplete()` operation.
 */
export function setOncomplete(self: bigint, value: bigint): void {
  const obj = lookupIDBTransaction(self);
  obj.oncomplete = value;
}

/**
 * `get-onerror()` operation.
 */
export function IdbTransactionGetOnerror(self: bigint): bigint {
  const obj = lookupIDBTransaction(self);
  return obj.onerror;
}

/**
 * `set-onerror()` operation.
 */
export function IdbTransactionSetOnerror(self: bigint, value: bigint): void {
  const obj = lookupIDBTransaction(self);
  obj.onerror = value;
}

// ---------------------------------------------------------------------------
// WIT interface: navigator-storage
// ---------------------------------------------------------------------------

/** Type alias */
export type NavigatorStorageHandle = bigint;

/** Handle table for NavigatorStorage instances */
const _navigatorStoragehandles = new Map<bigint, NavigatorStorage>();
let _nextNavigatorStorage = 1n;

/** Lookup a NavigatorStorage by handle, throwing if not found. */
function lookupNavigatorStorage(handle: bigint): NavigatorStorage {
  const obj = _navigatorStoragehandles.get(handle);
  if (!obj) {
    throw new Error(`NavigatorStorage handle ${handle} not found`);
  }
  return obj!;
}

/** Lookup an optional NavigatorStorage by handle. */
function lookupOptionNavigatorStorage(handle: bigint | undefined): NavigatorStorage | null {
  if (handle === undefined || handle === 0n) {
    return null;
  }
  return _navigatorStoragehandles.get(handle) ?? null;
}
/**
 * `get-storage()` operation.
 */
export function getStorage(self: bigint): bigint {
  const obj = lookupNavigatorStorage(self);
  const _callResult = obj.storage;
  const handle = _nextStorageManager++;
  _storageManagerhandles.set(handle, _callResult);
  return handle;
}

// ---------------------------------------------------------------------------
// WIT interface: storage-manager
// ---------------------------------------------------------------------------

/** Type alias */
export type StorageManagerHandle = bigint;

/** Handle table for StorageManager instances */
const _storageManagerhandles = new Map<bigint, StorageManager>();
let _nextStorageManager = 1n;

/** Lookup a StorageManager by handle, throwing if not found. */
function lookupStorageManager(handle: bigint): StorageManager {
  const obj = _storageManagerhandles.get(handle);
  if (!obj) {
    throw new Error(`StorageManager handle ${handle} not found`);
  }
  return obj!;
}

/** Lookup an optional StorageManager by handle. */
function lookupOptionStorageManager(handle: bigint | undefined): StorageManager | null {
  if (handle === undefined || handle === 0n) {
    return null;
  }
  return _storageManagerhandles.get(handle) ?? null;
}
/**
 * `persisted()` operation.
 *
 * Async operation: returns request ID, poll with `pollPersisted()`
 */
export function persisted(self: bigint): bigint {
  const requestId = _nextAsyncHandle++;
  const obj = lookupStorageManager(self);
  const promise = obj.persisted()
    .then((result: unknown) => {
      const entry = _asyncHandles.get(requestId);
      if (entry) {
        entry.result = { ok: true, value: result };
      }
    })
    .catch((err: Error) => {
      const entry = _asyncHandles.get(requestId);
      if (entry) {
        entry.result = { ok: false, error: err.message };
      }
    });

  _asyncHandles.set(requestId, { promise, result: null });
  return requestId;
}

/**
 * Poll an async `persisted()` operation.
 * Returns undefined if still pending, or the result if complete.
 */
export function pollPersisted(requestId: bigint): { ok: true; value: bigint } | { ok: false; error: string } | undefined {
  const entry = _asyncHandles.get(requestId);
  if (!entry) {
    return { ok: false, error: `Unknown request ID ${requestId}` };
  }
  return entry.result as { ok: true; value: bigint } | { ok: false; error: string } | null ?? undefined;
}

/**
 * `persist()` operation.
 *
 * Async operation: returns request ID, poll with `pollPersist()`
 */
export function persist(self: bigint): bigint {
  const requestId = _nextAsyncHandle++;
  const obj = lookupStorageManager(self);
  const promise = obj.persist()
    .then((result: unknown) => {
      const entry = _asyncHandles.get(requestId);
      if (entry) {
        entry.result = { ok: true, value: result };
      }
    })
    .catch((err: Error) => {
      const entry = _asyncHandles.get(requestId);
      if (entry) {
        entry.result = { ok: false, error: err.message };
      }
    });

  _asyncHandles.set(requestId, { promise, result: null });
  return requestId;
}

/**
 * Poll an async `persist()` operation.
 * Returns undefined if still pending, or the result if complete.
 */
export function pollPersist(requestId: bigint): { ok: true; value: bigint } | { ok: false; error: string } | undefined {
  const entry = _asyncHandles.get(requestId);
  if (!entry) {
    return { ok: false, error: `Unknown request ID ${requestId}` };
  }
  return entry.result as { ok: true; value: bigint } | { ok: false; error: string } | null ?? undefined;
}

/**
 * `estimate()` operation.
 *
 * Async operation: returns request ID, poll with `pollEstimate()`
 */
export function estimate(self: bigint): bigint {
  const requestId = _nextAsyncHandle++;
  const obj = lookupStorageManager(self);
  const promise = obj.estimate()
    .then((result: unknown) => {
      const entry = _asyncHandles.get(requestId);
      if (entry) {
        entry.result = { ok: true, value: result };
      }
    })
    .catch((err: Error) => {
      const entry = _asyncHandles.get(requestId);
      if (entry) {
        entry.result = { ok: false, error: err.message };
      }
    });

  _asyncHandles.set(requestId, { promise, result: null });
  return requestId;
}

/**
 * Poll an async `estimate()` operation.
 * Returns undefined if still pending, or the result if complete.
 */
export function pollEstimate(requestId: bigint): { ok: true; value: bigint } | { ok: false; error: string } | undefined {
  const entry = _asyncHandles.get(requestId);
  if (!entry) {
    return { ok: false, error: `Unknown request ID ${requestId}` };
  }
  return entry.result as { ok: true; value: bigint } | { ok: false; error: string } | null ?? undefined;
}

// ---------------------------------------------------------------------------
// WIT interface: navigator-locks
// ---------------------------------------------------------------------------

/** Type alias */
export type NavigatorLocksHandle = bigint;

/** Handle table for NavigatorLocks instances */
const _navigatorLockshandles = new Map<bigint, NavigatorLocks>();
let _nextNavigatorLocks = 1n;

/** Lookup a NavigatorLocks by handle, throwing if not found. */
function lookupNavigatorLocks(handle: bigint): NavigatorLocks {
  const obj = _navigatorLockshandles.get(handle);
  if (!obj) {
    throw new Error(`NavigatorLocks handle ${handle} not found`);
  }
  return obj!;
}

/** Lookup an optional NavigatorLocks by handle. */
function lookupOptionNavigatorLocks(handle: bigint | undefined): NavigatorLocks | null {
  if (handle === undefined || handle === 0n) {
    return null;
  }
  return _navigatorLockshandles.get(handle) ?? null;
}
/**
 * `get-locks()` operation.
 */
export function getLocks(self: bigint): bigint {
  const obj = lookupNavigatorLocks(self);
  return obj.locks;
}

// ---------------------------------------------------------------------------
// WIT interface: lock-manager
// ---------------------------------------------------------------------------

/** Type alias */
export type LockManagerHandle = bigint;

/** Handle table for LockManager instances */
const _lockManagerhandles = new Map<bigint, LockManager>();
let _nextLockManager = 1n;

/** Lookup a LockManager by handle, throwing if not found. */
function lookupLockManager(handle: bigint): LockManager {
  const obj = _lockManagerhandles.get(handle);
  if (!obj) {
    throw new Error(`LockManager handle ${handle} not found`);
  }
  return obj!;
}

/** Lookup an optional LockManager by handle. */
function lookupOptionLockManager(handle: bigint | undefined): LockManager | null {
  if (handle === undefined || handle === 0n) {
    return null;
  }
  return _lockManagerhandles.get(handle) ?? null;
}
/**
 * `request()` operation.
 *
 * Async operation: returns request ID, poll with `pollRequest()`
 */
export function request(self: bigint, name: string, callback: bigint): bigint {
  const requestId = _nextAsyncHandle++;
  const obj = lookupLockManager(self);
  const promise = obj.request(name, callback)
    .then((result: unknown) => {
      const entry = _asyncHandles.get(requestId);
      if (entry) {
        entry.result = { ok: true, value: result };
      }
    })
    .catch((err: Error) => {
      const entry = _asyncHandles.get(requestId);
      if (entry) {
        entry.result = { ok: false, error: err.message };
      }
    });

  _asyncHandles.set(requestId, { promise, result: null });
  return requestId;
}

/**
 * Poll an async `request()` operation.
 * Returns undefined if still pending, or the result if complete.
 */
export function pollRequest(requestId: bigint): { ok: true; value: bigint } | { ok: false; error: string } | undefined {
  const entry = _asyncHandles.get(requestId);
  if (!entry) {
    return { ok: false, error: `Unknown request ID ${requestId}` };
  }
  return entry.result as { ok: true; value: bigint } | { ok: false; error: string } | null ?? undefined;
}

/**
 * `query()` operation.
 *
 * Async operation: returns request ID, poll with `pollQuery()`
 */
export function query(self: bigint): bigint {
  const requestId = _nextAsyncHandle++;
  const obj = lookupLockManager(self);
  const promise = obj.getQuery()
    .then((result: unknown) => {
      const entry = _asyncHandles.get(requestId);
      if (entry) {
        entry.result = { ok: true, value: result };
      }
    })
    .catch((err: Error) => {
      const entry = _asyncHandles.get(requestId);
      if (entry) {
        entry.result = { ok: false, error: err.message };
      }
    });

  _asyncHandles.set(requestId, { promise, result: null });
  return requestId;
}

/**
 * Poll an async `query()` operation.
 * Returns undefined if still pending, or the result if complete.
 */
export function pollQuery(requestId: bigint): { ok: true; value: bigint } | { ok: false; error: string } | undefined {
  const entry = _asyncHandles.get(requestId);
  if (!entry) {
    return { ok: false, error: `Unknown request ID ${requestId}` };
  }
  return entry.result as { ok: true; value: bigint } | { ok: false; error: string } | null ?? undefined;
}

// ---------------------------------------------------------------------------
// WIT interface: lock
// ---------------------------------------------------------------------------

/** Type alias */
export type LockHandle = bigint;

/** Handle table for Lock instances */
const _lockHandles = new Map<bigint, Lock>();
let _nextLock = 1n;

/** Lookup a Lock by handle, throwing if not found. */
function lookupLock(handle: bigint): Lock {
  const obj = _lockHandles.get(handle);
  if (!obj) {
    throw new Error(`Lock handle ${handle} not found`);
  }
  return obj!;
}

/** Lookup an optional Lock by handle. */
function lookupOptionLock(handle: bigint | undefined): Lock | null {
  if (handle === undefined || handle === 0n) {
    return null;
  }
  return _lockHandles.get(handle) ?? null;
}
/**
 * `get-name()` operation.
 */
export function LockGetName(self: bigint): string {
  const obj = lookupLock(self);
  return obj.name;
}

/**
 * `get-mode()` operation.
 */
export function LockGetMode(self: bigint): bigint {
  const obj = lookupLock(self);
  return obj.mode;
}

// ---------------------------------------------------------------------------
// Exports
// ---------------------------------------------------------------------------

export default {
  getResult,
  IdbRequestGetError,
  IdbRequestGetSource,
  IdbRequestGetTransaction,
  getReadyState,
  getOnsuccess,
  setOnsuccess,
  IdbRequestGetOnerror,
  IdbRequestSetOnerror,
  getOnblocked,
  setOnblocked,
  getOnupgradeneeded,
  setOnupgradeneeded,
  getOldVersion,
  getNewVersion,
  getIndexedDb,
  fetch,
  pollFetch,
  getPerformance,
  getOrigin,
  getIsSecureContext,
  getCrossOriginIsolated,
  reportError,
  btoa,
  atob,
  setTimeout,
  clearTimeout,
  setInterval,
  clearInterval,
  queueMicrotask,
  createImageBitmap,
  pollCreateImageBitmap,
  structuredClone,
  getCaches,
  getCrypto,
  open,
  deleteDatabase,
  databases,
  cmp,
  IdbDatabaseGetName,
  getVersion,
  IdbDatabaseGetObjectStoreNames,
  transaction,
  close,
  createObjectStore,
  deleteObjectStore,
  IdbDatabaseGetOnabort,
  IdbDatabaseSetOnabort,
  getOnclose,
  setOnclose,
  IdbDatabaseGetOnerror,
  IdbDatabaseSetOnerror,
  getOnversionchange,
  setOnversionchange,
  IdbObjectStoreGetName,
  IdbObjectStoreSetName,
  IdbObjectStoreGetKeyPath,
  getIndexNames,
  IdbObjectStoreGetTransaction,
  getAutoIncrement,
  put,
  add,
  IdbObjectStoreDelete,
  clear,
  IdbObjectStoreGet,
  IdbObjectStorePollGet,
  IdbObjectStoreGetKey,
  IdbObjectStoreGetAll,
  IdbObjectStoreGetAllKeys,
  IdbObjectStoreGetAllRecords,
  IdbObjectStoreCount,
  IdbObjectStoreOpenCursor,
  IdbObjectStoreOpenKeyCursor,
  index,
  createIndex,
  deleteIndex,
  IdbIndexGetName,
  IdbIndexSetName,
  getObjectStore,
  IdbIndexGetKeyPath,
  getMultiEntry,
  getUnique,
  IdbIndexGet,
  IdbIndexPollGet,
  IdbIndexGetKey,
  IdbIndexGetAll,
  IdbIndexGetAllKeys,
  IdbIndexGetAllRecords,
  IdbIndexCount,
  IdbIndexOpenCursor,
  IdbIndexOpenKeyCursor,
  getLower,
  getUpper,
  getLowerOpen,
  getUpperOpen,
  only,
  lowerBound,
  upperBound,
  bound,
  includes,
  IdbRecordGetKey,
  IdbRecordGetPrimaryKey,
  IdbRecordGetValue,
  IdbCursorGetSource,
  getDirection,
  IdbCursorGetKey,
  IdbCursorGetPrimaryKey,
  getRequest,
  advance,
  _continue,
  continuePrimaryKey,
  update,
  IdbCursorDelete,
  IdbCursorWithValueGetValue,
  IdbTransactionGetObjectStoreNames,
  IdbTransactionGetMode,
  getDurability,
  getDb,
  IdbTransactionGetError,
  objectStore,
  commit,
  abort,
  IdbTransactionGetOnabort,
  IdbTransactionSetOnabort,
  getOncomplete,
  setOncomplete,
  IdbTransactionGetOnerror,
  IdbTransactionSetOnerror,
  getStorage,
  persisted,
  pollPersisted,
  persist,
  pollPersist,
  estimate,
  pollEstimate,
  getLocks,
  request,
  pollRequest,
  query,
  pollQuery,
  LockGetName,
  LockGetMode
};
