name: Format
on:
  pull_request:
    paths:
      - '.github/workflows/fmt.yml'
      - 'packages/**/*'
      - 'examples/**/*'
      - 'Cargo.toml'
  push:
    branches: [master, dev]

jobs:
  format:
    name: Format
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt

      - name: Run fmt
        run: cargo fmt --all -- --check
